chainflip-io/chainflip-backend

Cargo.lock
state-chain/pallets/cf-swapping/Cargo.toml
state-chain/pallets/cf-swapping/src/tests.rs

Closes: PRO-966
Added tests:
- check broker fee calculation is correct
- check broker fee cannot exceed amount swapped
- check broker fee is correctly subtracted from the amount swapped
- check swap fails if the amount swapped is too low

Test: added tests to swapping pallet

---

state-chain/pallets/cf-pools/src/migrations/v1.rs

As you suggested, I meant to add this in the original. It has been tested using the try-runtime script.

fix: add missing migration hook

---

state-chain/amm/src/common.rs
state-chain/amm/src/lib.rs
state-chain/amm/src/tests.rs
state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

RPC "cf_pool_orderbook":
Takes base_asset, quote_asset, and orders.
"base_asset": The returned amounts are in units of the base_asset.
"quote_asset": The returned sqrt_prices are fixed point nubers with 96 fractional bits, and are in units of the quote asset. So in the below example the sqrt_prices are in USDC, but if you flipped the order of the base and quote, they would be in ETH. 
"orders" the approximate number of asks/bids you want (min and max are 1-16384).
Example:
request:
```
{"id":1, "jsonrpc":"2.0", "method": "cf_pool_orderbook", "params": ["ETH", "USDC", 10]}
```
returns:
```
{
"jsonrpc": "2.0",
"result": {
"asks": [
{
"amount": "0x54b2cec31723f8b04",
"sqrt_price": "0x2091b342e50d7f26cdc582"
},
{
"amount": "0x5b475d13fc0374e",
"sqrt_price": "0x1e38a26ccc8cad8ff5ed7d0e"
},
{ …
```

feat: simulate order book RPC

---

api/bin/chainflip-cli/src/main.rs

chore: clarify that the hash is of the SC transaction

---

bouncer/commands/try_runtime_upgrade.ts
bouncer/shared/try_runtime_upgrade.ts
state-chain/amm/src/range_orders/v1.rs

fix: correct amm migration

---

localnet/init/scripts/start-lp-api.sh

Just copied this from the broker start script

fix: lp logs in localnet

---

engine/src/btc/rpc.rs

Closes: PRO-1012
If the transaction is already in the chain, we don't the engine to report failure, which would trigger a retry immediate. We just need to wait for the witnessing to see the transaction.

fix: transaction already in chain reported as success

---

.cargo/config.toml
.github/workflows/_20_build.yml
.github/workflows/ci-main.yml
.github/workflows/release-berghain.yml

Here's a job of it running on PR to main: https://github.com/chainflip-io/chainflip-backend/actions/runs/7098370962
(since this PR's code changes won't actually run until it's in main).
Will allow me to continue on adding upgrades to the CI.

feat: try-runtime build to CI

---

state-chain/pallets/cf-broadcast/src/benchmarking.rs

fix: benchmark

---

state-chain/pallets/cf-environment/src/migrations.rs

Fixes the current release version hooks

fix: current release version bumped checks

---

bouncer/shared/new_swap.ts

Fixes bouncer on resetting backspin

fix: broker endpoint as env var

---

bouncer/commands/go_bananas.ts

After the recent LP API changes, this fixes banana mode

Updated banana mode to adhere to new LP API

---

engine/src/witness/common/chunked_chain_source/chunked_by_time/builder.rs
engine/src/witness/common/chunked_chain_source/latest_then.rs

Closes: PRO-990
Extracted the logic into a spearate function to make testing easier. Added some basic tests. @kylezs you mentioned a "full suite" of tests, is there some functionality that I'm overlooking here?

test: latest_then adapter testing

---

state-chain/pallets/cf-ingress-egress/src/lib.rs

also: register net deposit amount, not gross.

fix: keep utxos even if swallowed (PRO-1068)

---

state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-pools/src/migrations.rs
state-chain/pallets/cf-pools/src/migrations/v2.rs
state-chain/runtime/src/lib.rs

I'm not sure how to do the resetting thought

fix: network fee

---

engine/src/witness/common/chain_source.rs
engine/src/witness/common/chain_source/strictly_monotonic.rs
engine/src/witness/common/chunked_chain_source/chunked_by_time/chain_tracking.rs
utilities/src/with_std/metrics.rs

Closes: PRO-986
Added a metric that reports the last reported block, this should help operators to quickly check if their engine is working correctly and reporting blocks from the external chains

feat: add chaintracking metric

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
engine/Cargo.toml
engine/src/witness/btc/btc_deposits.rs
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

fix: bitcoin deposit witness code (PRO-1078)

---

.github/workflows/_40_post_check.yml
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

Closes: PRO-1084
A deposit can be ignored for two reasons, either they simply submitted below the minimum deposit amount - or they do not have enough to pay for the fees of the requisite transactions.
I created a separate issue PRO-1085 to test this withheld fee functionality.

chore: add reason to DepositIgnored event

---

Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-broker-api/src/main.rs
api/bin/chainflip-lp-api/Cargo.toml
api/bin/chainflip-lp-api/src/main.rs
api/lib/src/lib.rs
engine/src/state_chain_observer/client/chain_api.rs
engine/src/state_chain_observer/client/mod.rs
utilities/Cargo.toml
utilities/src/with_std.rs

* feat: order_fills rpc (PRO-1044)
* formatting

feat: order_fills rpc (PRO-1044) (#4376)

---

engine/src/dot/http_rpc.rs
utilities/src/lib.rs

Closes: PRO-1086
Tested against getblock, onfinality, localnet, and our perseverance node, all work.

fix: remove meaningless bearer token

---

api/bin/chainflip-ingress-egress-tracker/src/main.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing/dot.rs
engine/src/main.rs
engine/src/state_chain_observer/client/mod.rs
engine/src/witness/common.rs
engine/src/witness/common/chunked_chain_source/chunked_by_vault/deposit_addresses.rs
engine/src/witness/common/chunked_chain_source/chunked_by_vault/egress_items.rs
engine/src/witness/common/chunked_chain_source/chunked_by_vault/monitored_items.rs
engine/src/witness/common/epoch_source.rs
engine/src/witness/dot.rs
engine/src/witness/eth.rs

fix: Avoid SCC "sparse stream" error in CLI when making requests (PRO-998)

---

api/bin/chainflip-ingress-egress-tracker/src/store.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc_mempool.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs

refactor(ingress-egress-tracker): configurable expiry times [WEB-761]

---

api/bin/chainflip-ingress-egress-tracker/README.md
api/bin/chainflip-ingress-egress-tracker/src/settings.rs

The env vars in the README were incorrect.

doc: correct env vars

---

.github/workflows/_40_post_check.yml
.github/workflows/upgrade-test.yml
bouncer/commands/try_runtime_upgrade.ts
bouncer/shared/submit_runtime_upgrade.ts
bouncer/shared/try_runtime_upgrade.ts
bouncer/shared/upgrade_network.ts
localnet/init/scripts/start-broker-api.sh
state-chain/pallets/cf-environment/src/migrations.rs

Fixes a few issues with the ugprade test - it's stil not currently working on main - still looking into that (I suspect there's a broken migration on main - but this should help).

fix: await finalisation before starting broker

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2024-0006

fix: RUSTSEC-2024-0006

---

Cargo.lock
state-chain/cfe-events/Cargo.toml
state-chain/cfe-events/src/lib.rs
state-chain/cfe-events/src/tests.rs

Closes PRO-1100
Just adding a simple test to help us detect whenever me make a change that would break compatibility between CFE and SC (at least when it comes to reading events).

Test: cfe event encoding

---

utilities/src/with_std/metrics.rs

Closes: PRO-1088
Added cfe_ prefix to the engine's metrics in order to make it easier to understand where the metric comes from in prometheus

added cfe_ prefix to engine metrics

---

engine/src/retrier.rs

Closes: PRO-1120
Increment the metric for request when the request is received rather than when it completes (in case a request never completes we weren't accounting for it)

increment metric when the request is received 

---

state-chain/pallets/cf-cfe-interface/src/lib.rs

fix: :bug: fixed storage version

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-ingress-egress-tracker/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml

Bumps version and updates the changelog

bump version, update changelog

---

state-chain/pallets/cf-broadcast/src/migrations/v3.rs

Closes: PRO-1133
Changed the post-upgrade check to fix migration test.
Tested with try-runtime on-runtime-upgrade against mainnet

Fixed runtime migration test for broadcast pallet

---

bouncer/shared/json_rpc.ts

Closes: PRO-1107
Localhost wasn't working in some cases - 127.0.0.1 always works.

fix: use 127.0.0.1 instead of localhost

---

bouncer/full_bouncer.sh
bouncer/run.sh

Add a transaction to Arbitrum to make sure Arbitrum is running correctly. Before fixing it in #4455 Arbitrum was broken in CI and we didn't know.
This can be removed once we have a functional Arbitrum bouncer with all the CF Arbitrum logic but let's make sure we don't break it before then.

Ensure Arbitrum is correctly running in CI

---

.github/workflows/ci-nightly.yml
.github/workflows/upgrade-test.yml

Closes: PRO-1153
Can see the job work here: https://github.com/chainflip-io/chainflip-backend/actions/runs/7709180916 
Will run an upgrade to the latest main version every night.

feat: nightly upgrade

---

bouncer/shared/try_runtime_upgrade.ts

Closes: PRO-1138
It's not possible to run the command again against the state if an error occurs on a nightly job, so better reporting the error makes things much nicer. 
Basically I need to capture the stdout without printing anything in the success case (which prints a lot of garbage that's not necessary to see), which is why this tempfile solution is required.
You can test:
Success:
check out release, build, start localnet, checkout this branch, build with --release and --features try-runtime. run `./commands/try_runtime_upgrade.ts --block latest --runtime ../target/release/wbuild/state-chain-runtime/state_chain_runtime.compact.compressed.wasm
Try runtime using runtime at …

chore: better errors for try_runtime_upgrade command

---

.github/workflows/_40_post_check.yml
bouncer/shared/gaslimit_ccm.ts

Closes: PRO-1095
Fixing CCM test. It was getting the `ccm gas` swap event, which was then getting the wrong swapID. The issue was uncovered after merging #4458 into main.

chore: fix swapScheduled

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/scripts/benchmark-all.sh

Fixes benchmarks by ensuring that egress scheduling never fails during benchmarks.

fix: force egress success for benchmarks

---

.github/CODEOWNERS

Adding more codeowners

---

.github/workflows/_40_post_check.yml
bouncer/commands/send_sol.ts
bouncer/full_bouncer.sh
bouncer/package.json
bouncer/pnpm-lock.yaml
bouncer/run.sh
bouncer/shared/send_sol.ts
bouncer/shared/utils.ts
localnet/manage.sh

Add basic SOL transfer to the bouncer to make sure Solana is running properly and that we don't break it before we start adding the logic to the protocol.
For now, allow the SOL transfer to be skipped for anyone that doesn't have Solana installed yet to avoid issues. I will remove that once Solana is integrated.

chore: add basic check solana

---

Cargo.lock

fix: update `snow` package to fix audit issue

---

.github/workflows/_02_retrieve-bins.yml
.github/workflows/_20_build.yml
.github/workflows/_24_docker.yml
.github/workflows/_25_package.yml
.github/workflows/_30_publish.yml
.github/workflows/_40_post_check.yml
.github/workflows/_50_release.yml
.github/workflows/_60_upload.yml
.github/workflows/ci-benchmarks.yml

Cherry pick 23006ecb78dd1882551e361007fc026e5d8fdfcc

Chore/cherry pick build fixes to release 1.2

---

localnet/init/scripts/start-ingress-egress-tracker.sh
localnet/manage.sh

Closes: PRO-1099
Added option to run ingress-egress-tracker when starting up localnet

feat: ingress-egress-tracker on localnet startup

---

state-chain/runtime/src/lib.rs

This was erroneously removed in #4478 . I'm adding it back here.

fix: re-add version update

---

state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/chainflip/cons_key_rotator.rs
state-chain/runtime/src/lib.rs

Provided that we are about to introduce two more foreign-chains, this might be increase ergonomics a tiny bit.

feat: extensible multi-key rotator

---

state-chain/cf-integration-tests/src/authorities.rs
state-chain/cf-integration-tests/src/broadcasting.rs
state-chain/pallets/cf-broadcast/src/benchmarking.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-broadcast/src/tests.rs
state-chain/pallets/cf-emissions/src/mock.rs
state-chain/pallets/cf-environment/src/mock.rs
state-chain/pallets/cf-funding/src/lib.rs
state-chain/pallets/cf-funding/src/mock.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/key_rotator.rs
state-chain/pallets/cf-threshold-signature/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/mock.rs
state-chain/pallets/cf-threshold-signature/src/tests.rs
state-chain/pallets/cf-vaults/src/mock.rs
state-chain/pallets/cf-vaults/src/tests.rs
state-chain/pallets/cf-vaults/src/vault_activator.rs
state-chain/traits/src/lib.rs
state-chain/traits/src/mocks/broadcaster.rs

Closes: PRO-1062
- Modified rotation to wait for ThresholdSignature success before switching to NewKeysActivated
- Modified tests to match the new behaviour

fix: Wait for ThresholdSignature success before switching to NewKeysActivated

---

.cargo/config.toml
contract-interfaces/sol-program-idls/download-sol-program-idls.sh
contract-interfaces/sol-program-idls/v0.1.1/cf_tester.json
contract-interfaces/sol-program-idls/v0.1.1/vault.json
localnet/docker-compose.yml

Pulling Solana image by tag.
Updated tag to include the cf_tester program.
Import latest Solana IDL from that tag.

Solana: update image to latest tag

---

api/lib/src/lib.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs

We should have the asset on here.
Is breaking.

chore: add asset to withdrawal event

---

localnet/manage.sh

Closes: PRO-1194
Added a check around docker login such that if the login fails we print a meaningful error, the check is done both when doing the initial setup and also when trying to build a localnet

log meaningful message if docker login fails

---

Cargo.lock

fix: RUSTSEC-2024-0019

---

Cargo.lock
state-chain/runtime-upgrade-utilities/Cargo.toml
state-chain/runtime-upgrade-utilities/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/migrations.rs
state-chain/runtime/src/migrations/housekeeping.rs

Adds a housekeeping migration to clean up state when we upgrade the network.

chore: migration housekeeping

---

bouncer/commands/get_proposed_runtime.ts

Closes: PRO-1239
The previous version still contained the SCALE length prefix and thus resulted in an invalid runtime.

fix "get_proposed_runtime" command

---

Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-ingress-egress-tracker/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

1.3 has been tagged, so bumping main to 1.4.

chore: bump main versions to 1.4

---

state-chain/pallets/cf-chain-tracking/src/migrations/v2.rs
state-chain/runtime/src/migrations/arbitrum_integration.rs

I think I found a likely cause of the try-runtime failures.

chore: add arb impl for chain tracking migration

---

state-chain/pallets/cf-threshold-signature/src/migrations/v4.rs
state-chain/runtime/src/migrations/arbitrum_integration.rs

Another attempt to fix the try-runtime issue.

chore: try to fix runtime upgrade checks

---

state-chain/runtime/src/lib.rs

fix: change pallet ordering to prevent breakage

---

ci/docker/development/rust-base.Dockerfile

chore: install cargo make on rust-base

---

state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-pools/src/mock.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs
state-chain/traits/src/liquidity.rs
state-chain/traits/src/mocks/lp_balance.rs

fix: return rpc error

---

engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs

See commit messages.
**Note: This is NOT the cause of PRO-1250**

fix: submission watcher could confuse/lose track of submissions

---

state-chain/pallets/cf-pools/src/benchmarking.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-pools/src/migrations.rs
state-chain/pallets/cf-pools/src/migrations/rename_slippage_to_price_impact.rs
state-chain/pallets/cf-pools/src/tests.rs
state-chain/pallets/cf-pools/src/weights.rs

Closes: PRO-1254
Renaming of slippage -> price delta

fix: rename slippage -> price impact

---

.github/workflows/upgrade-test.yml

1.3 is tagged now, so can remove this temp fix

chore: remove temp for 1.2 -> 1.3 upgrade test

---

state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-funding/src/lib.rs
state-chain/pallets/cf-governance/src/lib.rs
state-chain/pallets/cf-reputation/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/lib.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-witnesser/src/lib.rs
state-chain/runtime/src/lib.rs

Closes: PRO-913
Changed some Validator extrinsic to DispatchClass::Operational
Adjusted DispatchClass::Normal weight (from 75%) to 25% in the Runtime

Changed some extrinsics to DispatchType::Operational

---

state-chain/primitives/src/chains/assets.rs

fix: typo in the error message

---

utilities/src/with_std/metrics.rs

Closes: PRO-1260
Updated histogram buckets to better capture ceremonies/stages duration

feat: update metric's buckets values

---

state-chain/runtime/src/lib.rs

This should not have been commented out.

fix: uncomment pools pallet migration

---

Cargo.lock
api/bin/chainflip-ingress-egress-tracker/Cargo.toml

Fix cargo audit issue.
Also noticed an unused dep while I was here.

chore: fix cargo audit

---

api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
api/lib/src/lib.rs
api/lib/src/queries.rs
engine/src/lib.rs
engine/src/state_chain_observer/client.rs
engine/src/state_chain_observer/sc_observer/tests.rs
engine/src/witness/evm/key_manager.rs

Targets the feat/cfe-shared branch
Closes: PRO-1297
`wait_for_required_version` was always set to false, and so this isn't required anymore, as we always error out and let the runner handle the error code returned.

chore: remove wait for required version

---

bouncer/shared/upgrade_network.ts
state-chain/runtime/src/migrations/arbitrum_integration.rs

Was failing after upgrade because this wasn't set.

fix: set initial arb block

---

bouncer/shared/submit_runtime_upgrade.ts
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/migrations/add_boost_pools.rs

Closes: PRO-1292
Added the pool created event and made it get emitted when the migration that creates the pools gets ran.
Tested it on localnet 1..3.0 -> 1.4.0 upgrade test.

feat: add pool created events

---

PRACTICES.md
README.md
api/bin/chainflip-ingress-egress-tracker/README.md
contract-interfaces/README.md
engine/README.md
state-chain/TROUBLESHOOTING.md
state-chain/docs/docker-compose.md
state-chain/pallets/cf-flip/README.md
state-chain/pallets/cf-funding/README.md
state-chain/pallets/cf-reputation/README.md
state-chain/pallets/cf-threshold-signature/README.md
state-chain/pallets/cf-validator/README.md

* Spellchecked all .md docs
* Updated TOUBLESHOOTING

chore: fixed typo in docs

---

.github/workflows/upgrade-test.yml
bouncer/commands/setup_arb_vault.ts
bouncer/commands/setup_swaps.ts
bouncer/commands/setup_vaults.ts
bouncer/shared/initialize_new_chains.ts
bouncer/shared/setup_arb_vault.ts
bouncer/shared/setup_swaps.ts
bouncer/shared/submit_runtime_upgrade.ts
bouncer/shared/upgrade_network.ts
bouncer/shared/utils.ts
engine/src/witness/arb.rs
engine/src/witness/common/chain_source/shared.rs
state-chain/runtime/src/migrations/arbitrum_integration.rs
utilities/src/with_std/spmc.rs

Fixes:
- setup the arbitrum vault as part of the upgrade
- use correct contract addresses in arbitrum migration
- add arbitrum liquidity and boost liquidity as part of the upgrade

fix: arb vault rotation migration

---

state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Closes: PRO-1323 
Returns all pools for all chains in a single call
Usage:
`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "cf_boost_pools_depth"}' http://localhost:9944`
<details><summary>Response</summary>
<p>
```javascript
{
"jsonrpc": "2.0",
"result": [
{
"asset": {
"chain": "Ethereum",
"asset": "FLIP"
},
"tier": 30,
"available_amount": 0
},
{
"asset": {
"chain": "Ethereum",
"asset": "FLIP"
},
"tier": 5,
"available_amount": 0
},
{
"asset": {
"chain": "Ethereum",
"asset": "FLIP"
},
"tier": 10,
"available_amount": 0
},
{
"asset": {
"chain": "Ethereum",
"asset": "ETH"
},
"tier": 30,
"available_amount": 0
},
{
"asset": {
"chain": "Ethereum",
"asset": "ETH"
},
"tier": 5,
"available_amount": 0
}, …
```

feat: cf_boost_pools_depth rpc

---

.cargo/config.toml
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine/Cargo.toml
engine/src/dot/http_rpc.rs
engine/src/witness/dot.rs
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml

Fixes a bug introduced here: https://github.com/chainflip-io/chainflip-backend/pull/4388/files#diff-1015fc028d6f372919e563c645da89d8d3dd0fce1ec9ef4ef0400a5774b18541

fix: dot metadata update

---

state-chain/pallets/cf-ingress-egress/src/boost_pool.rs

Closes: PRO-1299
Just adding a doc comment and using DefaultNoBound to address comments in https://github.com/chainflip-io/chainflip-backend/pull/4698.

chore: boost cleanup

---

state-chain/runtime/src/safe_mode.rs

chore: arbitrum witnesser permission

---

state-chain/pallets/cf-swapping/src/lib.rs

Noticed this when looking at swapping pallet the other day.

chore: inline and functional split and group

---

state-chain/chains/src/btc.rs

Closes: PRO-1360
Egress fees only included the base transaction and a single output, but a typical egress also needs to spend a vault utxo and send some change back to the vault. This PR includes these missing aspects into the egress fee

Realistic BTC egress fees

---

.github/workflows/upgrade-test.yml

chore: change CI command

---

state-chain/pallets/cf-validator/src/migrations/authorities.rs
state-chain/runtime/src/migrations/active_bidders.rs

Just fixes some build warnings related to unused imports

chore: resolve build warnings

---

bouncer/shared/lp_api_test.ts

fix: wait for new balance on transfer asset

---

state-chain/pallets/cf-ingress-egress/src/migrations/add_boost_pools.rs
state-chain/pallets/cf-ingress-egress/src/migrations/multiple_brokers.rs
state-chain/pallets/cf-swapping/src/benchmarking.rs

Fixes the runtime upgrade for the ingress/egress pallet.

chore: fix storage migration for ingress-egress pallet

---

.github/workflows/ci-cherry-pick.yml

v3 is deprecated and failing the linter check

chore: bump create pull request version

---

bouncer/shared/lp_api_test.ts
state-chain/pallets/cf-lp/src/tests.rs

chore: move lp balance integrity check to unit test

---

api/bin/chainflip-lp-api/src/main.rs
state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-lp/src/tests.rs
state-chain/pallets/cf-pools/src/mock.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs
state-chain/traits/src/liquidity.rs
state-chain/traits/src/mocks/lp_balance.rs

Renamed custom rpc method to better reflect the actual behaviour, while keeping the old one for backwards compatibility as alias.

Chore: rename cf_asset_balances to cf_asset_free_balances

---

bouncer/.eslintrc.json
bouncer/commands/check_witnesses.ts
bouncer/commands/go_bananas.ts
bouncer/polkadot/keyring.ts
bouncer/polkadot/util-crypto.ts
bouncer/shared/broker_fee_collection.ts
bouncer/shared/cf_governance.ts
bouncer/shared/fund_flip.ts
bouncer/shared/fund_redeem.ts
bouncer/shared/lp_api_test.ts
bouncer/shared/multiple_members_governance.ts
bouncer/shared/new_dot_address.ts
bouncer/shared/new_statechain_address.ts
bouncer/shared/perform_swap.ts
bouncer/shared/polkadot_keyring.ts
bouncer/shared/polkadot_runtime_update.ts
bouncer/shared/provide_liquidity.ts
bouncer/shared/range_order.ts
bouncer/shared/redeem_flip.ts
bouncer/shared/setup_swaps.ts
bouncer/shared/swapping.ts
bouncer/shared/try_runtime_upgrade.ts
bouncer/shared/utils.ts
bouncer/tests/double_deposit.ts
bouncer/tests/eth_witness_test.ts

refactor(bouncer): ensure crypto ready

---

.github/workflows/ci-cherry-pick.yml
state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/primitives/src/lib.rs

Cherry picking https://github.com/chainflip-io/chainflip-backend/pull/4857 onto 1.4.
Also cherry picked ce323a82cc3cd0addf61b1bec445fc3a876c0b8c as per @ahasna's request (to fix ci warning).

pick: consistent boost fee

---

bouncer/shared/gaslimit_ccm.ts

Adjust failing CCM swap: https://github.com/chainflip-io/chainflip-backend/actions/runs/9143629312/job/25140649011

test: adjust btc eth ccm

---

.github/workflows/ci-development.yml
bouncer/shared/gaslimit_ccm.ts
bouncer/shared/send_evm.ts

Add a retrial mechanism for EVM transactions due to the nonce errors seen in CI: https://github.com/chainflip-io/chainflip-backend/actions/runs/9135739141/job/25211510837
Error comes from transactions not being submitted necessarily in the right order which causes the node to reject them.

Bouncer: Add retrial mechanism for EVM broadcasts

---

localnet/init/scripts/start-node.sh

Picks necessary part of: #4876 into release, since the try-runtime needs to download state from the old release.

fix: increase localnet chainflip-node request and response size 1.4

---

state-chain/cf-integration-tests/src/swapping.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-pools/src/tests.rs
state-chain/primitives/src/chains/assets.rs
state-chain/runtime/src/lib.rs
state-chain/traits/src/lib.rs
state-chain/traits/src/mocks/asset_converter.rs

Cherrypick commit 1459914514b083a9f12a575c33007d3da21514dd (implements #4834) onto release/1.4

fix: prevent liquidity saturation during fee estimation (#4834)

---

bouncer/shared/upgrade_network.ts

Logs version correctly here: https://github.com/chainflip-io/chainflip-backend/actions/runs/9170075494
- Correctly check the version for parsing

fix: check version correctly

---

state-chain/chains/src/any.rs
state-chain/chains/src/arb.rs
state-chain/chains/src/btc.rs
state-chain/chains/src/dot.rs
state-chain/chains/src/eth.rs
state-chain/chains/src/lib.rs
state-chain/chains/src/mocks.rs
state-chain/chains/src/none.rs

chore: remove unused associated type

---

.github/workflows/upgrade-test.yml

fix: add merge group for downloading

---

bouncer/commands/add_boost_funds.ts
bouncer/commands/create_boost_pools.ts
bouncer/commands/new_swap.ts
bouncer/commands/provide_liquidity.ts
bouncer/commands/setup_boost_pools.ts
bouncer/commands/stop_boosting.ts
bouncer/shared/boost.ts
bouncer/shared/broker_fee_collection.ts
bouncer/shared/gaslimit_ccm.ts
bouncer/shared/lp_api_test.ts
bouncer/shared/new_swap.ts
bouncer/shared/perform_swap.ts
bouncer/shared/polkadot_runtime_update.ts
bouncer/shared/provide_liquidity.ts
bouncer/shared/setup_boost_pools.ts
bouncer/shared/setup_swaps.ts
bouncer/shared/submit_runtime_upgrade.ts
bouncer/shared/utils.ts
bouncer/tests/all_concurrent_tests.ts
bouncer/tests/boost_test.ts
bouncer/tests/double_deposit.ts
bouncer/tests/rotation_barrier.ts
state-chain/pallets/cf-ingress-egress/src/lib.rs

PIcks two commits from main into release so bouncer test commands are available:
- f010979264419b0e53a074db5460f52030d1cbcf
- 9828707bde860a103825bbf5feac31db227f8e83

pick: bouncer for boost

---

Cargo.lock
state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/snapshots/custom_rpc__test__swap_output_serialization.snap
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-pools/Cargo.toml
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-pools/src/tests.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/mock.rs
state-chain/pallets/cf-swapping/src/tests.rs
state-chain/pallets/cf-validator/src/migrations/authorities.rs
state-chain/primitives/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs
state-chain/traits/src/liquidity.rs
utilities/src/with_std/rpc.rs

cherry-picks 4a942f78782bb407522f1750abb2234304cac9d9 (#4778) onto release/1.4

cherry-pick #4778

---

state-chain/pallets/cf-threshold-signature/src/key_rotator.rs
state-chain/pallets/cf-vaults/src/tests.rs
state-chain/pallets/cf-vaults/src/vault_activator.rs

Closes: PRO-1408
fixes the vault activation and introduces the ```ChainInitialized``` check while activating the key.

fix: vault activation and initialization

---

state-chain/pallets/cf-threshold-signature/src/key_rotator.rs
state-chain/pallets/cf-vaults/src/tests.rs
state-chain/pallets/cf-vaults/src/vault_activator.rs

pick: fix: vault activation and initialization #4902

---

bouncer/shared/gaslimit_ccm.ts

Cherry picks #4908 (commit 512cb60bae1d7679afcf6ffd1505b9a12f8290e5) onto release/1.4

chore: ccm gas limit (#4908)

---

Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/chainflip/decompose_recompose.rs
state-chain/runtime/src/lib.rs

pick: fix: use median for base_fee and gas_fee_multiplier for arbitrum #4914

---

.github/workflows/upgrade-test.yml
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-ingress-egress-tracker/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/chainflip/decompose_recompose.rs
state-chain/runtime/src/lib.rs

Select the median value for base fee and gas_fee_multiplier as Arbitrum nodes do not necessarily have the same idea of what these are. See comment in the PR for why this is required.

fix: use median for base_fee and gas_fee_multiplier for arbitrum

---

bouncer/shared/contract_swap.ts
bouncer/shared/perform_swap.ts
bouncer/shared/swapping.ts

See #4917 
Help to debug some flakiness.

pick: feat (bouncer): add swapContext to contract swaps (#4917)

---

bouncer/shared/multiple_members_governance.ts
bouncer/shared/utils.ts

See: #4912 
To fix some flakiness.

pick: fix: more robust governance bouncer test (#4912)

---

.github/workflows/ci-development.yml
bouncer/shared/setup_swaps.ts

Trying to tackle the flakyness in the bouncer where it ends up with the swaps getting stuck and not being executed.
Our best guess at the moment is that it's lack of liquidity.
Kyle tested locally too 👍

chore: increase bouncer liquidity

---

bouncer/shared/setup_swaps.ts

See #4924 - picking here to reduce flakiness here too.

pick: chore: increase bouncer liquidity (#4924)

---

CHANGELOG.md

chore: update changelog for 1.4.2

---

bouncer/shared/utils/substrate.ts

fix(bouncer): change field name

---

engine/multisig/src/crypto/ed25519.rs

As discussed, this checks the primitives/operations that would be used by our ed25519 multisig instance against the "reference" implementation used by Solana.

test: ed25519 verification

---

api/bin/chainflip-cli/src/main.rs
api/bin/chainflip-cli/src/settings.rs
api/lib/src/queries.rs
state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/monitoring.rs
state-chain/node/src/service.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/monitoring_apis.rs
state-chain/runtime/src/runtime_apis.rs

Closes: PRO-1274
Added a new list of RPCs which will be used for monitoring purposes such that if something is going to change in the state-chain it is not breaking the compatibility with our monitoring system

feat: add monitoring RPCs

---

.github/workflows/_25_package.yml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs

This is failing because old version doesn't match. Can improve a few things here first before just updating it.
Closes: PRO-1395
Previously the old dylib was manually copied into the repo. For release builds we can now use the one that was built in the CI.

chore: use ci built shared libs

---

.github/workflows/_41_test_benchmarks.yml
.github/workflows/ci-development.yml
.github/workflows/ci-main.yml
.github/workflows/release-sisyphos.yml

Closes: PRO-1365
After a little thinking, it's not really that expensive to run the benchmarks (with 1 repetition and 2 steps), so figured would just run it as a standard check on PRs, on main and release branch. Rather than only on the merge queue. We can adjust later if need be.

feat: test benchmarks in CI

---

.github/workflows/_40_post_check.yml
.github/workflows/upgrade-test.yml
bouncer/shared/contract_swap.ts
bouncer/shared/swapping.ts

Prints extrinsics and events to a file after we detect failure of bouncer to better investigate what is going wrong in failures, especially the flaky ones which are hard to reproduce.
I removed the SwapScheduled tracking for the contrat swap, which is just an intermediate step check, isn't checking anything important. I was debugging and can see that the swap is actually scheduled, but for contract swaps, if the swap is executed very quickly, then it's possible the observeEvent code hasn't started until *after* the SwapScheduled event occurs - meaning the test will hang there forever.

feat: chain state on bouncer failure

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs

Closes: PRO-1423
Disallow adding of 0 boost funds, which creates some minor extra state.

fix: cannot add 0 funds to boost pool

---

bouncer/shared/broker_fee_collection.ts
bouncer/shared/multiple_members_governance.ts

Part of: PRO-1411
Converts more to the new observeEvent function - started here #4907

refactor (bouncer): use new observe event for broker fee collection and gov members

---

bouncer/.eslintrc.json
bouncer/commands/create_raw_btc_tx.ts
bouncer/commands/explorer.ts
bouncer/commands/get_balance.ts
bouncer/commands/get_btc_balance.ts
bouncer/commands/go_bananas.ts
bouncer/commands/perform_swap.ts
bouncer/commands/send.ts
bouncer/commands/send_btc.ts
bouncer/shared/broker_fee_collection.ts
bouncer/shared/gaslimit_ccm.ts
bouncer/shared/polkadot_runtime_update.ts
bouncer/shared/safe_mode.ts
bouncer/shared/send_evm.ts
bouncer/shared/utils.ts
bouncer/shared/utils/substrate.ts
bouncer/tests/swap_after_temp_disconnecting_chains.ts

After adding the lint, fixed all the places we have them. Please review the places I've said to explicitly ignore.

chore (bouncer): add no-floating-promises lint

---

bouncer/shared/boost.ts
bouncer/shared/gaslimit_ccm.ts
bouncer/shared/utils/substrate.ts

Part of: PRO-1411
Continuing on from #4954

refactor (bouncer): convert boost and gas_limit_ccm to use new observeEvent

---

.github/workflows/_25_package.yml

Closes: PRO-1443
Required in the case we want to release another 1.4.x version.

pick: fix: package should use old dylibs based on tags (#4966)

---

bouncer/tests/btc_utxo_consolidation.ts

Import missed as part of #4958 
Fixes nightly error here: https://github.com/chainflip-io/chainflip-backend/actions/runs/9543458242
Another reason to add eslint compiler checks to CI...

fix: btc_utxo_consolidation import

---

.github/workflows/_05_force_version_bump.yml

The action wasn't respecting the release in all cases.

fix: use correct network for version bump check

---

engine/src/state_chain_observer/sc_observer.rs

Closes: PRO-1256
See linked issue.

feat: try to submit previous btc broadcasts before our own

---

engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs

We now have a 1.4.3, so use that here instead of 1.4.2. Should fix the failure on main.

chore: bump previous release version to 1.4.3

---

foreign-chains/solana/sol-prim/src/lib.rs
foreign-chains/solana/sol-prim/src/pda.rs
foreign-chains/solana/sol-prim/src/tests/pda.rs
state-chain/chains/src/sol/api.rs
state-chain/chains/src/sol/instruction_builder.rs
state-chain/chains/src/sol/sol_tx_core.rs
state-chain/chains/src/sol/sol_tx_core/address_derivation.rs
state-chain/runtime/src/chainflip/address_derivation/sol.rs

refactor: Solana's derived ATA struct

---

.cargo/config.toml

As dicussed on discord, I updated dependencies (including curve25519) and updated cargo audit exception list.

chore: update cargo audit exceptions

---

Cargo.lock
engine-runner-bin/Cargo.toml
engine-runner-bin/build.rs
engine-runner-bin/tests/command_args.rs

Related to: PRO-1455
Just some basic regression tests to catch some potential issues with the arg parsing and how things are passed through the runner. Also provides a nice framework for potential future tests, by use of assert_cmd.

test: basic runner tests for help and version

---

Cargo.lock
foreign-chains/solana/sol-prim/Cargo.toml
foreign-chains/solana/sol-prim/src/consts.rs
state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/node/src/chain_spec/testnet.rs
utilities/Cargo.toml
utilities/src/without_std.rs

Factors out the bs58 array const fn so that it can be used for the chainspec consts.

chore: add bs58 const array fn to utils

---

.github/workflows/upgrade-test.yml

Ensure they're different to the bouncer run

chore: namespace upgrade-test uploads

---

Cargo.lock
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
localnet/init/config/Settings.toml

Closes: PRO-1455
A bug slipped through into main, fixed here: https://github.com/chainflip-io/chainflip-backend/pull/4982 - which is hard to pick up without a test like this one.

test: engine-runner command line args passing filters correctly

---

.github/workflows/_01_pre_check.yml
.github/workflows/_10_test.yml
.github/workflows/_11_coverage.yml
.github/workflows/_20_build.yml

There still seem to be some issues after #5007 - so removing cache entirely, as we should be correct first, and then optimise it later.

fix: remove rust cache

---

api/bin/chainflip-broker-api/src/main.rs
api/bin/chainflip-cli/src/main.rs
api/bin/chainflip-cli/src/settings.rs
api/bin/chainflip-lp-api/src/main.rs
api/lib/src/lib.rs
api/lib/src/lp.rs

Closes: PRO-1490
See Linear issue. 
If this passes bouncer tests etc. I'll extend the approach to the LP api where appropriate (and where the change is non-breaking to the api).

feat: consistent broker api address strings

---

Cargo.lock
state-chain/cf-integration-tests/Cargo.toml
state-chain/cf-integration-tests/src/lib.rs
state-chain/cf-integration-tests/src/network.rs
state-chain/cf-integration-tests/src/solana.rs
state-chain/cf-integration-tests/src/swapping.rs
state-chain/chains/src/sol/instruction_builder.rs
state-chain/chains/src/sol/sol_tx_core.rs
state-chain/chains/src/sol/sol_tx_core/address_derivation.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip/address_derivation.rs

Closes: PRO-1449
Added integration tests for Solana API call building.
Tested: BatchFetch, Transfer, Vault rotation and CCM

test: Solana API Integration tests

---

state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-lp/src/mock.rs
state-chain/pallets/cf-lp/src/tests.rs
state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/chainflip/boost_api.rs
state-chain/runtime/src/lib.rs

Closes: PRO-1337
Check boost balances of LP before allowing de-registration

fix: account deletion logic to keep boost funds into consideration

---

Cargo.lock

pick: chore: bump openssl (#5066)

---

state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/lib.rs
state-chain/traits/src/safe_mode.rs

Figured would split this out, as it's useful for #4999 .

refactor: impl_pallet_safe_mode for instantiable pallets

---

state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-lp/src/mock.rs
state-chain/pallets/cf-lp/src/tests.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-pools/src/tests.rs
state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/chainflip/boost_api.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Cherry-picks #5042 and #5059 onto release/1.5

Cherry-pick #5042 and #5059

---

bouncer/shared/initialize_new_chains.ts
state-chain/node/src/chain_spec.rs
state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/node/src/chain_spec/testnet.rs
state-chain/runtime/src/migrations/solana_integration.rs

Add two extra nonces since that's the bottleneck for Solana and we still have byte space in the rotation transaction.

chore: Solana increase number of nonces

---

.github/workflows/ci-development.yml
bouncer/shared/initialize_new_chains.ts
state-chain/node/src/chain_spec.rs
state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/node/src/chain_spec/testnet.rs
state-chain/runtime/src/migrations/solana_integration.rs

Revert to 8 nonces after seeing flakyness.

Chore/debug solana update programs 0.6

---

bouncer/shared/gaslimit_ccm.ts
bouncer/shared/initialize_new_chains.ts
state-chain/node/src/chain_spec.rs
state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/node/src/chain_spec/testnet.rs
state-chain/runtime/src/migrations/solana_integration.rs

feat: solana add two more nonces

---

utilities/src/with_std/task_scope.rs

This is a known issue, just want to record it for the record.

task scope soundness comment

---

bouncer/commands/set_minimum_deposit.ts
bouncer/full_bouncer.sh
bouncer/shared/set_minimum_deposit.ts
bouncer/tests/minimum_deposit.ts

Tests for minimum deposit

---

state-chain/pallets/cf-swapping/src/lib.rs

Closes: PRO-1526
Allow arbitrary accounts to be used as affiliate broker

feat: Allow arbitrary accounts to be used as affiliate broker

---

state-chain/runtime/src/lib.rs
state-chain/runtime/src/monitoring_apis.rs

chore: add Solana missing rpc return values

---

engine/src/witness/common/chunked_chain_source/chunked_by_vault/monitored_items.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs

Cherry-picks #5104 onto release/1.5

Pick onto 1.5/prewitness deposit without delay

---

engine/src/witness/common/chunked_chain_source/chunked_by_vault/monitored_items.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs

cherry picks the changes of #5104 onto main

prewitness deposits without delay

---

api/lib/src/lib.rs
bouncer/commands/go_bananas.ts
bouncer/package.json
bouncer/pnpm-lock.yaml
bouncer/shared/broker_fee_collection.ts
bouncer/shared/contract_swap.ts
bouncer/shared/fill_or_kill.ts
bouncer/shared/new_swap.ts
bouncer/shared/perform_swap.ts
bouncer/shared/setup_boost_pools.ts
bouncer/shared/swapping.ts
bouncer/shared/utils.ts
bouncer/tests/all_concurrent_tests.ts
bouncer/tests/fill_or_kill.ts
bouncer/tests/fund_redeem.ts

cherry-picks #5056 onto release/1.5

test: Bouncer Fill or Kill test (#5056)

---

state-chain/runtime/src/lib.rs
state-chain/runtime/src/monitoring_apis.rs

Include arbitrum block_height in the monitoring rpc

Fix: Add missing Arbitrum block_height

---

engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs

This fixes the lp-api panic described in PRO-1250. We cannot resolve this issue properly atm, as this is happening due to a bug in substrate. So we simply ignore the error, but this means extrinsic in-block detection will be slower when this happens. It seems to only happen occassionally (once every few 1000 extrinsics).

fix: Don't panic in SCC extrinsic detection (PRO-1250)

---

.github/workflows/_25_package.yml

Wasn't correctly running when tagged, which made the git ref "1.5.1" and not "release/1.5" as expected

fix: match correctly when workflow triggered by tags

---

.github/workflows/_25_package.yml

The branch name returned by the git command had whitespace which messes with the pattern matching below it.

fix: remove whitespace from branch name

---

bouncer/commands/new_swap.ts

Picks addition of FoK swap params to 1.5 branch for easier manual testing.

refactor: bouncer cmd for FoK swap (#5103)

---

state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs

Closes: PRO-1511
Simple test that uses a 0 refund duration on the refund params and makes sure the swap is refunded when it fails without retry.

test: FoK 0 refund duration

---

state-chain/chains/src/sol.rs
state-chain/chains/src/sol/transaction_builder.rs

Closes: PRO-1501
- Set maximum CU per CCM transfer to 600k instead of 1.4M to avoid huge transactions which are less likely to be included by the leaders.
- Set a minimum of 1 priority fee (1 microlamport / CU), even if the median reported fee is zero. The cost of that priority fee will be negligible while it increases significantly the chances of being included.

Feat: Solana gas tweaks

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip.rs
state-chain/traits/src/lib.rs

Adding a limit to the ccm transfers, same as for regular batches.

feat: add maybe_ccm_limit

---

Cargo.lock
state-chain/pallets/cf-elections/Cargo.toml
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-elections/src/mock.rs
state-chain/pallets/cf-elections/src/tests.rs

Simple success case to get us started with a testing example.

test: voting and consensus checking

---

state-chain/cfe-events/src/tests.rs

feat: sol event encoding tests

---

state-chain/pallets/cf-elections/src/benchmarking.rs
state-chain/pallets/cf-elections/src/electoral_system.rs
state-chain/pallets/cf-elections/src/electoral_systems/median.rs
state-chain/pallets/cf-elections/src/lib.rs

Part of: PRO-1563
Adds a simple vote benchmark for elections pallet. The test passes 🚀

chore: vote benchmark

---

bouncer/tests/delta_based_ingress.ts

Add some prints to clarify and fix wrong arg.

chore: add logs

---

engine/src/witness/sol.rs
engine/src/witness/sol/nonce_witnessing.rs
state-chain/cf-integration-tests/src/solana.rs
state-chain/pallets/cf-environment/src/lib.rs
state-chain/pallets/cf-environment/src/mock.rs
state-chain/pallets/cf-environment/src/tests.rs
state-chain/runtime/src/chainflip/solana_elections.rs
state-chain/runtime/src/lib.rs
state-chain/traits/src/lib.rs

Implements Durable nonce witnessing for Solana.

feat: solana nonce tracking

---

Cargo.lock
state-chain/pallets/cf-elections/Cargo.toml
state-chain/pallets/cf-elections/src/electoral_system.rs
state-chain/pallets/cf-elections/src/electoral_systems.rs
state-chain/pallets/cf-elections/src/electoral_systems/median.rs
state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-elections/src/mock.rs
state-chain/runtime/src/chainflip/solana_elections.rs

- Introduces mocks for the accessors and tests for unsafe median. These mocks are not quite complete, but for most tests they will be sufficient. The rest can be fleshed out as needed, the hard part is done.
- Tests the unsafe median electoral system
- Splits the unsafe median and monotonic median into their own files

test: unsafe median electoral system

---

state-chain/pallets/cf-elections/src/vote_storage/composite.rs

Makes the vote storage benchmark values generic.

feat: benchmark value for all vote storage composites

---

bouncer/shared/gaslimit_ccm.ts
engine/src/elections/voter_api.rs
engine/src/sol/rpc_client_api.rs
engine/src/witness/sol.rs
state-chain/cf-integration-tests/src/mock_runtime.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-broadcast/src/mock.rs
state-chain/pallets/cf-elections/src/electoral_system.rs
state-chain/pallets/cf-elections/src/electoral_systems.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/electoral_systems/egress_success.rs
state-chain/pallets/cf-elections/src/vote_storage/composite.rs
state-chain/pallets/cf-elections/src/vote_storage/individual/composite.rs
state-chain/runtime/src/chainflip/solana_elections.rs
state-chain/runtime/src/lib.rs
state-chain/traits/src/lib.rs

Implements Solana egress witnessing with election pallet

feat: solana egress witnessing

---

.github/workflows/_10_test.yml
.github/workflows/_11_coverage.yml

PLA-1374: limit cargo tests step time to 23 minutes

---

state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs

Closes: PRO-1584
- Added some DCA and FoK details to the scheduled swaps subscription.
- Added a unit test to cover it.
TODO: Update docs

Feat: Add DCA details to scheduled swaps subscription

---

bouncer/shared/initialize_new_chains.ts
bouncer/shared/utils.ts
bouncer/tests/all_concurrent_tests.ts

Add check at the end of the test that all nonces are available. It will especially be useful when we improve the way we witness the nonces to make sure nothing is broken.

chore: bouncer add check for solana nonces

---

state-chain/pallets/cf-elections/src/benchmarking.rs
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-elections/src/weights.rs

feature: Added benchmark for delete vote

---

state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs
state-chain/pallets/cf-swapping/src/tests/dca.rs
state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs

Closes: PRO-1433
- Enables FoK for CCM swaps.
- Enables FoK + DCA + CCM combo.

Feat: FoK for CCM swaps

---

.github/workflows/upgrade-test.yml
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

1.6 has been branched, so main can be bumped to 1.7 now.

chore: bump main to 1.7

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-ingress-egress-tracker/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
engine/config/testing/config/Settings.toml
engine/src/settings.rs
localnet/init/config/Settings.toml
state-chain/custom-rpc/src/lib.rs
state-chain/node/Cargo.toml
state-chain/pallets/cf-lp/src/mock.rs
state-chain/primitives/src/chains/assets.rs
state-chain/runtime/Cargo.toml
state-chain/traits/src/mocks/balance_api.rs
utilities/src/with_std/rpc.rs

[CHERRY PICKS for 1.6.2]

---

state-chain/runtime/src/chainflip/address_derivation/sol.rs

The derived address is not an ATA so renaming it accordingly.

chore: fix naming

---

.github/workflows/upgrade-test.yml
bouncer/commands/try_runtime_upgrade.ts
bouncer/shared/submit_runtime_upgrade.ts
bouncer/shared/try_runtime_upgrade.ts

Noticed some little improvements while investigating some flakiness in this area.
- Bump try-runtime CLI
- Utilise the now fan-out api client so we don't need to pass it around everywhere

chore (bouncer): improve try_runtime

---

CHANGELOG.md
engine-runner-bin/src/main.rs
engine/src/constants.rs
engine/src/settings.rs
engine/src/sol/retry_rpc.rs
engine/src/witness/sol.rs
engine/src/witness/sol/nonce_witnessing.rs
engine/src/witness/sol/sol_deposits.rs
localnet/init/config/Settings.toml

chore: remove unused sol WS settings

---

.cargo/config.toml
CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-ingress-egress-tracker/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/pallets/cf-elections/src/electoral_systems/change.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

[RC 1.6.4]

---

CHANGELOG.md
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/src/constants.rs
engine/src/settings.rs
engine/src/sol/retry_rpc.rs
engine/src/witness/sol/egress_witnessing.rs
engine/src/witness/sol/nonce_witnessing.rs
engine/src/witness/sol/sol_deposits.rs
localnet/init/config/Settings.toml

Closes: PRO-1616
Picking across from #5239

chore: remove unused sol WS settings (#5239)

---

localnet/init/scripts/start-solana.sh

Closes: PRO-1640
Bouncer would sometimes fail due to the aggressive pruning of the solana-test-validator

fix: triple ledger size local sol node

---

state-chain/chains/src/sol/sol_tx_core.rs

Add encoding test/example so if it's easy to encode a transaction from a storage Transaction item.
I've written the test checking against a localnet crafted transaction serialization, so it's valid values.
Happy to remove these tests after we've shipped 1.7.

chore: add Solana encoding test utils

---

.github/workflows/_61_upload_versioned_build_artifacts.yml
.github/workflows/release-perseverance.yml
.github/workflows/release-sisyphos.yml

feat: uze zip archives for artifacts on s3

---

state-chain/pallets/cf-ingress-egress/src/mock_eth.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/lib.rs
state-chain/traits/src/mocks.rs
state-chain/traits/src/mocks/fetches_transfers_limit_provider.rs

Feature: Added EVM transfer/fetch limit

---

state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs

feat: Added a swap_request_id to the CcmFailed event

---

state-chain/pallets/cf-account-roles/src/lib.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-chain-tracking/src/lib.rs
state-chain/pallets/cf-emissions/src/lib.rs
state-chain/pallets/cf-environment/src/lib.rs
state-chain/pallets/cf-environment/src/mock.rs
state-chain/pallets/cf-funding/src/lib.rs
state-chain/pallets/cf-governance/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/mock.rs
state-chain/pallets/cf-threshold-signature/src/tests.rs
state-chain/pallets/cf-tokenholder-governance/src/lib.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-vaults/src/lib.rs
state-chain/pallets/cf-witnesser/src/lib.rs
state-chain/pallets/cf-witnesser/src/mock/dummy.rs
state-chain/traits/src/lib.rs

chore: Replace DispatchResultwithPostInfo with DispatchResult

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs

feat: add boosted deposit lost event

---

.github/workflows/ci-development.yml
bouncer/commands/setup_lp_account.ts
bouncer/shared/create_and_delete_multiple_orders.ts
bouncer/shared/fund_flip.ts
bouncer/shared/limit_order.ts
bouncer/shared/range_order.ts
bouncer/shared/setup_lp_account.ts
bouncer/shared/setup_swaps.ts
bouncer/shared/upgrade_network.ts
bouncer/shared/utils.ts
bouncer/tests/all_concurrent_tests.ts
bouncer/tests/create_and_delete_multiple_orders.ts
state-chain/node/src/chain_spec/testnet.rs

Closes: PRO-1600
Added //LP_3 to the default lp accounts of localnet so that we can run other tests in parallel without interfering with existing tests

test: add new LP to execute new tests in parallel

---

api/bin/chainflip-cli/src/main.rs
api/bin/chainflip-cli/src/settings.rs

Closes: PRO-1544
It became apparent that requesting swaps from the CLI is no longer required. This PR removes this functionality.

chore: Remove SwapRequest code in cli.

---

engine/src/elections/voter_api.rs
state-chain/pallets/cf-elections/src/electoral_system.rs
state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
state-chain/pallets/cf-elections/src/electoral_systems/change.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/electoral_systems/egress_success.rs
state-chain/pallets/cf-elections/src/electoral_systems/mock.rs
state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/change.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
state-chain/pallets/cf-elections/src/lib.rs
state-chain/runtime/src/chainflip/solana_elections.rs

Would let #5201 be merged first to avoid a large singular commit to main.
In preparation for: PRO-1645
This will allow us to take actions on specific validators depending on which way they voted, like punishments rewards etc.

feat: provide ValidatorIds to ElectoralSystem::check_consensus

---

engine/src/witness/sol/sol_deposits.rs
state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/traits/src/lib.rs

Refactors the generics for delte based ingress to make testing a little easier.

feat: refactor delta based ingress generics

---

state-chain/pallets/cf-asset-balances/src/lib.rs
state-chain/traits/src/lib.rs
state-chain/traits/src/mocks/asset_withholding.rs
state-chain/traits/src/mocks/liability_tracker.rs

Closes: PRO-1515
We needed these for an upgrade but now they're not required.

chore: remove unused fns

---

bouncer/commands/check_bin_and_runtime_versions.ts

Closes: PRO-1657
Turns out it was just the endpoint was wrong.

fix: force version bump endpoint

---

CHANGELOG.md
state-chain/chains/src/btc.rs
state-chain/pallets/cf-environment/src/lib.rs

fix: filter out stale bitcoin utxos

---

state-chain/chains/src/sol.rs

Adding the minimum priority fee to the ingress and egress fee calculations.

chore: add sol min_prio_fee to ingress and egress estimation

---

api/bin/chainflip-lp-api/src/main.rs

This will need to be added to main too.

fix: ignore dust underflow

---

engine/src/witness/sol/nonce_witnessing.rs
engine/src/witness/sol/sol_deposits.rs

Add address requested in the logging to report to rpc providers.

chore: add address to solana logging

---

Cargo.lock
engine/Cargo.toml
engine/src/witness/sol.rs
engine/src/witness/sol/program_swaps_witnessing.rs
state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/devnet.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs

Closes: PRO-1700
This is the skeleton code for the engine logic to witness program swaps. It needs to be integrated with the elections pallet.

Feat: engine logic to witness solana program swaps

---

Cargo.toml
state-chain/test-utilities/Cargo.toml

Fixes some build errors related to the test externalities.

fix: features for test-externalities

---

engine/src/witness/sol.rs

Just noticed this was missing for sol. We have it for all the other chains, inside the chain_tracking.rs adapter.
```rust
CHAIN_TRACKING.set(&[Inner::Chain::NAME], Into::<u64>::into(header.index));
```

feat: add sol chain tracking metric

---

bouncer/shared/vault_swap.ts
bouncer/tests/all_concurrent_tests.ts
bouncer/tests/all_swaps.ts

Add bouncer testing for Solana Vault swap event accounts closure.

Test: bouncer solana event closure

---

.github/workflows/ci-cherry-pick.yml
state-chain/runtime/src/lib.rs
state-chain/runtime/src/migrations.rs

[rebase and merge] - solana migration idempotency, bump github actions versions

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/monitoring.rs
state-chain/custom-rpc/src/snapshots/custom_rpc__test__swap_output_serialization.snap
state-chain/node/Cargo.toml
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs
state-chain/runtime/src/monitoring_apis.rs
state-chain/runtime/src/runtime_apis.rs

[rebase merge] - 1.7.1

---

bouncer/package.json
bouncer/pnpm-lock.yaml
engine/src/witness/common/cf_parameters.rs
engine/src/witness/evm/vault.rs

Closes: PRO-1767
Updated SDK with changes in: https://github.com/chainflip-io/chainflip-sdk-monorepo/pull/1037/commits/26c1406a1fa21e1bffd468ff816498ab5867dad3

feat: add cf-parameters versioning

---

state-chain/pallets/cf-elections/src/lib.rs

chore: remove unused `InvalidVote` error

---

state-chain/pallets/cf-swapping/src/lib.rs

Will wait for base PR to be merged.
Just noticed this could be simplified when reviewing the base branch's PR.

refactor: simplify beneficiary collection

---

state-chain/pallets/cf-elections/src/lib.rs

Closes: PRO-1814
Like in the witness pallet, these should be operational too.

chore: make elections pallet validator extrinsics operational

---

engine/src/witness/sol/program_swaps_witnessing.rs
state-chain/pallets/cf-elections/src/electoral_systems/solana_vault_swap_accounts.rs

we want to close vault swap accounts even for swaps that are invalid and not able to be processed.

feat: close accounts even for invalid swaps

---

state-chain/pallets/cf-swapping/src/lib.rs

Closes: PRO-1823 
Just a small one - noticed this when reviewing another PR.

fix: remove affiilate mappings

---

engine/src/witness/sol.rs

(cherry picked from commit b8c1825f3e58d3e84f5cf724ee82e29f041a78d6)

chore: reduce data needed for sol get block (#5428)

---

state-chain/runtime/src/lib.rs

Release branch fix for: PRO-1850
See: https://github.com/chainflip-io/chainflip-backend/pull/5430

fix: no intermediary swap amount for single-legs

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

Prepares the branch for tagging 1.7.2

chore: verision bumps, changelog for 1.7.2

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-broker-api/src/main.rs
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
api/lib/src/lib.rs
bouncer/tests/broker_level_screening.ts
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/custom-rpc/src/lib.rs
state-chain/node/Cargo.toml
state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/migrations.rs
state-chain/pallets/cf-ingress-egress/src/migrations/rename_tx_reports.rs
state-chain/pallets/cf-ingress-egress/src/tests/screening.rs
state-chain/pallets/cf-ingress-egress/src/weights.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

chore: rename broker screening stuff

---

.github/CODEOWNERS

Add myself as codeowner for a bunch of files, mainly related to EVM and Solana.
Also fixed a legacy path that was incorrect.

chore: add codeowner Albert

---

CHANGELOG.md
api/bin/chainflip-broker-api/src/main.rs
api/lib/src/lib.rs
bouncer/tests/broker_level_screening.ts
localnet/docker-compose.yml
state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests/screening.rs
state-chain/pallets/cf-ingress-egress/src/weights.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

This is a cherry-pick from release/1.7 (#5449 ) (+ some conflict resolution).

chore: rename broker screening

---

state-chain/chains/src/sol/sol_tx_core/program_instructions.rs

This is necessary for the broker api Solana Vault swaps encoding. I am adding it now for @syan095 to work on it.

chore: add swap endpoint interface for sol vault swaps

---

engine/src/retrier.rs

I'm not entirely convinced this will fix the test flakiness, but it might, and it's the more correct way to do it anyway (based on the tokio docs)

test: start paused retrier test

---

.github/workflows/ci-development.yml
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/pallets/cf-ingress-egress/src/tests/screening.rs

Chore: extend DepositFailed and merge with DepositWitnessRejected

---

api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc.rs
engine/src/btc/retry_rpc.rs
engine/src/elections.rs
engine/src/elections/voter_api.rs
engine/src/state_chain_observer/client/electoral_api.rs
engine/src/witness/btc.rs
engine/src/witness/btc/deposits.rs
engine/src/witness/btc/source.rs
engine/src/witness/btc_e.rs
engine/src/witness/sol.rs
engine/src/witness/start.rs
state-chain/custom-rpc/src/lib.rs
state-chain/node/src/chain_spec.rs
state-chain/pallets/cf-elections/src/electoral_systems.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-elections/src/vote_storage/composite.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

WIP: feat: block height tracking electoral system

---

state-chain/custom-rpc/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Closes: PRO-1892
Implemented on top of the ccm gas improvement since it's adding a new parameter to the already changed functions. No need to to the same versioning update in a separate PR.

Feat: add exclude fee quotes for Vault swaps

---

engine/src/witness/btc_e.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/primitives.rs

The BHW seems to work on localnet, it also successfully detects reorgs.

WIP: Fix block height witnesser bugs

---

.github/workflows/ci-development.yml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
state-chain/chains/src/arb.rs
state-chain/chains/src/evm/api/common.rs
state-chain/chains/src/evm/api/execute_x_swap_and_call.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-chain-tracking/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/migrations.rs
state-chain/pallets/cf-ingress-egress/src/migrations/deposit_channel_details_migration.rs
state-chain/pallets/cf-ingress-egress/src/migrations/scheduled_egress_ccm_migration.rs
state-chain/pallets/cf-swapping/src/migrations/swap_request_migration.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/migrations.rs
state-chain/runtime/src/migrations/api_calls_gas_migration.rs
state-chain/runtime/src/migrations/arbitrum_chain_tracking_migration.rs

Add migration for EthereumApi and ArbitrumApi
Add migration for ScheduledEgressCcmMigration

Chore: add migrations for "improve ccm gas calculations"

---

state-chain/amm/src/common.rs

Just a follow up on https://github.com/chainflip-io/chainflip-backend/pull/5510 as per @kylezs review.

chore: update comments in fixed point math

---

bouncer/shared/evm_vault_swap.ts
bouncer/shared/perform_swap.ts
bouncer/shared/utils.ts
bouncer/tests/all_swaps.ts
bouncer/tests/btc_vault_swap.ts

Re-add BTC vault swap test. The affiliate fee test should be done separately.

chore: add btc vault swap test

---

bouncer/package.json
bouncer/shared/perform_swap.ts
bouncer/shared/setup_swaps.ts
bouncer/shared/swapping.ts
bouncer/tests/all_swaps.ts
bouncer/tests/request_swap_deposit_address_with_affiliates.ts
state-chain/chains/src/ccm_checker.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip/decompose_recompose.rs
state-chain/runtime/src/chainflip/vault_swaps.rs
state-chain/runtime/src/lib.rs

Closes: PRO-1926 
Moved the CCM validity checks so that all ccms with destinations to Solana chains are checked.

fix: ccm validity check for vault swaps

---

bouncer/shared/sol_vault_swap.ts
state-chain/node/src/chain_spec/berghain.rs
state-chain/pallets/cf-environment/src/migrations/sol_api_environment.rs
state-chain/runtime/src/migrations/solana_vault_swaps_migration.rs

Closes: PRO-1779
- Update with the new addresses for the Swap Endpoint.

chore: update swap endpoint addresses

---

state-chain/pallets/cf-environment/src/lib.rs

fix: log UtxoSelectionError as warning instead of error

---

state-chain/cf-integration-tests/src/solana.rs
state-chain/chains/src/address.rs
state-chain/chains/src/sol.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs

Disables Solana address recycling pending implmentation of persistent channels / multiplexed deposits channels.

fix: revert solana recycling

---

.github/workflows/ci-development.yml
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/migrations.rs
state-chain/runtime/src/migrations/solana_remove_unused_channels_state.rs

chore: remove unused solana channels

---

api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
engine/src/witness/btc/vault_swaps.rs
engine/src/witness/evm/vault.rs
state-chain/cf-integration-tests/src/solana.rs
state-chain/cf-integration-tests/src/swapping.rs
state-chain/chains/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs
state-chain/pallets/cf-swapping/src/tests/ccm.rs
state-chain/pallets/cf-swapping/src/tests/config.rs
state-chain/pallets/cf-swapping/src/tests/dca.rs
state-chain/pallets/cf-swapping/src/tests/fees.rs
state-chain/runtime/src/chainflip/solana_elections.rs
state-chain/traits/src/mocks/swap_request_api.rs
state-chain/traits/src/swapping.rs

Closes: PRO-1951
Added broker id to the `SwapOrigin` & `DepositOrigin` enums.

chore: added broker_id to swap origin

---

state-chain/pallets/cf-ingress-egress/src/lib.rs

Was missed when we added these variants. We do this manually to workaround a bug in polkadot-js :/

fix: add ingress-egress pallet config metadata

---

engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs

This is in response to some keygen issues noticed on our engines recently.

fix: retry submission on StateDiscarded error

---

state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs

Only submit liveness vote when you haven't voted yet.

fix: liveness when necessary

---

engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs

Bump to the latest 1.7 version.

chore: bump old engine version

---

engine/src/sol/retry_rpc.rs
engine/src/sol/rpc.rs
engine/src/witness/sol/egress_witnessing.rs

refactor: always search history for signature statuses

---

state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/pallets/cf-environment/src/migrations/sol_api_environment.rs
state-chain/runtime/src/migrations/solana_vault_swaps_migration.rs

Closes: PRO-1952
Deploy the latest Swap Endpoint account that has the Native Vault functionality to fetch Vault swaps.

chore: update with deployed swap endpoint

---

.github/workflows/ci-development.yml
Cargo.lock
Cargo.toml
engine/src/elections/voter_api.rs
engine/src/witness/sol.rs
state-chain/cf-integration-tests/src/mock_runtime.rs
state-chain/cf-integration-tests/src/solana.rs
state-chain/node/src/chain_spec.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
state-chain/pallets/cf-elections/src/lib.rs
state-chain/pallets/cf-elections/src/vote_storage/composite.rs
state-chain/pallets/cf-elections/src/vote_storage/individual/composite.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/chainflip/solana_elections.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/migrations.rs
state-chain/runtime/src/migrations/remove_fee_tracking_migration.rs
state-chain/runtime/src/migrations/solana_remove_unused_channels_state.rs

Closes: PRO-1960
It's no longer used so we can remove it.

chore: remove sol fee witnessing

---

bouncer/shared/sol_vault_swap.ts
state-chain/runtime/src/chainflip/vault_swaps.rs

chore: derive from_token_account if not passed

---

state-chain/pallets/cf-ingress-egress/src/tests/screening.rs

test: added check of swap requests and egress pipelines

---

state-chain/chains/src/address.rs
state-chain/chains/src/ccm_checker.rs
state-chain/chains/src/sol/api.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/runtime/src/lib.rs

Add cf_receiver and destination_address to the Solana CCM Checker as one last optimization.

chore: optimize Solana CCM Checker

---

bouncer/tests/lp_api_test.ts
state-chain/chains/src/sol/sol_tx_core/transaction.rs
state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-lp/src/tests.rs

fix: ensure lp account is registered for transfers

---

engine/src/elections.rs

Excessive logging was causing confusion for operators.

chore: reduce voter logging in engine

---

localnet/init/scripts/start-solana.sh

Closes: PRO-1717
Increasing ledger size to 100k. Default is 10k, which is very small, and the previous 30k is also quite small.

chore: increase solana ledger size

---

api/bin/chainflip-broker-api/src/main.rs
bouncer/shared/btc_vault_swap.ts
bouncer/shared/evm_vault_swap.ts
bouncer/shared/sol_vault_swap.ts
state-chain/custom-rpc/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

fix: make naming more consistent for request_swap_parameter_encoding

---

engine/src/elections/voter_api.rs
engine/src/witness/btc_e.rs
state-chain/node/src/chain_spec/common.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs
state-chain/pallets/cf-elections/src/vote_storage/composite.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs
state-chain/runtime/src/chainflip/offences.rs
state-chain/runtime/src/chainflip/solana_elections.rs
state-chain/runtime/src/lib.rs

Closes: PRO-1865
Instantiation of the Liveness ES for bitcoin

feat: BitcoinLiveness election

---

state-chain/cf-session-benchmarking/src/lib.rs

Closes: PRO-1610
The final benchmarking that wasn't v2.

chore: update session pallet benchmarks to v2

---

state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs

Closes: PRO-2030
Picks changes from #5626 on `release/1.8`.

feat: refresh solana elections instead of recreate

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

Fixes small edge case with channel expiry and fetching EVM and solana deposits.

fix: potential stuck fetches

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs

Picks: #5631 from 1.8 to main.

fix: don't block fetches

---

Cargo.lock
Cargo.toml
api/bin/chainflip-elections-tracker/Cargo.toml
engine/Cargo.toml
engine/multisig/Cargo.toml
foreign-chains/solana/sol-prim/Cargo.toml
state-chain/amm/Cargo.toml
state-chain/cf-integration-tests/Cargo.toml
state-chain/cf-session-benchmarking/Cargo.toml
state-chain/chains/Cargo.toml
state-chain/pallets/cf-cfe-interface/Cargo.toml
state-chain/pallets/cf-lp/Cargo.toml
state-chain/pallets/cf-swapping/Cargo.toml
state-chain/pallets/cf-validator/Cargo.toml
state-chain/primitives/Cargo.toml
utilities/Cargo.toml

Used `cargo-udeps` to do a check of our deps.

chore: remove unused deps

---

bouncer/commands/set_boost_network_fee_percent.ts

A useful command for setting the boost network fee.

chore(bouncer): add command for setting boost network fee

---

engine/src/elections/voter_api.rs
engine/src/witness/btc_e.rs
state-chain/pallets/cf-chain-tracking/src/lib.rs
state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
state-chain/pallets/cf-elections/src/vote_storage/composite.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs
state-chain/runtime/src/chainflip/solana_elections.rs

Closes: PRO-1322
Added the fee electoral system for btc

feat: fee tracker ES for BTC

---

state-chain/runtime/src/chainflip/bitcoin_elections.rs

fix: improve error message

---

bouncer/tests/broker_level_screening.ts

feat: eth broker-level screening: Test rejection of LP deposits.

---

bouncer/shared/upgrade_network.ts

Since we are upgrading from a version of localnet without deposit-monitor, we have to start the deposit-monitor on upgrade.
Copied over from `release/1.8`.

fix: start deposit-monitor on runtime upgrade

---

state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Adds arb events and deposit channels.

chore: pass through arb events and deposit channels to broker api.

---

api/bin/chainflip-ingress-egress-tracker/src/settings.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing/arb.rs
engine/src/witness/arb.rs

Closes: PRO-2094
Adds Arbitrum ingress egress tracker.

feat: arbitrum ingress-egress tracking

---

bouncer/commands/on_chain_swap.ts
bouncer/shared/deposit_liquidity.ts
bouncer/shared/send_btc.ts

SImple command that I used to test my other PR. Thought I might as well push it.
Also added some log messages that might help with finding the flakiness in the bouncer setup.

chore: on-chain swap command in bouncer

---

api/bin/chainflip-ingress-egress-tracker/src/settings.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
api/bin/chainflip-ingress-egress-tracker/src/witnessing/arb.rs
engine/src/witness/arb.rs
state-chain/pallets/cf-ingress-egress/src/migrations/update_rejection_params.rs

Closes: PRO-2094
Picks #5702 to release/1.8

feat: arb ingress egress tracker (picked from: #5702)

---

state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/migrations/update_rejection_params.rs
state-chain/pallets/cf-ingress-egress/src/tests.rs

Another fix for BLS for boosted txs.
Same as #5703 but some differences due to structural differences between release branches.

fix: ensure boosted txs can be rejected

---

localnet/docker-compose.yml

if variable is not set, use given default value.
Closes: PRO-2099

feat: use environment variable to choose deposit-monitor image tag.

---

.cargo/config.toml

RUSTSEC-2024-0436
RUSTSEC-2025-0010

chore: cargo audit

---

.cargo/config.toml
Cargo.lock

fix: cargo audit issue RUSTSEC-2025-0014

---

.github/workflows/_21_build_m2.yml

explicitly add wasm target for m2 rustup

add wasm build target for m2

---

api/bin/chainflip-lp-api/src/main.rs
api/lib/src/lp.rs
bouncer/shared/utils.ts
bouncer/tests/lp_api_test.ts

Closes: PRO-2032
- Added the on chain swap rpc to the LP API.
- Added it to the lp api bouncer test.

feat: on chain swap in lp api

---

state-chain/pallets/cf-trading-strategy/src/benchmarking.rs
state-chain/pallets/cf-trading-strategy/src/lib.rs
state-chain/pallets/cf-trading-strategy/src/tests.rs
state-chain/pallets/cf-trading-strategy/src/weights.rs

A simple renaming of the extrinsic, as discussed on discord.

chore: rename deploy_strategy extrinsic

---

state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs

Closes: PRO-2102
Changed the return type of ExecuteHook to ()

feat: Bitcoin ES: change ExecuteHook to return ()

---

localnet/init/scripts/start-deposit-monitor.sh

ci: PLA-1835: limit start-deposit-monitor.sh retries in CI

---

engine/src/witness.rs
engine/src/witness/btc.rs
engine/src/witness/btc_e.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine_es.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs

Closes: PRO-2080
Moved SafetyMargin into the electoral system Unsynchronised Settings

feat: Move SafetyMargin into ES settings

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/mock.rs
state-chain/pallets/cf-swapping/src/tests.rs
state-chain/primitives/src/lib.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs
state-chain/traits/Cargo.toml
state-chain/traits/src/lib.rs
state-chain/traits/src/mocks.rs
state-chain/traits/src/mocks/pool_price_api.rs

Cherry picks: #5782 to release.

fix: correctly estimate input amount in scheduled swaps (#5782)

---

state-chain/custom-rpc/src/backend.rs
state-chain/custom-rpc/src/order_fills.rs

Cherry pick of 7d9fff7dc07b7daf0ab865ac067de8703f429477

fix: order_fills_for_block fix to show error only when result is none

---

bouncer/tests/fast_bouncer.test.ts

fix: changed bouncer test name from VaultSwapFeeCollection to VaultSwaps

---

state-chain/pallets/cf-elections/src/electoral_systems/exact_value.rs
state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/egress_success.rs
state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/chainflip/solana_elections.rs

feat: move state map access into pallet

---

localnet/common.sh
localnet/init/scripts/start-node.sh
state-chain/custom-rpc/Cargo.toml
state-chain/custom-rpc/src/backend.rs

* Minor fix that serializes Subscription ID and stores it as a String in the subscription gc
* Make sure to use the same chain head client for both the subscription and its GC.
* Removed debug messages to not pollute log file

fix: lru cache fixes in the subscription gc

---

bouncer/tests/fast_bouncer.test.ts

This reverts commit 9f1c1b7f3ddd48c8d81a965022088a4b48243ca6.

Revert "chore: increase test timeout"

---

state-chain/runtime/src/lib.rs

Sweeping (in the rpc layer) means we include any unswept amounts in open orders.

fix: sweep in lp total balances and strategies rpc

---

api/bin/chainflip-broker-api/src/main.rs
api/cf-rpc-apis/clippy.toml
api/cf-rpc-apis/src/broker.rs
api/lib/src/lib.rs
state-chain/custom-rpc/src/broker.rs

feat: Add option to wait finality when opening deposit channel

---

state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/monitoring.rs
state-chain/custom-rpc/src/snapshots/custom_rpc__test__validator_serialization.snap
state-chain/pallets/cf-funding/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Closes: PRO-2048
Added an extra function that returns the maximum redeemable balance.
`cf_account_info` and `cf_account_info_v2` rpc calls returns the redeemable balance

feat: Add redeemable balance to rpc call

---

engine/src/witness/btc.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/optimistic_block_cache.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs

feat: Feature/pro 2246

---

state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/lib.rs

feat: Save all processed events

---

state-chain/pallets/cf-account-roles/src/lib.rs
state-chain/pallets/cf-broadcast/src/lib.rs
state-chain/pallets/cf-chain-tracking/src/lib.rs
state-chain/pallets/cf-emissions/src/lib.rs
state-chain/pallets/cf-environment/src/lib.rs
state-chain/pallets/cf-funding/src/lib.rs
state-chain/pallets/cf-governance/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-lp/src/lib.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/pallets/cf-reputation/src/lib.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-threshold-signature/src/lib.rs
state-chain/pallets/cf-tokenholder-governance/src/lib.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-vaults/src/lib.rs

Closes: PRO-2263
These are usually out of date and generally not very helpful.

chore: remove events and errors sections from extrinsic doc comments

---

engine/src/witness/btc.rs

fix: correct conversion of btc hashes in the engine (bitcoin elections)

---

state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests.rs
state-chain/pallets/cf-swapping/src/tests/dca.rs
state-chain/pallets/cf-swapping/src/tests/fees.rs
state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs

Closes: PRO-2265
- Added the refund fee amount to both refund events: `RefundEgressScheduled` & `RefundedOnChain`.
- Cleaned up the refund code a bit by adding an `EgressType` enum.
- Expanded existing tests to check for the refund amount in the events.

feat: refund fee in refund events

---

state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/primitives.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/consensus.rs
state-chain/pallets/cf-elections/src/electoral_systems/state_machine/consensus.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs

Closes: PRO-2062
Added tests for the consensus mechanisms

feat: add tests for consensus mechanism

---

engine/src/witness/btc.rs
state-chain/runtime/src/lib.rs

improved some logic and deduplicated part of the code

feat: improve engine logic

---

CHANGELOG.md
Cargo.lock
api/bin/chainflip-broker-api/Cargo.toml
api/bin/chainflip-cli/Cargo.toml
api/bin/chainflip-lp-api/Cargo.toml
api/lib/Cargo.toml
engine-dylib/Cargo.toml
engine-proc-macros/Cargo.toml
engine-runner-bin/Cargo.toml
engine-runner-bin/src/main.rs
engine-upgrade-utils/src/lib.rs
engine/Cargo.toml
state-chain/node/Cargo.toml
state-chain/pallets/cf-trading-strategy/src/lib.rs
state-chain/pallets/cf-trading-strategy/src/tests.rs
state-chain/runtime/Cargo.toml
state-chain/runtime/src/lib.rs

Fixes an issue with parameter validation for trading strategies.

fix: better strategy funding validation

---

state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_height_tracking.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
state-chain/runtime/src/chainflip/bitcoin_elections.rs

feat: Only store reorged events in the block processor (again)

---

CHANGELOG.md
state-chain/chains/src/hub.rs
state-chain/runtime/src/lib.rs

Cherrypicks the fixes for 1.9.3 onto main.

chore: cherry-pick assethub fee fix

---

.github/workflows/upgrade-test.yml

Fixes a mistake that stopped the ci from uploading logs when the bouncer fails 🤦‍♂️

chore: ci to upload logs on failure

---

state-chain/custom-rpc/src/broker.rs
state-chain/custom-rpc/src/pool_client.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs

Just some things I noticed when reviewing #5896

chore: finality bug review changes

---

state-chain/cf-integration-tests/src/trading_strategy.rs
state-chain/pallets/cf-pools/src/lib.rs
state-chain/traits/src/liquidity.rs

fix: can close orders after sweeping (#5901)

---

state-chain/custom-rpc/src/snapshots/custom_rpc__tests__vault_swap_details_serialization-2.snap
state-chain/custom-rpc/src/snapshots/custom_rpc__tests__vault_swap_details_serialization-3.snap
state-chain/custom-rpc/src/tests.rs
state-chain/runtime/src/chainflip/vault_swaps.rs
state-chain/runtime/src/runtime_apis.rs

Cherry pick of a commit from 1.8 that was never merged to main.

fix: add token approval address for EVM vault swaps (#5647)

---

state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/consensus.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/primitives.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/block_height_witnesser.rs
state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs

feat: remove unwrap from NonemptyContinuousHeaders

---

state-chain/cf-integration-tests/src/swapping.rs
state-chain/chains/src/any.rs
state-chain/chains/src/arb.rs
state-chain/chains/src/btc.rs
state-chain/chains/src/dot.rs
state-chain/chains/src/eth.rs
state-chain/chains/src/hub.rs
state-chain/chains/src/lib.rs
state-chain/chains/src/mocks.rs
state-chain/chains/src/none.rs
state-chain/chains/src/sol.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
state-chain/pallets/cf-swapping/src/lib.rs
state-chain/pallets/cf-swapping/src/tests/fees.rs
state-chain/primitives/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/traits/src/lib.rs
state-chain/traits/src/mocks/asset_converter.rs

fix: estimate ingress fee for eth usdt and usdc if pool empty

---

bouncer/tests/evm_deposits.ts

Closes: PRO-2257
Test rpc to encode_cf_parameters. Documented in https://github.com/chainflip-io/chainflip-docs/pull/577

chore: add bouncer test for cf_params encoding

---

api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc.rs
engine/src/elections.rs
state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/helpers.rs
state-chain/pallets/cf-elections/src/electoral_systems/state_machine/test_utils.rs

Removes commented code, removes one `expect()` in the ingress egress tracker, and also temporary halving of BLOCK_TIME.

chore: last btc elections fixes

---

state-chain/custom-rpc/src/backend.rs
state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/snapshots/custom_rpc__tests__auction_state_serialization.snap
state-chain/custom-rpc/src/tests.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

Closes: PRO-2305 (see final comment)
Exposes the min bid via RPC call.

feat: add min bid to RPCs

---

state-chain/node/src/chain_spec/berghain.rs
state-chain/node/src/chain_spec/perseverance.rs
state-chain/node/src/chain_spec/sisyphos.rs
state-chain/node/src/chain_spec/testnet.rs
state-chain/runtime/src/migrations/generic_elections.rs

chore: insert addresses

---

engine/src/witness/btc/deposits.rs
engine/src/witness/eth/state_chain_gateway.rs
engine/src/witness/evm/key_manager.rs
engine/src/witness/evm/vault.rs

 chore: process all events in a block in parallel

---

Cargo.lock
state-chain/custom-rpc/Cargo.toml
state-chain/custom-rpc/src/lib.rs
state-chain/pallets/cf-elections/src/electoral_systems/oracle_price/chainlink.rs
state-chain/pallets/cf-elections/src/electoral_systems/oracle_price/state_machine.rs
state-chain/runtime/src/chainflip/generic_elections.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

feat: Rpc for oracle prices

---

state-chain/runtime/src/chainflip.rs
state-chain/runtime/src/chainflip/generic_elections.rs

fix: use `any::Asset` instead of `ChainlinkAssetpair` in internal price API

---

engine/src/elections/voter_api.rs
engine/src/evm/cached_rpc.rs
engine/src/evm/retry_rpc.rs
engine/src/evm/rpc.rs
engine/src/lib.rs
engine/src/state_chain_observer/client/electoral_api.rs
engine/src/witness.rs
engine/src/witness/eth.rs
engine/src/witness/eth2.rs
engine/src/witness/evm.rs
engine/src/witness/evm/erc20_deposits.rs
engine/src/witness/evm/evm_deposits.rs
engine/src/witness/start.rs
state-chain/pallets/cf-ingress-egress/src/lib.rs
state-chain/runtime/src/chainflip/ethereum_block_processor.rs
state-chain/runtime/src/chainflip/ethereum_elections.rs

feat: impl voter api

---

bouncer/tests/special_btc_swaps.ts

The test checks that we witnessed 4 different UTXOs by checking that their values lie within a certain range of the input amount. To make this test less flaky, this PR includes:
- increase accepted amount range.
- increase smallest amount.
- add more logging for the eventual case that this test fails again.

fix: make SpecialBitcoinSwaps test less flaky:

---

.github/workflows/ci-development.yml
bouncer/shared/utils/substrate.ts
bouncer/tests/delegate_flip.ts
bouncer/tests/fast_bouncer.test.ts
engine/src/witness/eth/sc_utils.rs
state-chain/chains/src/evm/api.rs
state-chain/chains/src/evm/api/sc_utils.rs
state-chain/chains/src/evm/api/sc_utils/deposit_flip_to_sc_gateway_and_call.rs
state-chain/chains/src/evm/api/sc_utils/sc_call.rs
state-chain/custom-rpc/src/lib.rs
state-chain/custom-rpc/src/tests.rs
state-chain/pallets/cf-funding/src/lib.rs
state-chain/pallets/cf-validator/src/benchmarking.rs
state-chain/pallets/cf-validator/src/delegation.rs
state-chain/pallets/cf-validator/src/tests.rs
state-chain/runtime/src/chainflip/ethereum_sc_calls.rs
state-chain/runtime/src/chainflip/vault_swaps.rs
state-chain/runtime/src/lib.rs
state-chain/runtime/src/runtime_apis.rs

feat: rpc for building ethereum tx for sc calls

---

state-chain/cf-integration-tests/src/authorities.rs
state-chain/pallets/cf-flip/src/lib.rs
state-chain/traits/src/lib.rs

Closes: PRO-2463
FYI @acdibble

feat: emit event on FLIP mints

---

state-chain/cf-integration-tests/src/funding.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-validator/src/migrations/remove_backups.rs
state-chain/pallets/cf-validator/src/tests.rs
state-chain/runtime/src/lib.rs

feat: absolute min val stake and min auction bid

---

bouncer/shared/setup_account.ts
state-chain/cf-integration-tests/src/delegation.rs
state-chain/pallets/cf-flip/src/lib.rs
state-chain/pallets/cf-validator/src/benchmarking.rs
state-chain/pallets/cf-validator/src/delegation.rs
state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-validator/src/tests.rs

feat: replace delegation capacity factor with bond and limit operator settings updates

---

state-chain/pallets/cf-validator/src/lib.rs
state-chain/pallets/cf-validator/src/tests.rs
state-chain/runtime/src/lib.rs

feat: update auction state rpc
