chainflip-io/chainflip-backend

- bouncer/commands/try_runtime_upgrade.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/utils/compile_binaries.ts
Part one of: PRO-956
- Will include in the upgrade tool next, this is useful as is, so thought I'd get this out now. Small PRs etc.
Provides an easy way to test migrations more thoroughly. This currently just uses `live` which might be quite slow for non-localnets, but we can optimise this later to use snapshots. Being able to start a localnet run bouncer and then test the migration for all the blocks super simply is already quite powerful.
Will also look at including something in CI.
> feat: try-runtime loop

- bouncer/shared/try_runtime_upgrade.ts
Closes: PRO-991
When testing try-runtime we don't really care about the spec-version - and this is slightly better than auto-bumping the spec version, since the bump would require a re-compile.
> fix: disable spec version check for try-runtime

- state-chain/amm/src/common.rs
The recent addition of set_fees and one of the new lp rpcs added a bug:
Basically the conversion from sqrt_price to tick, would assert for the max sqrt_price, but the conversion from tick to sqrt_price could output the max sqrt_price, so you couldn't freely/safely convert between them (i.e. tick_at_sqrt_price(sqrt_price_at_tick(TICK)) may panic even if the TICK was considered valid, which is dumb). In the original AMM code this was fine (and matched Uniswap's asserts/restrictiveness), but the assert is unnecessarily restrictive, as the function behaves correctly even for the max sqrt_price value (i.e. it outputs the max tick). So to make the function safer to use I've made the assert less restrictive. The only behavioural effect is that range order pools can be initialised at the max …
> fix: set_fees

- state-chain/pallets/cf-validator/src/lib.rs
Removes update_bond migration from #4276 so it's not applied twice.
> chore: remove update_bond migration

- bouncer/commands/upgrade_network.ts
- bouncer/shared/submit_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
Part of: PRO-973
Allows us to do an upgrade from prebuilt binaries, rather than having to use the git method (which involves locally building). On CI, and in particular on a nighly upgrade job, we already have the binaries on main built, so we can use them. Can use this locally too of course.
> feat: upgrade_network command using prebuilt binaries

- .cargo/config.toml
- bouncer/commands/try_runtime_upgrade.ts
- bouncer/shared/simple_runtime_upgrade.ts
- bouncer/shared/submit_runtime_upgrade.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
Review #4280 first - this targets that.
Would try it out locally.
Closes: PRO-956
Conveniently runs the `try-runtime` command as part of the network upgrade on the last 50 blocks from the time the script starts.
Next step - putting this in the CI 🚀
> feat: try runtime in upgrade tool

- state-chain/pallets/cf-funding/src/lib.rs
This is a very small fix but reduces the chance of future regressions. It also makes it possible to find a restricted address using polkaJS (otherwise they all default to `()` so it looks like the same whether the address is present or not).
> fix: make restricted address storage optional

- engine/src/witness/btc/btc_deposits.rs
Closes: PRO-1007
Ignores extra BTC vouts in a single transaction.
> fix: ignore extra btc vouts

- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/migrations/v1.rs
- state-chain/pallets/cf-pools/src/tests.rs
Makes it easier to use the type in the lp api.
> refactor: remove generic from AssetPair types

- api/bin/chainflip-lp-api/src/main.rs
- api/lib/src/lib.rs
Closes: PRO-959
TODO: Add new command to the docs
- Didn't add this command to the bouncer test. Would be quite a bit of work to do the full redeem flow or reuse any of the fundRedem test code. Not sure if it's worth the time.
Sample usage, redeem all:
```sh
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "lp_request_redemption", "params": ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", null, "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]}' http://localhost:10589
```
> feat: add redeeming to LP API

- api/bin/chainflip-cli/src/main.rs
- api/bin/chainflip-cli/src/settings.rs
- state-chain/primitives/src/lib.rs
- utilities/src/with_std.rs
Closes: PRO-1003
limits the precision of the amount of flip the user can specify to 6 decimal places. But now we don't get bad rounding errors.
We can set the number of decimal places to whatever we want, I think it starts to get rounding errors if it's >11. Hard to test, so i just left it at 6, seems like plenty for now.
```sh
./target/debug/chainflip-cli redeem --exact 199995 0x835012efffe34fabf82f26a9712d3eff1b2d5145
Connecting to state chain node at: `ws://localhost:9944` and using private key located at: `/Users/jamieford/...`
Submitting redemption with amount `199995` FLIP (`199995000000000000000000` Flipperinos) to ETH address `0x835012efffe34fabf82f26a9712d3eff1b2d5145`.
```
> fix: CLI redeem amount rounding error

- state-chain/cf-integration-tests/src/lib.rs
- state-chain/cf-integration-tests/src/network.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/chains/src/btc/api.rs
- state-chain/chains/src/dot/api.rs
- state-chain/chains/src/eth/api.rs
- state-chain/chains/src/evm/api.rs
- state-chain/chains/src/evm/api/transfer_fallback.rs
- state-chain/chains/src/lib.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-emissions/src/mock.rs
- state-chain/pallets/cf-environment/src/mock.rs
- state-chain/pallets/cf-funding/src/mock.rs
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-vaults/src/mock.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/api_call.rs
- state-chain/traits/src/mocks/broadcaster.rs
Closes: PRO-789
Added pathway to handle failed vault transfers.
Basic workflow:
* When one transfer fails in BatchAll call, the Vault contract emits an event, which is observed by Engine and the Statechain is notified:
- pallet_cf_ingress_egress::Call::vault_transfer_failed()
* Here the TransferFallback EthApi call is constructed with the transfer details included.
* The call is delegated to the Broadcast pallet to be signed, but NOT broadcasted. 
* After threshold signature is completed, the details are saved in the Broadcast pallet, the same way Failed CCM are handled.
* In the next epoch, the call is re-threshold signed, using the same mechanism as Failed CCM.
* In the epoch after that, all call data are culled from on-chain …
> feat: Handle failed vault transfers

- Cargo.lock
- api/bin/chainflip-lp-api/Cargo.toml
- api/bin/chainflip-lp-api/src/main.rs
- api/lib/src/lp.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-974
Modified existing `cf_pool_orders` RPC call to take in optional LP.
If no LP is supplied, all pool orders are returned.
> `cf_pool_orders` RPC call can return all Pool Orders

- engine/src/dot/http_rpc.rs
- engine/src/dot/retry_rpc.rs
- engine/src/dot/rpc.rs
- engine/src/witness/dot.rs
- engine/src/witness/dot/dot_source.rs
Closes: PRO-1017
The issue is caused by the `state_getRuntimeVersion` rpc returning the new runtime version when called at the given block, but the events in that block at encoded with the old runtime.
- Use parent block hash when getting polkadot runtime version & metadata
- Added a test that gets the events from the block on polkadot mainnet that had the runtime update in it and caused the error that we seen in the logs. Then parses the events and checks for any failure to decode. This test is set to ignore because it uses an external public endpoint.
- A few other small changes cleaning up code here and there.
> Fix: CFE Witnessing, use parent block metadata when decoding events

- state-chain/pallets/cf-lp/src/lib.rs
I'm not sure how this was happened, but sweeping was intended to occur before withdrawal automatically.
Also I fixed that error message you mentioned previously.
> fix: sweeping before withdrawal

- Cargo.lock
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc_mempool.rs
- engine/Cargo.toml
- engine/src/btc/retry_rpc.rs
- engine/src/btc/rpc.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/btc_deposits.rs
Closes: PRO-1034
We want to track how much fees the vault has used to pay for egress.
> feat: track btc fees on success

- engine/src/p2p/core.rs
Previously in some cases it was possible for connections to never become "stale" (preventing reconnections when inactive). Specifically, when we fail to connect to a node due to some authentication error, this would result us reconnecting to the node manually (rather than this being done by zmq internally), but this also reset activity for that node to "now" on every restart, preventing us from detecting the connection as stale. I changed the code to carry over any previous activity state when reconnecting, so inactive connections should now always enter "stale" state.
Writing a proper unit test for this is a bit cumbersome and I'm not sure if worth it, but I have tested this manually by changing some parameters and observing …
> fix: connections can become stale when reconnecting

- engine/src/witness/btc/btc_deposits.rs
Was a 1/85 chance of the test failing because 2 of the txid's are the same. Maybe we should make the function take an id argument so the test can guarantee no collisions?
For now i just did the quickest thing and make all the bytes random so the chances and almost 0.
> fix: btc witnesser test failing sometimes

- bouncer/commands/read_workspace_tomls.ts
- bouncer/shared/json_rpc.ts
- bouncer/shared/lp_api_test.ts
- bouncer/shared/utils/bump_spec_version.ts
- state-chain/runtime/src/lib.rs
Carrying on from #4351 , this one checks spec_version is bumped, which is required to push the runtime version update.
Also closes: PRO-919
> feat: spec_version of PR is greater than spec version of current release

- .github/workflows/ci-development.yml
- .github/workflows/upgrade-test.yml
- bouncer/shared/fund_redeem.ts
- bouncer/shared/submit_runtime_upgrade.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
- localnet/init/scripts/start-all-engines.sh
- localnet/init/scripts/start-broker-api.sh
- localnet/init/scripts/start-lp-api.sh
- localnet/manage.sh
Closes: PRO-973
Manually can trigger an upgrade test from CI.
After I test the job manually against main a few times (and others do too) I'll put this in a nightly job too.
> feat: end to end network upgrade github action

- state-chain/chains/src/btc.rs
- state-chain/pallets/cf-environment/src/tests.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/primitives/src/lib.rs
> feat: more accurate btc fees

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- engine/Cargo.toml
- engine/src/state_chain_observer/client/mod.rs
- state-chain/node/Cargo.toml
- state-chain/runtime/Cargo.toml
Closes: PRO-1064
As discussed, this seems like the most appropriate solution at this time. I have tested this on localnet, both the happy path, and with the request timing out (by setting a very short timeout).
> fix: can timeout when updating CFE version

- state-chain/runtime/src/lib.rs
Just bringing the spec version up for consistency.
> chore: bump spec version to match release

- engine/src/btc/rpc.rs
- engine/src/dot/http_rpc.rs
- engine/src/eth/rpc.rs
Annoying seeing the \n\t\t in some log messages like this:
```
{"timestamp":"2024-01-03T10:51:08.061388Z","level":"ERROR","fields":{"message":"Failed to connect to Polkadot node at https://polkadot.api.onfinality.io:443/rpc?apikey=2cc**** with error: Rpc error: RPC error: Networking or low-level protocol error: Server returned an error status code: 504. Please check your CFE\n\t\t\t\t\t\tconfiguration file. Retrying in 10s..."},"target":"chainflip_engine::dot::http_rpc"}
```
> chore: fix log message formatting

- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/runtime-utilities/src/lib.rs
Related: PRO-1081
It's nice to be able to identify any of these "log_or_panic" messages as more critical than just a simple error message, which is how they appear in the logs - as these should be treated (almost) as if they are an assert.
Also adds broadcast id to one of the messages.
> chore: log_or_panic prepends its name

- engine/src/retrier.rs
Closes: PRO-1080
We want to reduce some noise for monitoring people/systems. Given attempt 0 failures occur occasionally we want to make them warn instead of error - but only for requests that are `RetryLimit::NoLimit` - since requests that do have a limit, we want to know that they fail immediately, as they won't be retried for as long, or perhaps not as long. e.g. in the case of broadcasting, we want to know when we hit a broadcast error, as this could be indicative of lack of ETH in the account for example.
> chore: warn on attempt 0 in retrier

- state-chain/pallets/cf-environment/src/tests.rs
- state-chain/primitives/src/lib.rs
Closes: PRO-1082
To spend one of our deposit UTXOs, we need:
32 bytes for the TX ID
4 bytes for the output index
1 byte to indicate that this is a segwit input
4 bytes for the sequence number
= 41 bytes
in addition to that we need the witness data, which is:
1 byte for the element counter
65 bytes for the signature
1 length byte for the unlock script
x bytes for the salt
1 byte to drop the salt
33 bytes for the pubkey
1 bytes to check the signature
34 bytes for the internal pubkey
= 136 bytes + x
Initially, we assumed that the salt would be 1 byte long, but since it is varint encoded, it can grow up to 9 bytes.
In Bitcoin, each byte of witness data is counted as only 1/4 of a byte towards the size of the transaction, so assuming …
> Bitcoin fee for broadcast was set below minimum resulting in broadcast aborted

- Cargo.lock
- engine/Cargo.toml
- engine/src/dot/http_rpc.rs
- engine/src/dot/retry_rpc.rs
- engine/src/dot/rpc.rs
- engine/src/state_chain_observer/client/base_rpc_api.rs
- engine/src/state_chain_observer/client/mod.rs
- engine/src/witness/dot.rs
Closes: PRO-1000
On bad blocks, which we did receive from getblock.io at some point - as in the issue, subxt would previously panic. Now, instead, they throw an error in 0.32.0+ version. So here I'm bumping the version to 0.32.1, since upgrading to 0.33.0 (latest at time of writing) requires a compiler version bump, which isn't necessary right now.
> fix: bump subxt version to 0.32.1

- .github/workflows/upgrade-test.yml
> fix: use existing script for upgrade job

- engine/multisig/src/crypto/bitcoin.rs
- engine/multisig/src/lib.rs
I've increased the limit to the theoretical maximum number of signing payloads we could receive, rather than removing the limit. This is to protect against potential spam attacks. Created this PRO-992.
> chore: increase limit on max number of bitcoin payloads in a ceremony to theoretical maximum

- localnet/manage.sh
This PR has no Linear ticket associated with it.
When the docker is not launched, or some auth-token is stale, or something else prevents the script from normal execution, it can be fruitful to have a possibility to hear out the underlying commands' complaints:
```sh
DEBUG_OUTPUT=/dev/fd/1 /bin/bash -x ./localnet/manage.sh
```
> Ability to specify output for the subcommands, other than `/dev/null`

- api/bin/chainflip-ingress-egress-tracker/README.md
- api/bin/chainflip-ingress-egress-tracker/docker-compose.yaml
- api/bin/chainflip-ingress-egress-tracker/src/settings.rs
This PR (https://github.com/chainflip-io/chainflip-backend/pull/4399) introduced redis for the ingress egress tracker, however the port used conflicts with localnet.
> fix: don't have conflicting redis port with localnet

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
Closes: PRO-1075
If the deposited amount is less than `ingress-egress::MinimumDeposit` — an `ingress-egress::DepositIgnored { reason : BelowMinimumDeposit }` will be emitted.
If the (net) swapped amount is less than `swapping::MinimumSwapAmount` — a `swapping::SwapAmountTooLow` will be emitted (apparently, a deprecated scenario: PRO-1101).
If for any other reason, the `egress_amount` of a swap appears to be zero — a `swapping::EgressAmountZero` will be emitted.
> Produce an event in case the swap yields a zero egress amount

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc_mempool.rs
Some helpful debug logs for the ingress-egress-tracker
> chore: debug logs to see get_raw_txs query

- bouncer/commands/try_runtime_upgrade.ts
Closes: PRO-1023
- Simplifies, using yargs for everything in the command.
- Adds default value for the runtime
> refactor: use yargs for all try_runtime_command options

- bouncer/commands/polkadot_runtime_update.ts
- bouncer/commands/read_workspace_tomls.ts
- bouncer/shared/polkadot_runtime_update.ts
- bouncer/shared/simple_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
- bouncer/shared/utils/bump_spec_version.ts
- bouncer/shared/utils/spec_version.ts
Closes: PRO-1031
Improves readability and functionality of this util.
> fix: bump spec version command only bumps when necessary

- api/bin/chainflip-ingress-egress-tracker/src/main.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc_mempool.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_broadcast_calls.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-2.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-3.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-4.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
> refactor(ingress-egress-tracker): remove unnecessary fields

- Cargo.lock
see: https://rustsec.org/advisories/RUSTSEC-2024-0003
Updates the dependency `h2` to fix the above vulnerability.
> chore: fix RUSTSEC-2024-0003

- engine/src/state_chain_observer/client/mod.rs
- engine/src/state_chain_observer/client/subxt_state_chain_config.rs
Closes: PRO-1126
Closes: PRO-1130
Uses a custom config for our subxt client used with the SC. This allows us to successfully submit extrinsics to our chain with subxt - in particular the `cfe_version` extrinsic, which is the only one we use subxt for.
v0.32.1 uses the finalised nonce where it previously used the unfinalised nonce. Here we use the system_accountNextIndex call to also account for any mempool txs, ensuring we get the correct nonce.
> fix: use custom subxt config + nextAccountIndex

- .github/workflows/upgrade-test.yml
Previously you could only run from the latest commit on main. Allowing it to be run from any commit on main (where the build has finished) means we can more easily see where issues were, by bisecting for example.
> feat: upgrade test can be run from any commit on main

- bouncer/shared/gaslimit_ccm.ts
- bouncer/tests/gaslimit_ccm.ts
Closes: PRO-1065
The problem was that the 3-node network behaves differently than the 1-node when it comes to aborting broadcasts, paired with a loose that that was added some time ago when we found a bug.
There is a loose check for a `TransactionFeeDeficitRecorded` that was just aiming to check that CCM transactions deficit get recorded, due to their checks being different on the state chain. That check was checking that after all the CCM test has succeeded there is at least one fee deficit recorded.
However, in 3-node network the broadcast aborted take a longer time than anything else and end up that there is no deficit recorded happening after the test is complete, which is when the last aborted transaction is recorded.
I …
> chore: fix ccm gas limit 3 nodes

- bouncer/full_bouncer.sh
- bouncer/run.sh
- bouncer/shared/new_swap.ts
- bouncer/shared/perform_swap.ts
- bouncer/shared/swapping.ts
- bouncer/shared/utils.ts
- bouncer/tests/broker_fee_collection_test.ts
Closes: PRO-965
New bouncer test: Runs a swap, checks that the broker fees are collected, then withdraws the broker fees, making sure the balance is correct after the withdrawal. This is done for all assets at the same time.
- Added an argument to `performSwap` so the test could use a custom `CommissionBps`.
- Set the default broker fee for all bouncer swaps to 1%.
> bouncer test: broker fee collection

- .github/workflows/ci-development.yml
- .github/workflows/release-sisyphos.yml
- .github/workflows/upgrade-test.yml
Closes: PRO-1149
Previously you could only run the upgrade-test on main builds. However, because we will often be merging PRs into release branch before releasing - to stabilise the release, we want to be able to test that the upgrade from the sisyphos-release job can be upgrade to from the berghain release version for example.
> feat: upgrade-test can work on releases

- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/traits/src/mocks/asset_converter.rs
Closes: PRO-1085
Added test to check the correct Event DepositIgnored(NotEnoughToPayFees) is emitted in case a deposit gets swallowed because fees are higher than the deposited_amount.
> test: ensure DepositIgnored(NotEnoughToPayFees) event is emitted

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/mock_btc.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/primitives/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/liquidity.rs
- state-chain/traits/src/mocks/ccm_handler.rs
- state-chain/traits/src/mocks/lp_balance.rs
- state-chain/traits/src/mocks/swap_deposit_handler.rs
Closes: PRO-1119, PRO-1119
- `withhold_transaction_fee` now also returns the deducted fee.
- Added `ingress_fee` to the `DepositReceived` event.
- Added `action` field to the `DepositReceived` event. This allows the frontend to explicitly associate an action with a deposit.
- Added `egress_fee` to the `EgressScheduled` event, which we either get from `withhold_transaction_fee` (for regular swaps) or set to `gas_budget` (for CCM swaps).
- As discussed, I moved `DepositBalances` to `schedule_egress`, which is now called on CCM swaps too.
Technically this needs a migration, since the meaning of "amount" in ScheduledEgressFetchOrTransfer has now changed to mean "after fee deducted", but because these items are cleared after a block …
> Feat: expose ingress and egress fees on events

- utilities/src/with_std/logging.rs
Just two changes:
- Just dedup some code
- Also allow the macro to print panic objects that are `String` instead of just `&str`. `String`s is common in ou code base, as we add a lot of runtime info into the panics.
Note there are two commits one, for each of the above changes, so it is a little easier to review both commits individually.
> improve start up macro

- api/bin/chainflip-broker-api/src/main.rs
- api/bin/chainflip-cli/src/main.rs
- api/bin/chainflip-cli/src/settings.rs
- api/bin/chainflip-lp-api/src/main.rs
- api/lib/src/lib.rs
- api/lib/src/lp.rs
- bouncer/shared/provide_liquidity.ts
- bouncer/tests/double_deposit.ts
- bouncer/tests/eth_witness_test.ts
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/pallets/cf-lp/src/benchmarking.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-lp/src/tests.rs
- state-chain/pallets/cf-swapping/src/benchmarking.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
Closes: PRO-1146
Added boost_fee param to the broker/lp CLI/API when opening a deposit channel 
-it's an optional parameter that defaults to 0 if not provided
-Added boost_fee also to the relevant extrinsics (request_liquidity_deposit_address and request_swap_deposit_address)
Currently the extrinsics use this new parameter only in the events they emit (SwapDepositAddressReady, LiquidityDepositAddressReady) -> This is a breaking change for the CFE.
> feat: added boost_fee param

- localnet/manage.sh
Noticed that the recently added `debug.log` does not exist when "re-creating" localnet, resulting in errors that abort the script. I put the creation of this file in `build-localnet()` as well to ensure it always exists. (Seems like creating it at the beginning of the file is still necessary.)
> fix: recreate debug.log in build-localnet

- engine/src/witness/btc/btc_deposits.rs
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/btc_deposit_channels.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/deposit_channels_with_boost_fee.rs
- state-chain/pallets/cf-ingress-egress/src/mock_eth.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-lp/src/tests.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/deposit_handler.rs
Closes: PRO-1170
- Use the boost_fee parameter passed in open_swap_channel/open_liquidity_channel extrinsic and add it to the DepositChannelDetails
- Migrate old channelDetails to include this new field, set to 0 for "old" channels
> feat: add boost fee field to DepositChannelDetails

- state-chain/pallets/cf-vaults/src/benchmarking.rs
- state-chain/pallets/cf-vaults/src/lib.rs
This allows the benchmarks ci run to complete.
> fix: remove old runtime benchmarks

- Cargo.lock
- state-chain/pallets/cf-threshold-signature/src/lib.rs
- state-chain/pallets/cf-threshold-signature/src/migrations.rs
- state-chain/pallets/cf-threshold-signature/src/migrations/v4.rs
- state-chain/pallets/cf-threshold-signature/src/mock.rs
- state-chain/pallets/cf-vaults/src/lib.rs
- state-chain/pallets/cf-vaults/src/migrations.rs
- state-chain/pallets/cf-vaults/src/migrations/v3.rs
- state-chain/runtime-upgrade-utilities/src/helper_functions.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
Closes: PRO-1178
Adds migrations for the threshols signer refactor. 
The migration happens in three steps:
1. Vaults pallet migration v3: migrates/intializes storage in the vault pallet
2. custom runtime migration `ThresholdSignatureRefactorMigration`: moves storage from vaults to threshold signer pallets.
3. Threshold Signer pallet migration: Renames Vaults -> Keys and initialises CurrentKeyEpoch and PendingKeyRotation. 
The migration only works if we upgrade outside of a rotation. 
I used this output from subxt diff as a basis:
```
~ BitcoinThresholdSigner
Storage Entries:
+ CeremonyIdCounter <- init from vault pallet
+ CurrentKeyEpoch <- init with current epoch
+ KeyHandoverFailureVoters <- empty
+ …
```
> feat: storage migrations for signing refactor.

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/runtime/Cargo.toml
Version bump to satisfy the version bump checker.
> chore: version bump chainflip 1.2.0 -> 1.3.0

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/remove_old_storage.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
Closes: PRO-1193
i noticed we were leaving some old storage lingering in the ingress egress pallet. This is a fix, and a storage migration to delete the old values.
> fix: remove old failed ccms

- .cargo/config.toml
- api/bin/chainflip-cli/src/settings.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-2.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-3.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-4.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls.snap
- state-chain/pallets/cf-governance/README.md
- utilities/src/with_std/task_scope.rs
The cargo aliases we current use, don't run the tests in the binary code. This enables those tests.
Note this also makes it so that all code snippets are tested.
> chore: enable all tests

- state-chain/runtime/src/lib.rs
Was just rechecking my PR, I found in the merge I missed this code where the new type I added `ForeignChainAndAsset` could be used.
> refactor: use ForeignChainAndAsset

- engine/multisig/src/client.rs
Just noticed this when I was debugging
> chore: avoid extra allocation

- .github/actions/get-workflow-commit/action.yml
- .github/workflows/upgrade-test.yml
- bouncer/shared/lp_api_test.ts
- bouncer/shared/provide_liquidity.ts
- bouncer/shared/submit_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
- bouncer/tests/all_concurrent_tests.ts
- localnet/init/scripts/start-all-engines.sh
- localnet/init/scripts/start-all-nodes.sh
- localnet/init/scripts/start-node.sh
- localnet/manage.sh
Fixes the upgrade-test 🚀 
Closes: PRO-1176
- Restarts the nodes on a runtime upgrade to ensure we also bring in any new RPC changes when we upgrade. And everything that goes with that
- Properly uses the latest commit to avoid issues where bouncer may not be compatible with the release it's running against
- Small migration test that I added when debugging - might as well leave it
> fix: upgrade-test should restart the chainflip-nodes on an incompatible upgrade

- state-chain/pallets/cf-lp/src/benchmarking.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-lp/src/mock.rs
- state-chain/pallets/cf-swapping/src/benchmarking.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/mock.rs
- state-chain/runtime/src/lib.rs
As a result of #4512 the benchmarks run broke because the caller did not have enough balance to pay for the channel opening fee. 
This fixes the issue by linking the FeePayment benchmark api.
> fix: ensure channel open fee can be paid in benchmarks

- .cargo/config.toml
- README.md
- state-chain/TROUBLESHOOTING.md
- state-chain/scripts/build-and-benchmark-all.sh
This command is broken since polkadot-sdk 1.6. 
I decided to remove it pending resolution of the underlying issue. It makes sense (sort of): building with benchmarks enabled is useful for benchmarking only. In 99% of cases we don't want to default to building with benchmarks. 
If you just want to build, you can `cargo build`.
If you want benchmarks, `cargo cf-build-benchmarks`.
> chore: remove cf-build

- state-chain/runtime/src/lib.rs
This commit prevents a compiler issue with the code coverage test runner. The issue was a compiler overflow when evaluating some trait bounds related to the Grandpa pallet.
~~I wasn't able to solve the underlying problem - presumably it's something related to the internals of llvm-cov, and presumably it will be fixed in due course.~~
~~For now I have avoided the issue by using llvm-cov's cfg(coverage) compiler flag. I used this to conditionally compiler a more 'friendly' version of the offending trait, which is irrelevant to our code coverage. The 'normal' version of this remains active for all other tests and CI checks.~~
Turns out there's a much simpler solution. Thanks @AlastairHolmes
> fix: allow test coverage to run

- bouncer/commands/check_witnesses.ts
- bouncer/shared/try_runtime_upgrade.ts
Adds debug logging to the try-runtime checks so it outputs the *value* it can't deecode and not just the key.
> feat: debug logs on runtime upgrade test

- bouncer/tests/broker_fee_collection_test.ts
Fixes bouncer on main, depending on the order of the txs, the fees can increase making these very tight bounds be exceeded - just widening the bounds a bit more.
> fix: more lenient max deposit fee

- engine/src/witness/common/chunked_chain_source/chunked_by_vault/continuous.rs
Closes: PRO-684
I finally worked out what problem this ticket was actually about. Its not really a significant bug (Explained in the issue).
Of course I feel the loop_select! macro is probably needs some work, as its clear from this and some of the other uses it's design doesn't work nicely in these complex situations, but it is still better than the tokio::select! (As what I do here, isn't possible *simply* with that macro).
We should review this together, and there is zero urgency to merge this.
> fix: continuous adapter (PRO-684)

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- engine/src/witness/btc.rs
- engine/src/witness/dot.rs
- engine/src/witness/eth/key_manager.rs
- state-chain/chains/src/any.rs
- state-chain/chains/src/benchmarking_value.rs
- state-chain/chains/src/btc.rs
- state-chain/chains/src/dot.rs
- state-chain/chains/src/eth.rs
- state-chain/chains/src/evm.rs
- state-chain/chains/src/lib.rs
- state-chain/chains/src/mocks.rs
- state-chain/chains/src/none.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-broadcast/src/tests.rs
Closes: PRO-1195
Updated transaction_succeeded and BroadcastSuccess Event to include the tx_ref which represent the transaction hash (or an equivalent way of identifying a transaction depending on the chain)
This PR is breaking, both an extrinsic used in the engine and an event changed
> feat: Expose tx_hash on BroadcastSuccess event

- bouncer/tests/broker_fee_collection_test.ts
The bounds are too tight, and we can't exactly predict the fees - this code is unit tested anyway. This test is more for testing the e2e flow a broker might take, rather than specific tight balances.
> fix: remove bounded balance check

- bouncer/shared/try_runtime_upgrade.ts
Disabling these checks since they throw a lot of false positives. 
We can re-enable when the below issue is resolved:
https://github.com/paritytech/polkadot-sdk/issues/2560
> fix: disable try-state checks

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
Add `origin` to ccmFailed event so it can be associated to a deposit channel.
> chore: add origin to ccm failed

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_broadcast_calls.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/btc_deposits.rs
- state-chain/chains/src/benchmarking_value.rs
- state-chain/chains/src/btc.rs
- state-chain/chains/src/btc/api/batch_transfer.rs
- state-chain/chains/src/btc/benchmarking.rs
- state-chain/chains/src/btc/deposit_address.rs
- state-chain/pallets/cf-environment/src/migrations/bitcoin_utxos.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/btc_deposit_channels.rs
Closes: PRO-1196
Added tx_ref to the ingress-egress-tracker
> ingress-egress-tracker: add tx_ref to redis

- bouncer/commands/get_proposed_runtime.ts
Closes: PRO-997
See [this Notion page](https://www.notion.so/chainflip/Verify-a-proposed-runtime-update-f8de089316244f34a0106b9aaca26f0c) for detailed instructions
> Added bouncer command to download a runtime update from a proposal

- .github/CODEOWNERS
- Add myself as code owner to the upgrade-test files
- Organise the codeowners file into groups of like folders/files
> chore: add myself as codeowner to upgrade-test

- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
(In preparation for PRO-1145)
Split these changes from https://github.com/chainflip-io/chainflip-backend/pull/4602 to avoid potential future migrations (since that PR will to be delayed now). These fields will be necessary when emitting events after performing the correponding channel action.
> feat: add block height and deposit details to PrewitnessedDeposit

- .github/workflows/upgrade-test.yml
- bouncer/shared/upgrade_network.ts
Includes some patches for flakiness for the upgrade-test.
Compare 1.2 to this: https://github.com/chainflip-io/chainflip-backend/tree/release-1.2-broker-test-fix to see changes
> fix: patch 1.2 broker test

- api/bin/chainflip-cli/src/settings.rs
Closes: PRO-1156
CLI wasn't working in debug mode, removing the version_short fixed the problem
The version command can now be called with: `--version` or `-V`
If we want `-v` instead I can add 
```
#[cfg(not(debug_assertions))]
#[clap(version = env!("SUBSTRATE_CLI_IMPL_VERSION"), version_short = 'v')]
pub struct CLICommandLineOptions { ... }
```
such that when we compile with --release flag enabled we can use `-v`
> fix: debug cli 

- api/lib/src/lib.rs
- api/lib/src/queries.rs
- engine/src/main.rs
- engine/src/state_chain_observer/client.rs
- engine/src/state_chain_observer/client/base_rpc_api.rs
- engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
- engine/src/state_chain_observer/client/storage_api.rs
- engine/src/state_chain_observer/sc_observer/tests.rs
- engine/src/witness/eth/key_manager.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/primitives/src/lib.rs
I've tested every case of error returning from the client - and that the downcast works as expected. alles gut.
A step towards single-binary CFE upgrades. This will allow the reason for shutting down to bubble up to the runner. 
Also allows for passing a starting block number to the SCC to ensure it won't miss blocks on the handover to the new version in an upcoming PR.
Non breaking but no point including it in the release.
> refactor: pass out CFE incompatibility exit information to main

- api/bin/chainflip-broker-api/src/main.rs
- api/lib/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/deposit_handler.rs
Closes: PRO-1233
Added channel_opening_fee field to the events:
- SwapDepositAddressReady
- LiquidityDepositAddressReady
> feat: Add channel opening fee to *DepositAddressReady Events

- .github/workflows/upgrade-test.yml
Fixes the fact the localnet configuration might be different between releases - we obviously want to start using the localnet of the same version as the release.
> fix: start localnet using correct commit

- state-chain/cfe-events/Cargo.toml
- state-chain/chains/Cargo.toml
- state-chain/runtime-upgrade-utilities/Cargo.toml
Running a test from inside chains crate e.g. `test_eth_eth` in VSCode fails due to some crate with missing runtime-benchmarks - haven't found culprit yet, but found some missing ones
> fix: missing feature flags

- api/bin/chainflip-broker-api/src/main.rs
Adds the possibility to change the broker api connection limit from its  current default of 100.
> feat: add broker api connection limit option

- Cargo.lock
- state-chain/custom-rpc/Cargo.toml
- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1185
Created a RPC call that returns System events (In EventRecord) scale encoded.
Changed the original get_events rpc to return event records instead of just the Raw events
> feat: RPC for returning scale-encoded System events

- state-chain/pallets/cf-broadcast/src/migrations/v3.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/btc_deposit_channels.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/deposit_channels_with_boost_fee.rs
- state-chain/runtime/src/lib.rs
Changes remaining unwraps (from post-upgrade checks) into expects, and also logs any try-runtime errors before unwrapping the result of the try-runtime call.
> fix: more try-runtime unwraps.

- state-chain/pallets/cf-cfe-interface/src/lib.rs
- state-chain/pallets/cf-cfe-interface/src/migrations.rs
I think this might finally fix the failing nightly try-runtime check.
> fix: correct cfe-events pallet version

- ci/docker/development/rust-base.Dockerfile
Turns out we don't actually need this.
Closes: PRO-1251
> chore: revert addition of cargo make

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-broker-api/src/main.rs
For consistency, this should return `NumberOrHex` instead of `u128`. `u128` is too large to be safely represented in JSON, but in this case there shouldn't be any issues because the fee shouldn't exceed 2^53 - 1 (at least immediately).
> fix(chainflip-broker-api): replace u128 with U256

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-broker-api/src/main.rs
Cherry picks #4656 onto release/1.3
> fix(chainflip-broker-api): replace u128 with U256 (#4656)

- engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
This adds logging so we can work out what is happening. I choose to leave the panic in as I don't want to change the behaviour, as it maybe the LP-API is in a bad state, and so the panic is useful in forcing a reset.
> logging: lp-api panic in submission watcher 

- bouncer/shared/broker_fee_collection.ts
- bouncer/shared/fund_redeem.ts
- bouncer/shared/utils.ts
- bouncer/tests/fund_redeem.ts
In #4622 the broker fee test was moved into all concurrent tests. However, that test exits the process when completed, which meant that all other running tests will exit once that one was completed. That is a problem not only if the other tests were still running but more importantly if they had "hanged" (e.g. waiting for an event) they wouldn't time out, effectively making it impossible to catch it.
Turns out, there was indeed a bug in the existential amount test.
> Prevent concurrent tests from exiting :bug: 

- state-chain/pallets/cf-account-roles/src/benchmarking.rs
- state-chain/pallets/cf-account-roles/src/lib.rs
- state-chain/runtime/src/lib.rs
This allows CI checks to pass.
> fix: add dummy benchmark for account roles pallet

- bouncer/commands/go_bananas.ts
This change adds USDT to the currencies supported by banana mode.
It also updates the banana mode code to support the new storage locations introduced as part of the 1.3 update.
> Add USDT to banana mode and update code to reflect new storage

- .cargo/config.toml
- Cargo.lock
- api/bin/chainflip-ingress-egress-tracker/Cargo.toml
- engine/Cargo.toml
- engine/src/state_chain_observer/client.rs
- engine/src/state_chain_observer/client/subxt_state_chain_config.rs
Resolves the cargo-audit issue (https://rustsec.org/advisories/RUSTSEC-2022-0093), as this bumps the ed25519-dalek dependency to v2
> chore: bump subxt to 0.33

- bouncer/run.sh
- bouncer/shared/gaslimit_ccm.ts
Closes: PRO-1095
- Tweak gas parameters. It was consistently failing before.
- Some rare flakyness is almost impossible to avoid in this test. However, as explained in PRO-1095 it was sometimes failing and sometimes hanging. `stopObservingCcmReceived` being a global variable instead of a local variable. There was a race condition causing that an unexpected broadcasted CCM swap would sometimes not be caught as an error and the test would hang. After this change, if the protocol works well, we should see it either pass or fail due to a need to tweak the gas, but never hang.
> Fix failing gas ccm tests

- PRACTICES.md
Until we get the CI working for external contributors, I've included the changes from @umbr4g3 from here: https://github.com/chainflip-io/chainflip-backend/pull/4434
> doc: fix a typo and minor grammar issue in PRACTICES.md

- .github/workflows/ci-cherry-pick.yml
This uses the original PR title as the title for the cherry pick
We already add the label `cherry-pick` to the prs
> chore: clearer cherry pick title

- engine/src/witness/common/chunked_chain_source/chunked_by_vault/continuous.rs
Basically, its an off by one error.
If the main stream misses the first block in an epoch, the continuous adapter would not fill the missed witness for that first block.
*Note if the engine was restarted it would fill in the gap.*
Looking at the code we were handling the last_processed_index and the start of the epoch in the same way, but the first is an index we don't want to process, but the second is an index we do want to process.
> fix: continuous adapter

- api/bin/chainflip-lp-api/src/main.rs
- api/lib/src/lp.rs
- api/lib/src/queries.rs
- bouncer/shared/lp_api_test.ts
- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-pools/src/mock.rs
- state-chain/primitives/src/chains/assets.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/src/liquidity.rs
- state-chain/traits/src/mocks/lp_balance.rs
Affects the responses of these rpcs:
lp-api rpcs
- lp_subscribe_order_fills
- lp_order_fills
- lp_get_open_swap_channels
- lp_asset_balances
node rpcs
- cf_pool_price_v2
- cf_subscribe_pool_price_v2
- cf_subscribe_prewitness_swaps
- cf_prewitness_swaps
- cf_supported_assets
- cf_asset_balances
I'll make a doc PR later today.
> chore: remove backcompat asset encoding from rpcs (and make them line up with newer Asset encoding)

- state-chain/pallets/cf-ingress-egress/src/lib.rs
This error is confusing. It's not really an error, can happen quite frequently while we're signing bitcoin transactions.
> fix: remove misleading error

- bouncer/shared/new_swap.ts
Hide whitespace for an easier review.
Closes: PRO-1093
If the dry_run fails, which it could, for example due to a nonce issue - then the extrinsic isn't retried, and the whole bouncer run fails. Here we just retry until success. 20 retries to be safe, only one retry is likely to ever occur based on the frequency we see this issue occur (not super frequently).
> fix: broker flakiness on bouncer CI

- state-chain/chains/src/arb/api.rs
- state-chain/chains/src/btc/api.rs
- state-chain/chains/src/dot/api.rs
- state-chain/chains/src/eth/api.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-vaults/src/mock.rs
- state-chain/pallets/cf-vaults/src/vault_activator.rs
Closes: PRO-1278
This is a minor thing, but we used an error to signal when AggKey rotation broadcast is not required. This change uses an Option to indicate whether a transaction needs to be submitted or not and only errors on real errors.
> chore: SetAggKeyWithAggKey should not error to indicate that a transaction is not needed

- README.md
- state-chain/README.md
I noticed there was quite a bit of outdated / confusing information. 
I've added some updates based an a very quick readthrough. More needs to be done but this is a small improvement.
> fix: update some obvious gaps / inaccuracies in the main readmes

- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/pallets/cf-witnesser/Cargo.toml
- state-chain/pallets/cf-witnesser/src/lib.rs
- state-chain/pallets/cf-witnesser/src/tests.rs
Closes: PRO-1287
Emit an event when a witnessed call is deposited, and when nodes are being punished for failing to witness a call.
This will help operators to connect what call they were being punished for (when they failed to witness in time).
> feat: emit event to help diagnose failed witnessing reports

- state-chain/runtime-upgrade-utilities/src/lib.rs
The perseverance genesis hash needs to be updated due to the phoenix.
> fix: use new perseverance genesis hash

- state-chain/runtime/src/lib.rs
It was added to try-runtime, but not the standard release.
> fix: add migration to executive for release

- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-threshold-signature/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
Makes the resign-broadcast method use a new temporary method that forces a delayed threshold signature request. 
This is to allow the request to be emitted *after* the runtime upgrade block.
The previous approach didn't work because CfeEvents storage is cleared in the on_initialize hook, which is executed after the runtime upgrade hooks.
> fix: delay threshold signature retries

- state-chain/node/src/chain_spec/testnet.rs
In order to run the broker_fee_collection_tests.rs on bouncer, we need this account to exist. Because we added this to genesis *after* 1.3, when we do the upgrade, the account doesn't exist, since it's not there at 1.3. So just adding it to genesis on the release branch since it's no impact, and the simplest.
> fix: broker test upgrade

- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
Closes: PRO-1295, PRO-1296, PRO-1294, PRO-1293
Still not very confident on the details/types in these events, but it's hopefully a good start.
- Added 3 new events
- modified `DepositBoosted` to have the amounts of each pool used.
- updated or added tests to cover the events.
TODO: Test on localnet.
> feat: Add prewitness deposit events

- .github/actions/get-workflow-commit/action.yml
- .github/workflows/ci-nightly.yml
- .github/workflows/upgrade-test.yml
- bouncer/tests/all_concurrent_tests.ts
- Use the last successful run of each pipeline - meaning we don't have to wait for completion each time (if the last completion doesn't matter)
- Log that it's the concurrent test that times out when it does
- Use sisyphos instead of persa - because currently there's a fix just on the sisy build to make the broker test work (and ultimately doesn't matter too much either way)
> chore: use success runs

- .github/workflows/upgrade-test.yml
- bouncer/commands/get_arbeth_balance.ts
- bouncer/commands/send_arbeth.ts
- localnet/init/scripts/start-node.sh
- state-chain/runtime/src/migrations/arbitrum_integration.rs
Also add liquidity after the upgrade, so in the case of new chains, there's liquidity there to swap into.
> fix: initialise ingress egress pallet values for arbitrum

- .github/workflows/upgrade-test.yml
- bouncer/commands/upgrade_network.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
- bouncer/shared/utils/exec_with_log.ts
This restructures some of the try-runtime tests and adds some utilities (see comments).
My main motivation for this was to write snapshots of failed runtime upgrade blocks so these can be downloaded for local debugging when something fails. 
After trying for a long time to get nodeJS/github actions to output stderr to be able to read the try-runtime log, I finally gave but. But then I realised (quite late) that the try-runtime output is already visible in the chainflip-node logs! So I just added a notice to that effect when the try-runtime tests exit with an error.
> feat: write snapshot if try runtime check fails

- state-chain/cf-integration-tests/src/authorities.rs
- state-chain/cf-integration-tests/src/funding.rs
- state-chain/cf-integration-tests/src/network.rs
- state-chain/cf-integration-tests/src/new_epoch.rs
- state-chain/cf-integration-tests/src/signer_nomination.rs
- state-chain/cf-integration-tests/src/witnessing.rs
- state-chain/pallets/cf-account-roles/src/migrations.rs
- state-chain/pallets/cf-broadcast/src/tests.rs
- state-chain/pallets/cf-funding/src/migrations.rs
- state-chain/pallets/cf-reputation/src/benchmarking.rs
- state-chain/pallets/cf-reputation/src/mock.rs
- state-chain/pallets/cf-threshold-signature/src/benchmarking.rs
- state-chain/pallets/cf-threshold-signature/src/mock.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/authorities.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-witnesser/src/benchmarking.rs
- state-chain/pallets/cf-witnesser/src/mock.rs
- state-chain/pallets/cf-witnesser/src/tests.rs
- state-chain/runtime-upgrade-utilities/src/lib.rs
- state-chain/runtime/src/chainflip/decompose_recompose.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/active_bidders.rs
- state-chain/runtime/src/migrations/vanity_names.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/epoch_info.rs
Closes: PRO-1201
- Changed Storage Items (currentAuthorities, historicalAuthorities) to use a Vec instead of BTreeSet
- Added randomization when creating the new authority set such that authorities are not sorted based on their ID
> feat: Authorities should be sorted pseudo-randomly

- utilities/src/with_std/spmc.rs
Have tested it works now, I don't feel there is a reasonable way to unit test, or that it is necessary.
> fix: PRO-1330 - Move Location::panic() to inside the function, so it outputs the caller of the fn and not of the async block poll fn.

- bouncer/commands/upgrade_network.ts
Fixes this, which shows up occassionally:
```
upgrade_network exiting due to error:  Error: Timed out after 900000 ms.
at <anonymous> (/opt/actions-runner/_work/chainflip-backend/chainflip-backend/bouncer/shared/utils.ts:264:13)
at runWithTimeout (/opt/actions-runner/_work/chainflip-backend/chainflip-backend/bouncer/shared/utils.ts:261:18)
```
> fix: extend upgrade timeout

- engine/src/state_chain_observer/client/base_rpc_api.rs
- engine/src/state_chain_observer/client/extrinsic_api/signed.rs
- engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
- engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher/tests.rs
We had the problem where dry-run wouldn't re-obtain the runtime version when it is out of date, so here I changed the dry-run to always re-obtain the runtime version.
> fix: dry run gets fresh runtime version (PRO-1249)

- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/add_boost_pools.rs
- state-chain/pallets/cf-ingress-egress/src/mock_btc.rs
- state-chain/pallets/cf-ingress-egress/src/mock_eth.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/arbitrum_integration.rs
- state-chain/runtime/src/safe_mode.rs
Closes: PRO-1300
- Added 3 safe mode enable flags for the boost features (add, stop, boost). These are implemented for each chain.
- Changed the eth and btc mocks to work with the chain instance's as it was now needed.
- Added unit tests for the 3 flags.
- Added the new safe mode settings to the 1.4 arbitrum migration and set them to CODE_RED by default, so for testnet/mainnet we can turn the boost features on when we are ready.
- For localnets, the boost features will be defaultly enabled at genesis.
> feat: added safe mode for ingress egress pallet

- .github/workflows/upgrade-test.yml
Should fix recent issues such as: https://github.com/chainflip-io/chainflip-backend/actions/runs/8803229843
> chore: git fetch --all before checkout in upgrade-test

- engine/src/btc/retry_rpc.rs
- engine/src/dot/retry_rpc.rs
- engine/src/evm/retry_rpc.rs
- engine/src/evm/retry_rpc/address_checker.rs
- engine/src/retrier.rs
- state-chain/pallets/cf-vaults/src/vault_activator.rs
Having the log parameter after the async-closure parameter creates a common lifetime issue that we need to move the parameters into the async-closure, but we also need those parameter to create the text for the log message. Meaning you need to uninline the log parameter and create it before creating the async-closure, or clone the parameter. This makes the code more difficult to read. By moving the log message parameter first you avoid that.
Also I noted that the activate_key function exists, but wasn't always being in this particular case for no reason.
> refactor: minor cleanup of retrier code and vault pallet

- .github/workflows/ci-main-merge-queue.yml
- .github/workflows/ci-main.yml
Since merge queues, we can optimistically build in ci-main, speeding it up, because it's *very* unlikely to fail. 
We also already run the post-check and upgrade-check as part of the merge queue, so these don't need to be run again (especially since they are slow). 
Note: We still run bouncer on nightly, as it uses `full_bouncer` which runs some extra, longer tests.
> feat: optimistic build, streamlined ci-main

- bouncer/shared/utils.ts
Getting the Liquidity Deposit safe mode enabled error again :/
Doesn't really make sense, so printing the raw dispatch error for when it happens again, so we can check it's not a bug in the error parsing (which is possible, we've seen quite a few metadata related polkadot-js issues lately).
> chore: log raw dispatch error

- .github/workflows/ci-development.yml
Build with try-runtime so the upgrade test can be run on branches in development
I think this should close: PRO-1258
> feat: try-runtime build step on dev ci

- state-chain/pallets/cf-vaults/src/lib.rs
- state-chain/pallets/cf-vaults/src/tests.rs
As discussed with Dan, we don't want to enable safe mode, when the agg-key is set by governance, as this is a normal situation (on new external chain contract deployment) and governance can independently set safe mode if required.
This also solves a problem were bouncer was intermittently failing, due to code red being set, on initializing Arbitrum.
> fix: don't set code red on "agg-key set by gov-key"

- bouncer/commands/go_bananas.ts
- bouncer/shared/broker_fee_collection.ts
- bouncer/shared/evm_deposits.ts
- bouncer/shared/perform_swap.ts
- bouncer/shared/polkadot_runtime_update.ts
- bouncer/shared/swapping.ts
- bouncer/tests/all_concurrent_tests.ts
- bouncer/tests/swapping.ts
In support of PRO-1342
I found it quite tedious finding out which swaps didn't finish from what's currently avalable in the logs.
Now record and update their status in a `SwapContext` object, which is shared between all concurrent swaps. When the test times out, we now print a report containing the unsuccessful swaps along with their status (the stage at which they got stuck).
> feat: better diagnostics for bouncer swaps

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__boost_fees_serialization.snap
- state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1356
I went ahead and implemented this based on the discussion on discord without waiting for PRO-1355 considering we want to merge this for 1.4. Hopefully this is close to what we want.
- Extended boost pool storage to additionally store fees earned by every booster for each pending boost.
- Added `cf_boost_pool_pending_fees` rpc to expose those fees (internally, we still use the same runtime api call, cf_boost_pool_details, which now also returns the fee).
- The rpc works similarly to `cf_boost_pool_details`, in that it takes an optional asset, and returns data for all fee tiers for the asset; when the asset is not specified, data for all assets is returned.
- Added insta test for the new RPC's response.
Example: …
> feat: store boost fees explicitly + rpc

- state-chain/node/src/chain_spec/berghain.rs
- state-chain/node/src/chain_spec/perseverance.rs
- state-chain/node/src/chain_spec/sisyphos.rs
- state-chain/runtime/src/migrations/arbitrum_integration.rs
Closes: PRO-1224
Update chainspecs and migrations with the correct addresses.
The `eth_address_checker_address` and `arb_vault_address` have the same address, that is not a mistake. It's just that we use the same deployer wallet.
> Update Arbitrum migrations and chainspec

- .github/workflows/upgrade-test.yml
Should fix the permission issue we see on upgrade-test atm: https://github.com/chainflip-io/chainflip-backend/actions/runs/8971952228/job/24639118948
> fix: upgrade test permissions

- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/weights.rs
Closes: PRO-1302
Wouldn't normally open a PR this small, but wanted to close PRO-1302 (not sure why I didn't bundle this in some other PR).
Although the names are still quite generic, at least they no longer resemble "hooks", and something more specific could be misleading (as they do more than one thing).
> chore: rename boost methods

- api/lib/src/lp.rs
- state-chain/chains/src/eth/api/register_redemption.rs
- state-chain/chains/src/evm/api/execute_x_swap_and_call.rs
- state-chain/node/src/chain_spec.rs
- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/traits/src/liquidity.rs
we no longer need the allow(too_many_arguments) since the threshold is now set to 100
> chore: remove ` too_many_arguments` warning supression

- .github/workflows/ci-main-merge-queue.yml
- .github/workflows/upgrade-test.yml
Sisyphos has been tagged, so we should use persa.
> fix: use release-persa for upgrade-test

- .github/workflows/upgrade-test.yml
Now that we are upgrading *from* a version that uses the engine-runner, we need to set the permissions for it in the *from* side of the test.
> fix: engine-runner permissions +x

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-ingress-egress-tracker/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- bouncer/shared/polkadot_runtime_update.ts
- bouncer/shared/upgrade_network.ts
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/runtime/Cargo.toml
A few fixes:
- Now 1.4 is on sisy, any incompatible upgrades now need to kill the `engine-runner` not the `chainflip-engine` as before.
- Bumps the versions to match the 141 spec version, ensuring we do actually do the upgrade-test correctly.
- Removes an unnecessary await that was on a sync function
> fix: upgrade test same version

- .github/workflows/_40_post_check.yml
- ci/docker/development/chainflip-engine.Dockerfile
- ci/docker/production/chainflip-engine.Dockerfile
- engine-runner-bin/Cargo.toml
- engine-runner-bin/build.rs
- engine-runner-bin/package/berghain/chainflip-engine.service
- engine-runner-bin/package/perseverance/chainflip-engine.service
- engine-runner-bin/package/sisyphos/chainflip-engine.service
- engine-runner-bin/package/test/chainflip-engine.service
- engine/src/lib.rs
- localnet/init/scripts/start-engine.sh
- localnet/manage.sh
I want to test the apt and docker packaging is correct on a linux machine before merging this.
To test it works:
1. `unset DYLD_LIBRARY_PATH`
2. `cargo clean`
3. `cargo cf-test`
Tests should pass.
@martin-chainflip has tested this and it works.
I've tested the linux and docker builds on a linux machine to ensure the builds and path finding works correctly.
- Use `@rpath` instead of `DYLD_LIBRARY_PATH` to find the dylibs for mac - so `DYLD_LIBRARY_PATH` doesn't need to be set.
- For linux and docker we supply the correct paths `/usr/lib/chainflip-engine` or `/usr/local/lib` respectively. 
- Used install_name_tool to set the path for the dylib
- $ORIGIN doesn't work the way `@executable_path` does for mac, so leaving that to …
> chore: better dylib path finding

- .github/workflows/ci-development.yml
Hacks around the branch protection. We can now protect the branch by requiring "upgrade-check" to be run, but it will be skipped (which is a pass). Then on the merge queue, it will actually run, such that if it fails, it'll fail the PR, since upgrade-check is a branch protection rule
> feat: require upgrade-check pass on merge queue

- .github/workflows/upgrade-test.yml
I also manually ran a workflow to ensure that also still works: https://github.com/chainflip-io/chainflip-backend/actions/runs/9188546171
Previously the upgrade test was pulling the last successful commit from the main workflow. However, what we want to do is use the artefacts that are built as part of the commit that triggers the workflow. Though, I also maintained the behaviour of allowing a manually triggered workflow and selecting the commit as before.
There are effectively 3 cases:
1. Workflow call/dispatch with provided commit to upgrade to
2. Workflow call/dispatch without provided commit
3. Push/pull request (in which case, use the commit of the push/pr)
> feat: run upgrade-test on commit of trigger

- bouncer/shared/lp_api_test.ts
- state-chain/pallets/cf-lp/src/tests.rs
Fixes a flaky bouncer test that has been fixed on main.
> pick: chore: move lp balance integrity check to unit test (#4852)

- Cargo.lock
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__swap_output_serialization.snap
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-pools/Cargo.toml
- state-chain/pallets/cf-pools/src/benchmarking.rs
- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/mock.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-validator/src/migrations/authorities.rs
- state-chain/primitives/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/src/liquidity.rs
- utilities/src/with_std/rpc.rs
Closes: WEB-1059, WEB-1062
The current implementation of the quoter uses a version of the AMM wrapped in a rust library that converts it to a native Node.js addon. Then we query the state of the pools via RPC and then add the limit orders we receive from the market makers before we simulate a swap though the pools.
This greatly simplifies the status quo by preventing us from having to monitor changes to the AMM and backporting them into our version of it as well as reducing the number of rpc calls we have to make to just one. 
This is the first in a series of pull requests that will create a more well-rounded swap rate custom RPC that will not only simulate the swap though the pools but also:
- accept additional limit orders to …
> feat(custom-rpc): swap rate with limit orders [WEB-1059][WEB-1062]

- .github/workflows/upgrade-test.yml
- bouncer/shared/upgrade_network.ts
When the versions are "compatible" it doesn't mean the RPCs will be unbroken. So we have to start the node with the new version to ensure the RPC updates are reflected on the node.
e.g. see this failure: https://github.com/chainflip-io/chainflip-backend/actions/runs/9191091275/job/25277048379
Upgrade tests should pass now: https://github.com/chainflip-io/chainflip-backend/actions/runs/9208000827
> fix: restart node on compatible upgrade

- bouncer/tests/all_concurrent_tests.ts
Hitting memory limit for bouncer in upgrade-test, but it's hitting it on the bouncer run of release, so we need to update it here. 
Ideally we can decrease memory usage, but want to get the upgrade-test blocking check in before looking into that.
> fix: increase javascript memory limit for bouncer all_concurrent_tests

- state-chain/pallets/cf-environment/src/migrations.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/arbitrum_integration.rs
This removes some spurious warnings from the 1.4 runtime upgrade. Checked against perseverance and berghain.
> chore: remove errors and warnings from runtime upgrade

- bouncer/.eslintrc.json
- bouncer/commands/check_witnesses.ts
- bouncer/commands/go_bananas.ts
- bouncer/polkadot/keyring.ts
- bouncer/polkadot/util-crypto.ts
- bouncer/shared/broker_fee_collection.ts
- bouncer/shared/cf_governance.ts
- bouncer/shared/fund_flip.ts
- bouncer/shared/fund_redeem.ts
- bouncer/shared/lp_api_test.ts
- bouncer/shared/multiple_members_governance.ts
- bouncer/shared/new_dot_address.ts
- bouncer/shared/new_statechain_address.ts
- bouncer/shared/perform_swap.ts
- bouncer/shared/polkadot_keyring.ts
- bouncer/shared/polkadot_runtime_update.ts
- bouncer/shared/provide_liquidity.ts
- bouncer/shared/range_order.ts
- bouncer/shared/redeem_flip.ts
- bouncer/shared/setup_swaps.ts
- bouncer/shared/swapping.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/utils.ts
- bouncer/tests/double_deposit.ts
- bouncer/tests/eth_witness_test.ts
Resolves a source of flakiness that is fixed on main, but this is not on release. Needs to be on release so the upgrade-test can pass on main too.
Example of said flakiness: https://github.com/chainflip-io/chainflip-backend/actions/runs/9283460684/job/25545685114
> pick: refactor(bouncer): ensure crypto ready (#4858)

- bouncer/shared/contract_swap.ts
- bouncer/shared/perform_swap.ts
- bouncer/shared/swapping.ts
We added it for channel swaps but not contract swaps, and contract swaps have been getting stuck occasionally, so this should help see where they get stuck.
> feat (bouncer): add swapContext to contract swaps

- state-chain/chains/src/btc/utxo_selection.rs
- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-environment/src/tests.rs
- state-chain/traits/src/mocks/key_provider.rs
@j4m1ef0rd noticed that consolidation test didn't work on localnet, so I had a look (it is part of full bouncer, but not run by default in PRs). Looks like at some point the code was changed resulting in consolidation being skipped if the previous key isn't available (which it is not the case unless you've rotated multiple times on localnet).
Arguably, we don't care about this edge case, but it is still techincally a bug and it is annoying that the test stopped working on localnet (it wasn't a problem in full bouncer because we rotate more than once there), so I fix it here.
**Update**: This turned out to be more work than I originally thought, but I decided that I might as well finish what I started. Specifically, some changes were required in unit tests, which I found a bit messy. Some …
> fix: utxo consolidation works without prev key

- bouncer/commands/setup_vaults.ts
- bouncer/shared/cf_governance.ts
- bouncer/shared/create_lp_pool.ts
- bouncer/shared/initialize_new_chains.ts
- bouncer/shared/provide_liquidity.ts
- bouncer/shared/range_order.ts
- bouncer/shared/setup_arb_vault.ts
- bouncer/shared/setup_boost_pools.ts
- bouncer/shared/submit_runtime_upgrade.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/substrate.ts
- bouncer/tests/rotation_barrier.ts
- bouncer/tsconfig.json
Intention is to use this new observeEvents to memoize the subscription instead of creating a new subscription for each event listener.
Part of: PRO-1411
> refactor(bouncer): migrate file to new observe event

- localnet/manage.sh
I noticed that "recreate" option stopped working on localnets, and realised that the fix I've merged in the past for this (https://github.com/chainflip-io/chainflip-backend/pull/4487) got reverted in https://github.com/chainflip-io/chainflip-backend/pull/4796. I'm assuming this wasn't intentional, but let me know if it was @albert-llimos.
> fix: add missing debug.log on recreate in localnet/manage.sh

- state-chain/chains/src/sol/api.rs
- state-chain/chains/src/sol/instruction_builder.rs
- state-chain/chains/src/sol/sol_tx_core.rs
Closes: PRO-1390
Added Usdc Token support for CCM messages in the Solana instruction builder and Solana API
> feat: Usdc token support for Solana CCM transaction

- bouncer/shared/multiple_members_governance.ts
- bouncer/shared/utils.ts
Possible the GovernanceExecuted is actually picking up the executed of another test, and therefore maybe running the check too early. This just protects against that.
> fix: more robust governance bouncer test

- Cargo.toml
- engine-runner-bin/README.md
Closes: PRO-1419
Ensures the `LC_ID_DYLIB` is set with `@rpath/libname` to allow for relative linking and searching via LC_RPATH of the runner.
> chore: use rpath in profile for linking dylibs

- .github/workflows/release-sisyphos.yml
Closes: PRO-1380
Quite simply, run upgrade-test on push to release branches. Given we generally don't expect many pushes to release branches this is fine, and of course, we should be more conservative and run all the CI checks on release, as this is what will go out.
> feat: run upgrade-test on push to release branches

- engine-runner-bin/build.rs
The new dylib is located in the directory of the executable. This was missed in #4939
> fix: mac rpath search should use executable's directory

- bouncer/shared/contract_swap.ts
- bouncer/shared/swapping.ts
Picks across part of #4948 , see there for desc.
To remove flakiness from the upgrade test which needs to run bouncer on 1.4 first.
> pick: contract swaps shouldn't wait for SwapScheduled (#4948)

- .github/workflows/_25_package.yml
Closes: PRO-1443
This fixes an issue where, if we had a release branch that had been tagged, causing release-berghain to run, then the next time we released off that branch, the "latest" release would actually be the previous patch release, which is not what we want.
Instead, if we're on release/1.4 we want to get the latest 1.3.x tag and use that.
Will need to cherry-pick this across to release too.
> fix: package should use old dylibs based on tags

- engine-upgrade-utils/src/lib.rs
1.4.3 has arb, so we shouldn't ignore passing them in. I created PRO-1455 to address testing such regressions.
> fix: don't ignore arb settings

- .github/workflows/upgrade-test.yml
In the merge queue, they will both try to write to the same place, so this just differentiates them so one is not overwritten.
> chore: differentiate chain explorer name b/w upgrade test and bouncer

- api/bin/chainflip-broker-api/src/main.rs
- api/lib/src/lib.rs
- api/lib/src/lp.rs
Closes: PRO-1277
Ensures we return hex-encoded amounts from broker api. 
Improved error messages. 
Examples:
`broker_withdraw_fees` success:
```json
{
"jsonrpc": "2.0",
"result": {
"tx_hash": "0x3fc8762e54d9eada666adb8adfabe18099611e62544751fff5b5f45a8a8db81d",
"egress_id": [
"Ethereum",
93
],
"egress_amount": "0xa68859da017bcdc",
"egress_fee": "0x77a10",
"destination_address": "0xabababababababababababababababababababab"
},
"id": 1
}
```
`broker_withdraw_fees` error:
```json
{
"jsonrpc": "2.0",
"error": {
"code": -32000,
"message": "Module error ‘NoFundsAvailable‘ from pallet ‘Swapping‘: ‘The withdrawal is not possible because not enough funds are available.‘"
},
"id": 1
}
```
> fix: use U256 return value for asset volume

- state-chain/amm/src/common.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1410, PRO-1437
- Changed the `get_scheduled_swap_legs` function to not return a result. In case of swap simulation failure, it will use the given pool_price (of the input asset) to estimate the swap amount (in Usdc) for the second part of the leg.
- The first leg will now always be returned, even if the swap simulation fails. 
- The only reason the second leg would not be returned, is if there is no pool_price (no liquidity in the pool at all)
- Added a unit test to cover this new fallback code.
> feat: scheduled swap sub price estimation fallback

- state-chain/pallets/cf-witnesser/src/lib.rs
- state-chain/pallets/cf-witnesser/src/mock.rs
- state-chain/pallets/cf-witnesser/src/mock/dummy.rs
- state-chain/pallets/cf-witnesser/src/tests.rs
Closes: PRO-1391
The ExtraCallData storage currently takes up ~300Mb of storage on mainnet. 
This PR makes two changes:
1. remove the ExtraCallData when we recombine it to construct the dispatch calldata.
2. prevent it from being inserted if we have already processed it (ie. if the call has already passed the voting threshold).
This is a non-breaking runtime change.
> fix: eagerly prune ExtraCallData

- ci/docker/development/bitcoin/start.sh
In order to be able to thoroughly test our swapping app transitions, we need to increase the block producing time.
> chore: increase backspin btc block time

- .github/workflows/_01_pre_check.yml
- .github/workflows/_10_test.yml
- .github/workflows/_11_coverage.yml
- .github/workflows/_20_build.yml
Closes: PRO-1461
Encountered some issues with the caching, where artifacts from unrelated PRs were polluting each other. This at least protects main and releases by only using the cache on PRs to develop. The issue can still occur, but at least broken code can't make it into main.
> fix: only use cache on PRs to main

- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-lp/src/tests.rs
record_fees function was broken recently, as mutate gives a mut reference and doesn't use the closures return value to set the storage item.
> fix: record_fees

- state-chain/chains/src/sol/api.rs
- state-chain/runtime/src/chainflip.rs
Closes: PRO-1475
Implements the Solana's transaction builder - which is used to actually broadcast the Solana Call
> feat: Solana transaction builder implementation

- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-threshold-signature/src/key_rotator.rs
- state-chain/pallets/cf-threshold-signature/src/lib.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/traits/src/mocks/cfe_interface_mock.rs
Closes: PRO-1434
Removes deprecated events, and removes comment for events that we do want to leave, since they are used externally - and we don't want external APIs depending on CFE Events pallet events.
> chore: remove deprecated events

- api/lib/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
As per @niklasnatter request, adding FoK parameters (`refund_parameters`) to the `SwapDepositAddressReady` event. Updated one of the test to check that it is correctly set. Also added `refund_parameters` to the CLI's `SwapDepositAddress` since its purpose seems to be to observe the event and read its parameters (I'm not sure how this is used exactly, but I'm assuming this is converted to JSON, which means the change is non-breaking).
> feat: add fok params to SwapDepositAddressReady

- engine-runner-bin/README.md
This fixes an issue with the engine dylib file that was preventing it from running on mac localnets. 
The dylib install path was previously set to a local path on my machine.
Now it's correctly set to a relative path. 
The engine lib build script already do this correctly on main, but that change hasn't been ported to the release branch. Hence the release version 1.4.5 libs were compiled with absolute paths instead of relative paths. 
Before:
```bash
otool -L old-engine-dylib/libchainflip_engine_v1_4_5.dylib | head -2
old-engine-dylib/libchainflip_engine_v1_4_5.dylib:
/Users/dan/[...]/old-engine-dylib/libchainflip_engine_v1_4_5.dylib (compatibility version 0.0.0, current version 0.0.0)
```
After:
```bash
otool -L old-engine-dylib/libchainflip_engine_v1_4_5.dylib | head -2 …
```
> fix: use rpath in engine dylib

- state-chain/pallets/cf-ingress-egress/src/migrations/add_refund_params.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/remove_prewitnessed_deposits.rs
This (hopefully) fixes a migration issue that was occurring on CI. 
The problem was the two ingress/egress migrations were updating the same storage and we were ending up with corrupted/unmigrated values.
> fix: ingress-egress pallet migration co-dependency

- engine/src/retrier.rs
Closes: PRO-1409
The idea here is that we want to keep trying the secondary endpoint until a specified time (2 minutes) has elapsed. We then try the primary endpoint again to check it's online. If not, we try the backup again. Note that this is global to all requests for the chain - previously every request would start by trying the primary, but not it will try the currently preferred endpoint, and occassionally re-attempt the primary, as we want to bias towards the primary.
> feat: smart retrier endpoint selection

- engine/src/retrier.rs
- utilities/src/with_std/metrics.rs
Added a label "endpoint" to RPC_RETRIER_TOTAL_REQUESTS metric such that we know which endpoint (primary or secondary) we are using.
> feat: add primary/secondary label to RPC_RETRIER_TOTAL_REQUESTS metric

- .github/workflows/_40_post_check.yml
- .github/workflows/upgrade-test.yml
Closes: PRO-1480
1.4 doesn't have the extra dylib pathfinding metadata in the runner binary so still requires the dylib to be copied to a default search path in the upgrade-test. However, we can remove these from post-check which is running the current version.
> chore: remove cp dylibs from post check

- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
Closes: PRO-1503
https://github.com/chainflip-io/chainflip-backend/blob/main/state-chain/pallets/cf-validator/src/lib.rs#L752
The corresponding code checks the range last_expired..=current but should check last_expired+1..=current
> fix: allow validators to deregister once they no longer have relevant key material

- .github/workflows/_40_post_check.yml
- .github/workflows/upgrade-test.yml
It turns out that the change here: https://github.com/chainflip-io/chainflip-backend/pull/5044/files was actually wrong. The reason it worked before is because the runs were using *old* dylibs, i.e. one that had already been moved into /usr/lib because at that time `/usr/lib` was not being cleaned up on the runner. 
Now that `/usr/lib` is cleaned up, it's clear that the relative linking is not working as expected. We should find out why: PRO-1510 . But getting this in now because it's blocking.
> fix: cp .so files to /usr/lib

- engine/src/retrier.rs
Closes: PRO-1262
See linked issue.
> feat: return early if no client ready on retry limited requests

- ci/scripts/check_runtime_spec_version.sh
It was grepping two `spec_version` s from the file.
> fix: grep correct spec_version

- .github/workflows/upgrade-test.yml
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-ingress-egress-tracker/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
* chore: bump `main` to `1.6.0` 👆
* chore: use `.dylib` built on GHA M2 runner 🥽
* fix: get `1.4.6` dylib 🐛
* fix: use correct path 🙈
* fix: use `curl` and dump `wget` 🤬
* chore: run upgrade test 👹
* Revert "chore: run upgrade test 👹"
This reverts commit dc15f0d9b617db11940bacba717f51678a232854.
> cherry-pick: package fixes 🍒

- foreign-chains/solana/sol-prim/src/lib.rs
- foreign-chains/solana/sol-prim/src/pda.rs
- foreign-chains/solana/sol-prim/src/tests/pda.rs
- state-chain/chains/src/sol/instruction_builder.rs
- state-chain/chains/src/sol/sol_tx_core.rs
- state-chain/chains/src/sol/sol_tx_core/address_derivation.rs
Renaming `DerivedAta` because it was wrong. That was a Program derived address (PDA) but not an ATA (Associated token account).
> chore: rename DerivedAta to PdaAndBump

- Cargo.lock
- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/Cargo.toml
- state-chain/traits/src/liquidity.rs
Closes: PRO-1506
- Added an RPC `cf_available_pools` which rdated the code where we returns the available pools as a Vec<AssetPair>
- Added pools() to PoolApi to access these info internally, updated the code to use this new function instead of looping through all assets but usdc (error prone if we don't create the pool as soon as we release a new chain or if we decide to create pools with quote asset != USDC)
> feat: RPC to return available pools

- .github/workflows/ci-development.yml
- engine/src/sol/retry_rpc.rs
- engine/src/sol/rpc.rs
- engine/src/witness/sol.rs
Closes: PRO-1499
Add a check that the transactions is processed after it's send (with a delay). If not, it errors so it gets retried again by the retrier rpc. See an example of this in the Rust SDK client:
https://docs.rs/solana-rpc-client/2.0.2/src/solana_rpc_client/nonblocking/rpc_client.rs.html#592
This is because the `send_transaction` won't ensure that the transaction hasn't been dropped and in case of congestion there is no other mechanism than just manually checking if the transaction has landed and resending it otherwise.
> Feat: solana engine broadcast retries

- bouncer/shared/utils.ts
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
`SwaprRequested` is now emitted before any other event (e.g. SwapScheduled) that mentions swap_request_id, as was requested by the product. One difficulty was that we can reject a CMM request in some cases (the check is done in `init_swap_request` for various reasons), and originally I didn't want to emit `SwapRequested` event in that case, but now I'm thinking it is OK as long as we also emit `SwapRequestCompleted` immediately after `CcmFailed`, so that's what I did here. (The alternative was to split the match statement so we check check, then emit the event, and then later only assert on the fact that we have performed the check, but that would make the code a bit ugly).
> feat: emit swap request first

- engine/src/sol/retry_rpc.rs
- engine/src/witness/sol.rs
By default the nodes store a few days worth of data which should be plenty for our purpose. Setting the flag to true makes the node look into months worth of data (terabytes) making the query a lot more computationally heavy.
> chore: Solana engine not require tx history

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- engine/src/witness/common/chunked_chain_source/chunked_by_vault/monitored_items.rs
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/runtime/Cargo.toml
Means we won't delay the prewitnessing of a particular. Previously we would wait for the *next* external chain block before prewitnessing.
This release would have to be done runtime upgrade first and then CFE upgrades.
> fix: prewitness deposits without delaying for a block

- bouncer/commands/new_swap.ts
Closes: PRO-1537
- Refactored the new swap command to use yargs to allow for more complex command line arguments.
- Added the 3 FoK refund parmas as command line options.
- Changed the `maxBoostFeeBps` to a command line option instead of an optional positional argument.
> refactor: bouncer cmd for FoK swap

- state-chain/pallets/cf-broadcast/Cargo.toml
- state-chain/pallets/cf-broadcast/src/migrations.rs
- state-chain/pallets/cf-broadcast/src/migrations/api_call_to_pending.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/migrate_apicalls_to_store_signer.rs
Changes the order of the migrations, and how the migration is achieved to simplify it.
The issue before this fix was:
The 3->4 migration drains the ThresholdSignature data storage, and inserts the PendingApiCalls storage. When we are draining from ThresholdSignatureData, we are decoding into the new ApiCall type (note the lack of an old ApiCall) type. 
This now passes try-runtime on mainnet and perseverance. Given the migration has already occurred on sisyphos, there's no need to worry about fixing it. After this is applied to persa and mainnet the storage will be at the same version and correct, so they will be consistent.
> fix: api call migrations

- api/lib/src/lib.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/add_broker_fee_to_ccm.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/liquidity.rs
- state-chain/traits/src/mocks/ccm_handler.rs
- state-chain/traits/src/mocks/deposit_handler.rs
- state-chain/traits/src/mocks/swap_deposit_handler.rs
Closes: PRO-1553
See Linear description.
Changes are potentially engine-breaking (event update) which is why it would be good to include this in 1.5.1
> fix: use encoded address for refund_address in events

- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/add_refund_params.rs
Release 1.5.1 has ingress-egress pallet at version 12, so the upgrade was failing, since the storage on-chain was 12, and the one in the new runtime was 11 which is lower.
> fix: pallet versions should match release + bump old dylib version to 1.5.1

- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-environment/src/tests.rs
Closes: PRO-1533
Added a new Governance Extrinsic that recovers used DurableNonce.
| Nonce status  | Hash is Some()         | Hash is None              |
| -------------- | -------------------- | --------------------- |
| Unavailable     | Reset to given Hash | Reset with original hash |
| Available | Update to new Hash | Return Error |
The given Nonce account must be either Available or Unavailable (i.e. New Nonce accounts are not accepted).
> feat: Governance extrinsic to recover Solana Durable Nonces

- state-chain/cf-integration-tests/src/genesis.rs
- state-chain/pallets/cf-reputation/src/lib.rs
- state-chain/pallets/cf-reputation/src/tests.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/qualify_node.rs
Fixes some issues I noticed while reviewing #5062. (Not strictly related to the PR itself, but still..)
1. The implementation of QualifyNode::filter_unqualified was wrong. Fortunately it was also unused (another mistake). 
2. We implemented the reputation-based qualification using is_qualified and the (buggy) default impl of filter_unqualified. The implementation using is_qualified is very ewxpensive (storage iteration over all validators for each validator, so n^2 storage reads).
I think the reason is wasn't noticed it probably that (a) it wasn't actually used (it should have been!) and (b) the naming was confusing.
I changed the name and made sure it's used when filtering backup validators.
I also created an explicit struct for the heartbeat-based qualification rather than using the …
> fix: qualify nodes based on reputation

- api/lib/src/lib.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/deposit_handler.rs
- state-chain/traits/src/mocks/swap_request_api.rs
- state-chain/traits/src/swapping.rs
Cherry pick of changes from #5135
> fix: use encoded addresses in refund params for events

- engine/src/sol/rpc.rs
- engine/src/witness/sol/nonce_witnessing.rs
- engine/src/witness/sol/sol_deposits.rs
We shouldn't be making external calls within unit tests as it introduces an external dependency to our unit tests. These can be left in the repo for easier testing though, as this has proven useful in the past.
> chore: disable external RPC tests

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/mock_btc.rs
- state-chain/pallets/cf-ingress-egress/src/mock_eth.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1547
Figured this was easy enough to get in before 1.6.
> fix: allow unswept funds to be used in boost

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
This fixes an issue with genesis that was preventing benchmarks from running. 
Also removed an unused event. 
See commits.
> chore: allow benchmarks to run

- bouncer/shared/broker_fee_collection.ts
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/primitives/src/lib.rs
- state-chain/traits/src/liquidity.rs
Closes: PRO-1540 and PRO-1483
The PR is indended to be reviewed by individual commits
- Broker fee now behaves exactly like network fee, charged at the same time (once we have intermediate amount) and in USDC.
- Moved `broker_fee` field from `SwapRequested` to `SwapExecuted` (FYI @zoheb391 and @acdibble). Don't think there are any other implications for the product, other than brokers noticing that only their USDC balance is changing.
- Updated tests; `swap_broker_fee_subtracted_from_swap_amount` was mostly a duplicate so I merged it with `expect_earned_fees_to_be_recorded`.
- Also, as discussed, combined `Ccm` and `Regular` variants from SwapRequestState into `UserSwap`. Didn't really result in code deduplication, but at least …
> Feat: charging broker fee per chunk and in USDC

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
Note: Targeting other swapping event PR to avoid conflicts.
Closes: PRO-1549
As dicussed (a while back), adding these parameters to `SwapRequested`.
> feat: add fok and dca params to SwapRequested event

- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/traits/src/swapping.rs
Closes: PRO-1597
Made `CcmDepositMetadata` generic so we can encode the address inside of it when outputting it in the swap requested event and the ccm failed event.
> feat: use encoded address in ccm deposit metadata in events

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/node/src/chain_spec.rs
- state-chain/pallets/cf-chain-tracking/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/solana_integration.rs
We want chain tracking events for solana
> feat: solana chain tracking events

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-ingress-egress-tracker/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- engine/src/elections.rs
- engine/src/retrier.rs
- engine/src/sol/retry_rpc.rs
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-elections/src/vote_storage/composite.rs
- state-chain/runtime/Cargo.toml
Minor hotfixes for the 1.6 release:
- downgrade error severity to reduce log spam
- increase the sol rpc timeout to 4 secs
> fix: downgrade log message severity for voting / retrier

- state-chain/node/package/berghain/chainflip-rpc-node.service
- state-chain/node/package/perseverance/chainflip-rpc-node.service
- state-chain/node/package/sisyphos/chainflip-rpc-node.service
Companion docker compose change: https://github.com/chainflip-io/chainflip-mainnet-apis/pull/5
The RPC nodes need to serve a lot of requests, so we can default the max runtime cache instances to the max for RPC nodes.
> chore: set max wasm instances for rpc nodes

- engine/src/witness/sol.rs
- engine/src/witness/sol/egress_witnessing.rs
- engine/src/witness/sol/fee_tracking.rs
- engine/src/witness/sol/nonce_witnessing.rs
This is a refactor / tidy up I did as I was debugging other issues. 
Some minor changes to behaviour, specifically these two case:
- when the rpc returns no priority fees -> now we return a default value MIN_PRIORITIZATION_FEE
- when the rpc returns no new durable nonce -> now we return the *old* nonce instead of erroring, and the impl of the `Change` electoral system handles the rest.
Details from the commit message:
- move implementation details into their own modules.
- make impls return Option instead of Vec and take single arg where appropriate
- remove unused data and assertions (slot, signature comparison etc)
- Handle case when there are no Prio Fees (add MIN_PRIORITIZATION_FEE)
- Durable Nonce default to old nonce if the new one isn't witnessed (election logic handles this).
> chore: tidy up solana vote impls

- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-lp/src/mock.rs
- state-chain/primitives/src/chains/assets.rs
- state-chain/traits/src/mocks/balance_api.rs
- utilities/src/with_std/rpc.rs
This makes the fn infallible, and prevents some strange pre/post runtime upgrade effects.
This is a cherry pick of #5218 (release/1.5)
Also needs to be picked to release/1.6
> fix: change try_from_iter into from_iter_or_default

- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
Tiny change to prevent some unlikely (and consequence-free) runtime error cases to be hit.
> fix: only call monotonic median hook if state is updated.

- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-elections/src/electoral_system.rs
- state-chain/pallets/cf-elections/src/electoral_systems.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mock.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/mock.rs
- state-chain/pallets/cf-elections/src/tests.rs
- state-chain/test-utilities/src/lib.rs
- state-chain/test-utilities/src/rich_test_externalities.rs
This includes a mock for the ElectoralSystem trait, and some initial tests of the consensus transitions when votes are added / ignored / deleted.
It's still incomplete - the next step would be to implement a mock of the VoteStorage trait and then `generate_vote_properties`.
> feat: elections pallet tests

- api/bin/chainflip-lp-api/src/main.rs
- state-chain/pallets/cf-pools/src/lib.rs
Closes: PRO-1605
Updated lp api cancel_all_orders to use cf_available_pools to query for the available pools instead of looping through all the assets and checking if the fees are set (makes thing more readable and understandable, that's one of the main reason we added cf_available_pools)
> LP API cancel_all_orders use cf_available_pools

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
Closes: PRO-1628
Fixed a bug where `CcmFailed` event is erased due to storage rollback
> fix: CcmFailed event erased due to storage rollback

- engine/src/sol/retry_rpc.rs
- state-chain/runtime/src/lib.rs
> fix: decrease broadcast timeout constants for sol and arb

- state-chain/chains/src/arb/api.rs
- state-chain/chains/src/btc/api.rs
- state-chain/chains/src/dot/api.rs
- state-chain/chains/src/eth/api.rs
- state-chain/chains/src/lib.rs
- state-chain/chains/src/sol/api.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-funding/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/traits/src/mocks/account_role_registry.rs
- state-chain/traits/src/mocks/api_call.rs
Closes: PRO-1617
Cleaned up strings used in DispatchError::Others. Refactored them into named errors if appropriate.
Removed deprecated extrinsics.
> chore: Cleanup DispatchError that contains strings

- .github/workflows/ci-development.yml
- engine/src/state_chain_observer/sc_observer.rs
- state-chain/cf-integration-tests/Cargo.toml
- state-chain/cf-integration-tests/src/lib.rs
- state-chain/cf-integration-tests/src/migrations.rs
- state-chain/cf-integration-tests/src/migrations/serialize_solana_broadcast.rs
- state-chain/cfe-events/src/tests.rs
- state-chain/chains/src/sol.rs
- state-chain/chains/src/sol/api.rs
- state-chain/chains/src/sol/benchmarking.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-cfe-interface/src/migrations.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations.rs
- state-chain/runtime/src/migrations/serialize_solana_broadcast.rs
Closes: PRO-1634
Use serialized data as the transaction passed to the engine instead of the regular transaction. The regular transaction is quite annoying/difficult to serialize into the raw transaction in case it needs to be broadcasted manually
> chore: solana serialize broadcast data

- engine/src/state_chain_observer/client.rs
Closes: PRO-1608
Currently, submitting a new CFE version might silently fail. We could not reproduce the exact failure conditions, but to safeguard against such an accidental failure we now do the following:
After submitting a new version, we get the actual (hopefully new) version number from storage to check whether our submission was successful. If it was not, we retry up to 10 times. We also retry if we get explicit errors during submission.
> Handle CFE version submission sometimes silently failing.

- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/tests.rs
Closes: PRO-1063
In set_range_order, if the input asset (size) is > 0 but the resultant liquidity change is 0, an error is returned.
> fix: set_range_order now returns an error if no position is created

- .zepter.yaml
Closes: PRO-1474
Zepter is a tool that helps make sure cargo features are applied/propagated correctly. 
This PR just contains the default zepter config. 
To run it, you need to install zepter:
`cargo install zepter -f --locked`
Then `zepter check` to check and `zepter` to fix the issues.
For now I didn't include the applied changes - we will apply them *after* the next polkadot sdk update to avoid additional merge conflicts.
> feat: support use of zepter for feature checks

- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/test-utilities/src/rich_test_externalities.rs
Part of: PRO-989
During #5270 I noticed that it would be nice to have a test utility function which works like `then_execute_with`, but instead of requiring the user to forward or construct a new context it simply retains the old one.
> chore: rename `inspect_storage` to `then_execute_with_keep_context`.

- state-chain/pallets/cf-elections/src/electoral_system.rs
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/change.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/egress_success.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mock.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/change.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/utils.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
Part of: PRO-1645
We always want to supply all votes to check_consensus, to allow us to take action on particular validator ids who have *not* voted - not just on those who have voted.
> refactor: always supply all votes to ElectoralSystem::check_consensus

- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/node/src/chain_spec.rs
- state-chain/pallets/cf-broadcast/src/benchmarking.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-broadcast/src/migrations.rs
- state-chain/pallets/cf-broadcast/src/migrations/initialize_broadcast_timeout_storage.rs
- state-chain/pallets/cf-broadcast/src/migrations/migrate_timeouts.rs
- state-chain/pallets/cf-broadcast/src/mock.rs
- state-chain/pallets/cf-broadcast/src/tests.rs
- state-chain/runtime/src/constants.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/mocks/block_height_provider.rs
Closes: PRO-989
This change involves the following (in the broadcast pallet):
- `BroadcastTimeout` is now specified in `ChainBlockNumberFor<T,I>`
- `Timeouts` is now specified in `ChainBlockNumberFor<T,I>`
- A new constant `SafeModeBlockMarginForTargetChain`, also in `ChainBlockNumberFor<T,I>` is introduced since the previously used `SafeModeBlockMargin` stays denominated in `BlockNumberFor<T>` for other purposes.
- For convenience, introduction of block time constants for all target chains.
- Update the migration introduced in #5258 since it hasn't been released yet.
If this PR includes non-breaking changes, select the `non-breaking` label. On merge, CI will automatically cherry-pick the commit to a PR against the release …
> Denote broadcast timeout in target chain blocks.

- Cargo.lock
- state-chain/custom-rpc/Cargo.toml
- state-chain/custom-rpc/src/lib.rs
- state-chain/node/src/service.rs
- state-chain/runtime/src/monitoring_apis.rs
- state-chain/runtime/src/runtime_apis.rs
Updated our RPC interface in `custom-rpc` crate to jsonrpsee-0.23.2
Major changes to how subscriptions are streamed.
Major changes to all error types.
> Update RPC interface to jsonrpsee-0.23.2

- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/egress_success.rs
Closes: PRO-1592
This is close to a copy paste of the Change tests. Just renamed some things and modified to the finalise test to better reflect the behaviour which is slightly different to the Change system.
Deliberately not deduplicating anything here because the Change electoral system will eventually become a more specific nonce witnessing electoral system, which is WIP now.
> test: egress success tests

- Cargo.lock
- engine/Cargo.toml
- engine/src/dot/http_rpc.rs
- engine/src/settings.rs
Closes: PRO-1620
Currently the polkadot http rpc client uses jsonrpsee's HttpClient. Unfortunately, since we are on version 0.16 of jsonrpsee, this client has the rule that a port must always be given, even if it should be the default port. Later versions of jsonrpsee forgo this requirement.
To make sure that the user configures a valid http endpoint for polkadot, we currently check that the url contains a port. Unfortunately the checking logic uses a regex and accepts urls such as `https://endpoint/path:port` as valid, even though it shouldn't.
It also seems that the Solana configuration logic mistakenly was copied from Polkadot since it calls the same validation logic, without there being a need for that.
This PR does multiple …
> PRO-1620: Ensure that default port is used if none is given in configuration

- Cargo.lock
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-cli/src/main.rs
Closes: PRO-1275
The code for printing the redemption amount in the chainflip-cli is printing two numbers: amount in FLIP and amount in Flipperinos. The latter is the authoritative one and is computed from the user input via rounding to 6 decimal places.
Previously the amount in FLIP was simply the user-entered amount and thus did not always match up with the flipperino amount. This change recomputes a decimal FLIP-valued representation of the authoritative flipperino amount when displaying the redemption amount. 
> fix: Redemption amount printed not consistent in rounding

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/monitoring.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/monitoring_apis.rs
Closes: PRO-1658
Add solana monitoring data to monitoring rpc:
- Available nonces/Unavailable nonces
- Broadcaster.incomingKeyAndBroadcastId() -> This is missing for all the chains
- Plus the signature of the transaction for solana -> we need to check it didn't revert  
- Solana aggKey
- SolanaBroadcaster.currentOnChainKey -> Sol funds held here
> feat: add solana monitoring data

- state-chain/cf-integration-tests/src/solana.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/primitives/src/lib.rs
- state-chain/traits/src/mocks/swap_request_api.rs
Closes: PRO-1548
Previously, `SwapId` and `SwapRequestId` were both type aliases for `u64`, making them easy to accidentally misuse. This PR changes them to be struct wrappers around `u64`, generated with a new macro, `define_wrapper_type`.
The macro implements `From<$inner>` for the wrapper struct, such that strongly-typed ids can now be created by, e.g., `my_u64.into()`. It also implements the `Deref` and `DerefMut` traits to access the underlying `u64` value.
One particular problem during implementation was that multiple test files in the swapping pallet use macros such as `assert_event_sequence` which expect patterns to be passed in. Previously, literal values for both SwapId and SwapRequestId were used in such calls. In …
> refactor: Strongly-typed identifiers for SwapId/SwapRequestId

- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- state-chain/pallets/cf-asset-balances/src/lib.rs
Version bump had not yet been pulled across to main from release - meaning try-runtime/migrations would fail due to version mismatch.
See: ea83d71bf70b37ce0224160255b89ee710d3c359
> chore: bump asset-balances to match release

- Cargo.lock
- engine/src/elections/voter_api.rs
- engine/src/witness/sol.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/node/src/chain_spec/common.rs
- state-chain/pallets/cf-elections/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/change.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/egress_success.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/vote_storage/composite.rs
- state-chain/pallets/cf-elections/src/vote_storage/individual/composite.rs
- state-chain/runtime/src/chainflip/offences.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations.rs
- state-chain/runtime/src/migrations/add_liveness_electoral_system_solana.rs
Closes: PRO-1645
Generic liveness electoral system that could be used for all chains. It works by asking the engines to return the block hash for a particular block number in a range from the current block height to 100 blocks below the current block height - this is to provide some variation on slower chains such as bitcoin. If we were to use the chain height and we're doing liveness every minute, then we would be returning the same value which is not ideal.
We punish any nodes who:
a) voted for the non-consensus value
b) did not vote when there was a consensus value
We don't punish nodes in any other scenarios such as:
- no one voted
- votes but no consensus
The offence contains the `ForeignChain` to identify it against other …
> feat: liveness electoral system

- CHANGELOG.md
- engine/src/witness/sol/sol_deposits.rs
Cherry pick from release/1.6
Closes PRO-1683
> fix: ensure unused sol deposit channels are closed

- engine/src/retrier.rs
Closes: PRO-1685
Should fix flakiness for this timing based test - was pretty uncommon before, but this should make it even more uncommon.
> fix: increase init timeout for backup test

- state-chain/pallets/cf-funding/src/lib.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/traits/src/lib.rs
Closes: PRO-1721
This is more reliable than using HistoricalAuthorities because the latter is not cleared when an epoch expires.
Preivously is was possible for a validator to be considered active for an expired epoch if the epochs were expired out-of-order (see updated test case).
> fix: keyholder check should use `HistoricalActiveEpochs`

- bouncer/commands/run_test.ts
- bouncer/commands/setup_vaults.ts
- bouncer/package.json
- bouncer/pnpm-lock.yaml
- bouncer/shared/polkadot_utils.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/substrate.ts
- bouncer/tests/DCA_test.ts
- bouncer/tests/all_concurrent_tests.ts
- bouncer/tests/request_swap_deposit_address_with_affiliates.ts
- bouncer/tsconfig.json
Closes: WEB-1499
To enable integrators to more securely submit extrinsics to open swap deposit channels outside of the broker API, I created a helper that will go in the SDK that will return the parameters properly formatted for them, ready for submission with the Polkadot API.
This adds a test that ensures that the parameters that are generated by the utility submit the extrinsic to the state chain successfully and open channels with the expected attributes.
Also there are some type fixes (I can't help myself).
> test(bouncer): add test for new utility

- localnet/common.sh
Ran into this when trying to start a new network. The script shouldn't exit if the file we are trying to remove already doesn't exit, and `-f` achieves this.
> fix: don't exit if we can't remove a file that already doesn't exist

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-2.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-3.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls-4.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/snapshots/chainflip_ingress_egress_tracker__witnessing__state_chain__tests__handle_deposit_calls.snap
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
> feat: expose deposit transaction hash from ingress-egress-tracker

- CHANGELOG.md
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-ingress-egress-tracker/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/runtime/Cargo.toml
This is a cherry pick from main. 
Some alterations were made to the original commit to ensure this is a non-breaking change:
- Instead of adding a new variant to the PalletConfigUpdate enum, replaced MaximumSwapAmount. This ensures that encoding remains compatible. 
- No event is emitted when the min chunk size is updated.
- Some test cases were modified/removed (ie. those relating to the maaximum swap amount.
The main consequence is that we can't set a MaximumSwapAmount, but I think this is fine since we don't use it any more (can probably be removed in a future release). 
(TODO: version bumps, changelog etc.)
> [DO NOT SQUASH] Release candidate 1.6.9

- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/delete_old_epoch_data.rs
- state-chain/pallets/cf-validator/src/tests.rs
Closes: PRO-1318
Currently some epoch-indexed storage values are not deleted when their epoch is expiring. This PR adds logic to delete these storage values.
This includes:
- Clean up of AuthorityIndex, HistoricalAuthorities, HistoricalBonds
- Delete values for every newly expired epoch in `expire_epoch`
- Add migration for deleting values for *all* previously expired epochs
- Tests for migration and epoch expiry
> chore: Prune historical values in Validator pallet

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- engine/src/witness/arb.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/deposits.rs
- engine/src/witness/btc/smart_contract.rs
- engine/src/witness/eth.rs
- engine/src/witness/evm/evm_deposits.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/chains/src/benchmarking_value.rs
- state-chain/chains/src/btc.rs
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
Closes: PRO-1695, PRO-1644, PRO-1643
- `OnDeposit::on_deposit_made` no longer takes `DepositChannel` as a parameter (in case of smart contract swaps, there is no channel). It was only used by bitcoin to pass deposit address. Instead, now engines submit deposit address as part of `DepositDetails` (next to the existing `UtxoId`).
- Added `deposit_details` as a parameter to `contract_swap_request`.
- Added FoK/DCA/Boost parameters to `contract_swap_request`. FoK and DCA should already by handled correctly on the SC side, however Boost is currently ignored as it will require some potentially non-trivial refactoring. For now the engine uses default parameters for these in case of EVM smart contracts (i.e. they are still effectively disabled).
- On every BTC block the engine checks contract …
> feat: witnessing btc smart contract swaps

- localnet/create.sh
- localnet/recreate.sh
Added a "-d" option to the recreate localnet script that will cause it to use defaults if no settings file is found.
> chore: localnet recreate script can use defaults

- api/bin/chainflip-broker-api/src/main.rs
- api/lib/src/lib.rs
Small PR to address the consistency issues in the broker API that [ crumps raised](https://github.com/chainflip-io/chainflip-backend/pull/5329#issuecomment-2427975326)
> chore: more consistent params in Broker API

- engine/src/witness/sol/nonce_witnessing.rs
- engine/src/witness/sol/sol_deposits.rs
Adding data to error logging in the Engine for account data decoding.
> chore: add engine account_info logging

- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/lib.rs
Add logic to btc_utxos_balance rpc
Closes: PRO-1716, PRO-1739
> bug: change_utxo not always present

- .github/workflows/_20_build.yml
- .github/workflows/_40_post_check.yml
- .github/workflows/ci-development.yml
- .github/workflows/ci-main-merge-queue.yml
- .github/workflows/release-berghain.yml
- .github/workflows/release-sisyphos.yml
- bouncer/shared/upgrade_network.ts
- engine-runner-bin/Cargo.toml
- engine-runner-bin/build.rs
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
Closes: PRO-1622
When the is_mainnet flag is `true` on the build job, the engine-runner will now download from the pgks.chainflip.io - which contain only the binaries built for mainnet. It will also verify the signature of these dylibs to ensure that the chainflip releaser has released them.
> feat: engine-runner verifies gpg signature of old dylib when downloaded

- state-chain/custom-rpc/src/order_fills.rs
chore: more consistent params
This was causing lp apis to crash, we avoid it by saturating the calculation.
> fix: ignore dust underflows in order fills rpc

- state-chain/cf-integration-tests/src/authorities.rs
- state-chain/cf-integration-tests/src/broadcasting.rs
- state-chain/cf-integration-tests/src/funding.rs
- state-chain/cf-integration-tests/src/genesis.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/cf-integration-tests/src/network.rs
- state-chain/cf-integration-tests/src/new_epoch.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/cf-integration-tests/src/witnessing.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/monitoring.rs
- state-chain/node/src/chain_spec.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/rename_blocks_per_epoch.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/monitoring_apis.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1613
- Changed the `expire_epoch` function to recursively expire all previous epochs that had not expired yet in chronological order. This should avoid the bug stated in the issue.
- Added a test to make sure it expires as expected.
- Renamed `BlocksPerEpoch` -> `EpochDuration`
- Added a migration and migration test for the rename.
I think this is non breaking, i'll let you tag it @dandanlen
> fix: expire all previous epochs

- state-chain/pallets/cf-elections/src/electoral_system.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mock.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_change.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_change.rs
- state-chain/pallets/cf-elections/src/lib.rs
Closes: PRO-1757
`is_vote_valid` was only used once, and was used erroneously. Plus, if a single vote within a group is invalid then the whole extrinsic vails, effectively invalidating all the votes. We have is_vote_needed to prevent engines from submitting too many votes. So have removed it, which simplifies things too. No need to hash the data at all, we can compare the values directly in check_consensus.
> fix: remove is_vote_valid

- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/tests.rs
It's not the ElectoralSystemStatus at all... is a recipe for confusion, so renaming.
> chore: rename ElectoralSystemStatus -> ElectionPalletStatus

- engine/src/elections.rs
Closes: PRO-1614
It turns out the ticket was incorrect, the error occurs when a validator *becomes* an authority, not when they drop out. There's not really an issue here, it's just because the engines only "find out" they are an authority via the electoral_data rpc, by design, so there's no engine logic required to handle epochs etc. So, just making the error message clearer and adding a clarifying comment.
> chore: better not contributing error message

- state-chain/runtime/src/lib.rs
We sweep for lp_account_info but not for the free balances
> fix: always sweep on RPC free balance

- api/bin/chainflip-lp-api/src/main.rs
- state-chain/custom-rpc/src/lib.rs
Fixes the return types in rpc subscriptions. 
Used to be wrapped in an additional (unexpected) Result.
> fix: rpc subscription return types

- engine/src/sol/retry_rpc.rs
Closes: PRO-1762
In some cases egress witnessing can fail because the Solana nodes don't keep the transactions in a local cache. This isn't so bad, it just means we might retry a bit more than necessary, and also that we display the status as "pending". This should resolve it though.
> fix: retry with search history enabled after some attempts

- .github/workflows/ci-cherry-pick.yml
We can't use the old versions anymore. So using these versions which we use everywhere else.
> chore: bump actions versions

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/btc.rs
- engine/src/state_chain_observer/client/storage_api.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/deposits.rs
- engine/src/witness/common/chunked_chain_source/chunked_by_vault.rs
- engine/src/witness/common/chunked_chain_source/chunked_by_vault/private_deposit_channels.rs
- state-chain/pallets/cf-swapping/src/lib.rs
Closes: PRO-1749
- Added a new adapter (similar to the existing `deposit_addresses`) which monitors the new storage for private channels `BrokerPrivateBtcChannels` on every block.
- `btc_deposits` now has access to private channel ids which it uses to derive deposit addresses (based on the current and previous epoch keys) and checks transactions for vault deposits into them (similarly to how it is already done for channel_id = 0 aka "change address").
- Based on #5361, will need to rebase after that one is merged.
- Do we still want to allow vault deposits directly into the "change address" skipping the broker?
> Feat: Private Broker Channel Witnessing

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-broker-api/src/main.rs
- api/lib/src/lib.rs
- state-chain/custom-rpc/Cargo.toml
- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1706
In this PR all changes to the broker API which are required for broker level screening are going to be merged. Currently based on @Janislav 's PR ~~(https://github.com/chainflip-io/chainflip-backend/pull/5310)~~ (https://github.com/chainflip-io/chainflip-backend/pull/5332) which implements the extrinsic for rejecting transactions.
Once that PR is merged, rebase this on main.
This PR includes the following changes:
- Add new methods to `custom_rpc`:
- `cf_get_tainted_transaction_events` which gets all events (for a given block) related with tainted transactions occuring in the ingress egress pallet.
- `cf_get_open_deposit_channels` which returns all open channel addresses for a given account id.
- These methods …
> feat: update custom_rpc, runtime_api and broker api for broker level screening

- api/lib/src/lib.rs
- engine/src/witness/btc/vault_swaps.rs
- state-chain/chains/src/btc/vault_swap_encoding.rs
Closes: PRO-1759, PRO-1770
- Added version byte (currently set to 0); decoding will fail if it is not 0
- Added broker fee field (as a u8)
- Added affiliate fees. Supports up to 2 affiliates. Each entry takes 2 bytes (1 byte for affiliate idx, and another byte for their fee)
I briefly considered inlining `SharedCfParameters` (since we are not going to share them after all), but it seemed helpful to have a separate struct for fields that we don't want to decode independently (unlike the version, output asset and address), so I left it for now.
> feat: add version and affiliates to UTXO encoding

- bouncer/shared/try_runtime_upgrade.ts
We should check for idempotency to be safe against accidentally leaving migrations in, which could result in a migration being run twice, which could corrupt state.
> chore: enable idempotency checks on try-runtime for upgrade-test

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/monitoring.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/monitoring_apis.rs
> feat: runtime API versioning for monitoring API

- state-chain/custom-rpc/src/monitoring.rs
Use correct trait object to access the runtime api version.
> fix: use correct trait object

- state-chain/custom-rpc/src/lib.rs
> fix: rpc error message displaying as "{error}" (#5399)

- state-chain/custom-rpc/src/lib.rs
Simple fix. now the rpc's show the error message:
`{"jsonrpc":"2.0","error":{"code":-32603,"message":"DispatchError: PoolDoesNotExist"},"id":1}%   `
> fix: rpc error message displaying as "{error}"

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
Added here #5394 to deal with unpredictable block times on testnets. In particular bitcoin testnet block times can move extremely fast at times.
> feat: add ability to configure DepositChannelLifetime via governance

- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1708
Added runtime versioning for `cf_pool_simulate_swap` so that cf_pool_swap_rate_v3 will still work against the old runtime.
> support cf_pool_swap_rate_v3 with old runtime

- .github/workflows/ci-development.yml
- engine/src/elections.rs
- engine/src/elections/voter_api.rs
- engine/src/state_chain_observer/client/electoral_api.rs
- engine/src/witness/sol.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-elections/src/electoral_system.rs
- state-chain/pallets/cf-elections/src/electoral_system_runner.rs
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/egress_success.rs
- state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mock.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_change.rs
- state-chain/pallets/cf-elections/src/electoral_systems/monotonic_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/mock.rs
- state-chain/pallets/cf-elections/src/tests.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1675
Rather than have a composite "electoral system" impl Electoral system, we now have a new `ElectoralSystemRunner` trait for the composite, which is then used by the elections pallet directly. This removes some prior hacks that were required to get the traits to work for both a single and composite electoral system.
It also makes it easier to write migration utilities in the future, since storage will *always* be enum wrapped, as a composite, and we don't need to consider the individual electoral system case.
As a consequence there were other simplifications that fell out:
- Simpler Composite electoral system macro
- Some trait methods now have simpler signatures (e.g. no Result necessary in some cases, fewer …
> refactor: split out composite electoral system trait

- localnet/build_and_run.sh
Simple script to:  cargo build -> recreate localnet -> setup for test. I have been doing this exact chain of commands for a while now when developing. I think others might too, so this is just a shortcut for us.
Usage: `./localnet/build_and_run.sh`
> chore: build and run script for localnet

- api/bin/chainflip-broker-api/src/main.rs
- api/lib/src/lib.rs
- bouncer/tests/all_concurrent_tests.ts
- bouncer/tests/btc_vault_swap.ts
- engine/src/state_chain_observer/client/base_rpc_api.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1752
- Added RPC's to the broker to open and close private btc channels.
- The Btc vault swap now opens a private channel
- Added the btc vault swap bouncer test to the concurrent tests
> feat: Btc vault swap bouncer test can open a private channel

- api/lib/src/lib.rs
Creating the util to reduce the extra duplication that was introduced in #5410
> refactor: deduplicate event finding logic

- state-chain/cf-integration-tests/src/solana.rs
- state-chain/chains/src/address.rs
- state-chain/chains/src/sol.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
Added integration test for the recycling.
Closes: PRO-1684
Allow deposit channel to recycle for Solana
Added integration test.
> feat: Deposit channel recycling for Solana

- localnet/docker-compose.yml
Updates the localnet chainspec for polkadot to the latest version 1.3.4
> update localnet polkadot node to version 1.3.4

- engine/src/witness/sol.rs
According to the docs when not passing those parameters (Rust's None) it doesn't default to those. Setting them prevents the call to get the rewards and more importantly the transaction data which we don't need.
> chore: reduce data needed for sol get block

- Cargo.lock
- Cargo.toml
- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1793
Replica of https://github.com/chainflip-io/chainflip-backend/pull/5406 which was merged in 1.7, with the addition of using obake to create struct versioning.
This PR is here just to have an example in the codebase as a reference implementation.
> feat: Custom runtime api versioning + struct versioning

- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/monotonic_median.rs
Allows us to avoid duplicating the "hook_called" etc. I'm also going to need to this to, for example, check how many elections are open at any one time, and would rather not write a hook specific to the number of times I expect, as it will change throughout the test.
> feat: allow for providing params to ElectoralSystem test checks

- bouncer/shared/try_runtime_upgrade.ts
- state-chain/TROUBLESHOOTING.md
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/mock.rs
Closes: PRO-1726
This PR adds try-state hook checks to the Elections pallet. For these hooks to be fired up, the try-runtime-cli must be called with --checks all (or at- least try-state). The ci and troubleshooting guide were updated accordingly.
This PR implemented try-state hook only for the Elections pallet, but it was agreed that another issue will be raised to handle try-state hooks in a more generic way and enable it for all other pallets.
> feat: try-state hook for elections pallet

- state-chain/node/src/chain_spec/testnet.rs
- state-chain/pallets/cf-flip/src/lib.rs
- state-chain/pallets/cf-flip/src/tests.rs
- state-chain/pallets/cf-swapping/src/benchmarking.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/mock.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/weights.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks.rs
- state-chain/traits/src/mocks/bonding.rs
Closes: PRO-1761
- Bond a broker by a 100 FLIP if he wants to open a private broker channel
- Added an extrinsic to update the required bond
- Extended the Flip pallet to bond an account under the condition of having enough liquid balance in his account
- Added a benchmark and tests
- Increased the amount of FLIP for BROKER accounts in the test net to have enough funds in the bouncer tests
> Feature: bond brokers for private channels

- bouncer/commands/create_raw_btc_tx.ts
- bouncer/shared/send_btc.ts
- bouncer/tests/btc_vault_swap.ts
- bouncer/tests/lp_api_test.ts
Closes: PRO-1832
Using the btc client mutex around selecting inputs and sending transaction to avoid double spending error.
> fix: bouncer btc client mutex for vault swaps

- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
I hit an issue when writing a check like so on my PR:
```rust
number_of_open_elections_is(_pre, post, n: ElectionCount) {
assert_eq!(post.unsynchronised_state.open_elections, n, "Number of open elections should be {}", n);
},
```
and it was because without explicitly comparing the whole post-state as is currently done on some Checks, it can't infer the rest of the state. Fixing this by explicitly providing the type in the closure, writing checks should remain just as clean.
> chore: improve ES Check type inference

- state-chain/pallets/cf-funding/src/lib.rs
- state-chain/pallets/cf-funding/src/tests.rs
Closes: PRO-1821
* Added a check that makes sure we are not left with the situation where a restricted address is below MINIMUM_FUNDING.
* This broke some other tests which were updated to take the new checks into consideration
> feat: check all restricted balances are above minimum when redeeming

- state-chain/pallets/cf-elections/src/electoral_systems/tests/solana_vault_swap_accounts.rs
Uses new ability introduced in #5441 for the solana vault swap elections tests.
> chore: tidy solana vault swap test hooks

- state-chain/pallets/cf-vaults/src/lib.rs
- state-chain/pallets/cf-vaults/src/tests.rs
- state-chain/runtime/src/chainflip/epoch_transition.rs
Closes: PRO-1699
* Implemented cleaning VaultStartBlockNumbers upon epoch expiry
* It's implemented in a simple way where it removes all epochs <= expired_epoch. This means that it would be expensive the first time we run this.
> feat: cleanup VaultStartBlockNumbers upon epoch expiry

- state-chain/pallets/cf-vaults/src/lib.rs
The docs here: https://paritytech.github.io/polkadot-sdk/master/frame_support/storage/trait.IterableStorageMap.html#tymethod.iter_keys say you shouldn't remove when iterating, so even though it's probably ok, best not to.
> fix: don't remove while iterating

- state-chain/amm/src/common.rs
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/traits/src/lib.rs
Closes: PRO-1581
Added unit tests for the delta based ingress electoral system.
Improved the mock system for the tests.
Fixed a bug where on revert, on_finalize will cause underflow panic 
Log a warning on ingress reverts
> test: Solana's delta-based-ingress electoral System

- api/lib/src/lib.rs
- bouncer/shared/send_btc.ts
- bouncer/tests/btc_vault_swap.ts
- engine/src/witness/btc/vault_swaps.rs
- state-chain/chains/src/btc/vault_swap_encoding.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1845
- Fixed a bug in the auto assigning of affiliate short id's in the broker api.
- Removed the op codes from the nulldata utxo.
- Renamed the `nulldata_utxo` -> `nulldata_payload` seems it's no longer a complete uxto.
> refactor: remove op codes from btc vault swap encoding

- engine-runner-bin/src/main.rs
Closes: PRO-1887
Given we never expect the engine to exit, when it does exit it should exit with a "1" exit code, so unix systems can interpret it as an error correctly.
> fix: return correct exit code on engine error

- Cargo.lock
> fix: downgrade parity-scale-codec dependencies

- engine/src/dot/rpc.rs
- utilities/scale-json-event-logger/src/main.rs
Included in 1.7.4 release already: #5478
> fix: allow insecure connections with subxt

- state-chain/pallets/cf-asset-balances/src/tests.rs
- state-chain/pallets/cf-broadcast/src/tests.rs
- state-chain/pallets/cf-emissions/src/tests.rs
- state-chain/pallets/cf-environment/src/tests.rs
- state-chain/pallets/cf-flip/src/tests.rs
- state-chain/pallets/cf-funding/src/tests.rs
- state-chain/pallets/cf-governance/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/pallets/cf-ingress-egress/src/tests/screening.rs
- state-chain/pallets/cf-lp/src/tests.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/pallets/cf-threshold-signature/src/tests.rs
- state-chain/pallets/cf-tokenholder-governance/src/tests.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-vaults/src/tests.rs
- state-chain/pallets/cf-witnesser/src/tests.rs
Closes: PRO-1824
- Added `max_boost_fee_bps` field to both `DepositFinalised` and `DepositBoosted` events
- Added `broker_fees` field to the `SwapRequested` event FYI @niklasnatter 
- While updating tests, I noticed some tests used unnecessary annotations like `crate::Event::<Test, Instance1>` where `Event` would suffice, so I cleaned up the tests where this applies. This change is done in a separate commit.
> Feat: add boost_fee and broker_fees to events

- api/bin/chainflip-broker-api/src/main.rs
- state-chain/custom-rpc/src/lib.rs
Closes: PRO-1886
* Added cf_subscribe_transaction_screening_events to custom_rpc that uses the new finalized notification behavior
* Modified broker-api subscribe_transaction_screening_events to use the custom-rpc equivalent function
* Also, changed the logic slightly so that it returns an empty events vector if there are no events detected, making it consistent with other custom-rpc subscriptions
> refactor: move broker api subscription to custom-rpc

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__broker_serialization.snap
- state-chain/runtime/src/chainflip/address_derivation/btc.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1862
Adds the deposit address of a private broker channel to the response of cf_account_info.
> feat: Add private channel address to account info rpc

- api/bin/chainflip-lp-api/src/main.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/order_fills.rs
Closes: PRO-1764
* Implemented lp_get_order_fills for a certain block in custom-rpc.
* Modified the custom-rpc cf_subscribe_lp_order_fills to subscribe to the finalized block stream.
* Removed and refactored lp_api order-fills calls to use the custom-rpc equivalents. Logic is defined in only one place.
* Performed manual testing
> feat: move order fills api to custom rpc

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__broker_serialization.snap
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1884
Adds the associated affiliates of a broker account to the response of the cf_account_info rpc.
> feature: Added affiliates to cf_account_info rpc

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__boost_details_serialization.snap
- state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1778
- New storage item: `NetworkFeeDeductionFromBoostPercents` representing the % of boost fee to be taken as network fee. Its value is initially 0, and can be updated via `update_pallet_config` governance extrinsic.
- When a deposit is boosted, the full boost fee is "deducted" from the deposit, but we now apply network fee reduction when recording the amounts to be credited to boosters upon finalisation.
- When a boosted deposit is finalised, we add up all funds credited to boosters, and any non-zero excees amount is swaped into FLIP as network fee. (The swap request's type being NetworkFee takes care of the resulting flip being scheduled for burning later.)
- `DepositFinalised` (when action is `BoostersCredited`) now additionally exposes `network_fee_swap_request_id` (of …
> Feat: Network Fee from Boost

- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
This fixes an issue observed during the recent upgrade, when liquidity is low. Error messages were being erased due to the implementation of DispatchError.
> fix: expose error detail when swap simulation fails

- .github/workflows/_01_pre_check.yml
- .github/workflows/_10_test.yml
- .github/workflows/_11_coverage.yml
- .github/workflows/_20_build.yml
- .github/workflows/_25_package.yml
- .github/workflows/ci-benchmarks.yml
- ci/docker/development/rust-base.Dockerfile
> chore: update CI to new base image

- api/bin/chainflip-lp-api/src/main.rs
Closes: PRO-1897
Updated the LP-API cancel_orders_batch to accepts OrderId as string/hex as well 
> fix: lp_cancel_orders_batch to accepts OrderId as string/hex

- Cargo.lock
- Cargo.toml
- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1776
Removes deprecated V1 RPC for cf_pool_simulate_swap. Since this is only a runtime API that is called over cf_pool_swap_rate, there is no actual RPC that is changing. The only thing that is changing is the fact that calling the cf_pool_swap_rate on "old" blocks will potentially fail, but since this is not needed any more it should be fine to remove it.
> chore: removed cf_pool_simulate_swap_v1

- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1680
Removes the obsolete check for pending swaps during a runtime upgrade. 
> chore: Removed upgrade condition for pending swaps

- state-chain/amm/src/common.rs
Closes: PRO-1711
1. `fixed_point_to_power_as_fixed_point` now returns `None` (instead of panicking) whenever the result would overflow, to achieve which rewrote the algorithm in a more procedural style (which looks way simpler IMO).
2. To address the overflow/panic in `nth_root_of_integer_as_fixed_point` I initially tried saturating some values at `U256::MAX` where it made sense (like when computing the "error"), but I noticed that for some inputs while the panic no longer occurred, we were getting incorrect results, even after increasing the max number of iterations. My guess is that the algorithm isn't guaranteed to converge on the answer due to how "step" is computed (If I remember my math, we should be computing the first derivative in this case, but the derivative of nth root …
> Fix: pool orderbook panic

- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
Closes: PRO-1898
I added an optional field for the egress details so it's easy for Product to know if we are scheduling the egress or it's for the user to broadcast themselves if they want to.
Adding this field might be a breaking change for Product so I'll let them know.
> chore: unify fallback events

- state-chain/chains/src/sol.rs
- state-chain/chains/src/sol/api.rs
- state-chain/chains/src/sol/sol_tx_core.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/vault_swap.rs
- state-chain/runtime/src/runtime_apis.rs
Per discussion, made some improvements to the Solana version of Vault swap RPC call
* Solana vault swaps uses on-chain-key instead of aggkey
* Added a new SolInstructionRpc type that uses SolAddress so it serializes all addresses into bs58 instead of byte arrays.
> fix: vault swap - solana improvements

- bouncer/tests/btc_vault_swap.ts
- state-chain/runtime/src/constants.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1851
* Return `expires_at` field determining when the payload is considered expired.
* Only implemented for Bitcoin for now, Solana implementation should be straightforward when Solana vault swapping is in main
* Updated bouncer btc_vault_swap test to validate `expires_at`
> feat: add expires_at field to request swap parameter encoding

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/migrations.rs
- state-chain/pallets/cf-swapping/src/migrations/swap_and_swap_request_migration.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-1701
- New `MinimumNetworkFeePerChunk` storage item, set to 0 by default, but can be updated via governance extrinsic. In practice "min fee per chunk" should effectively be "min fee per swap request" since we also enforce min chunk size (which should be sufficiently large). I considered adding checks ensuring that we never update parameters such that this doesn't hold, but it is a bit tricky since chunk size is in target chain asset amount and we don't know the exchange rate... The best we can do it check it against the min chunk limit for USDC and rely on other limits being in line with that. However, I dicussed this with @kylezs and we agreed that this shouldn't really matter considering that the new min network fee will already be incorporated into the price estimation …
> feat: min network fee

- .github/workflows/_01_pre_check.yml
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- bouncer/tests/all_swaps.ts
- engine/src/witness/arb.rs
- engine/src/witness/btc/vault_swaps.rs
- engine/src/witness/eth.rs
- engine/src/witness/evm/vault.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
Closes: PRO-1906
- Catches decoding errors of cf-parameters
- Provides default parameters
- Handles the case if no refund parameters are available on the protocol side
Defaults values
If we can not decode the cf_parameters we use these default vaules:
- broker_fee = broker_account with 0 address, and 0 bps
- affilate_fees = Default / which should just be an empty Vector
- dca_parameters = None
- refund_params = None 
> feat: Support backwards compatible vault_swap_requests

- .github/workflows/ci-development.yml
- bouncer/package.json
- bouncer/pnpm-lock.yaml
- bouncer/shared/evm_vault_swap.ts
- bouncer/shared/send_evm.ts
- bouncer/shared/swapping.ts
- bouncer/tests/all_swaps.ts
- bouncer/tests/fill_or_kill.ts
- bouncer/tests/gaslimit_ccm.ts
- engine/src/evm/retry_rpc.rs
- state-chain/chains/src/arb.rs
- state-chain/chains/src/benchmarking_value.rs
- state-chain/chains/src/lib.rs
Increase allowed ccm length to 15k.
While testing with higher payloads I've encountered some issues:
- In localnet payloads bigger than several hundred bytes end up with gas limits higher than Arbitrum block gas limit so we need to limit the size. Pretty sure this is due to localnet settings, this won't happen in a real network.
- Vault swaps, particularly in Solana, run into issues due to transaction size limitations. I've added a the corresponding limitations under the `newVaultSwapCcmMetadata` function.
- Arbitrum gas proved extremely unreliable. While this is just a localnet issue, it made me rethink how estimations should be done. Part of the gas estimation that takes into account Arbitrum's gas limit variability should be …
> chore: increase ccm message max to 15k

- state-chain/cf-integration-tests/src/authorities.rs
- state-chain/cf-integration-tests/src/broadcasting.rs
- state-chain/cf-integration-tests/src/funding.rs
- state-chain/cf-integration-tests/src/genesis.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/cf-integration-tests/src/network.rs
- state-chain/cf-integration-tests/src/new_epoch.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/cf-integration-tests/src/witnessing.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/monitoring.rs
- state-chain/node/src/chain_spec.rs
- state-chain/pallets/cf-pools/src/migrations.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/rename_blocks_per_epoch.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/monitoring_apis.rs
- state-chain/runtime/src/runtime_apis.rs
~~TEMP: opening this PR to investigate recent issues.~~
Appears to be solved. There were a couple of issues:
- It looks like the migration was incorrect.
- Doing the expiry in the on_initialsed hook was causing the block to be filled up with expiry weight. Expiry has now been moved to the on_idle hook and only runs if there is enough remaining weight in the block.
> fix: expire previous epochs and rename epoch duration

- .github/workflows/ci-development.yml
- bouncer/shared/contract_interfaces.ts
- bouncer/shared/evm_vault_swap.ts
- bouncer/shared/fund_flip.ts
- bouncer/shared/perform_swap.ts
- bouncer/shared/sol_vault_swap.ts
- bouncer/shared/swapping.ts
- bouncer/shared/utils.ts
- bouncer/test_commands/legacy_vault_swap_test.ts
- bouncer/tests/all_concurrent_tests.ts
- bouncer/tests/all_swaps.ts
- bouncer/tests/btc_vault_swap.ts
- bouncer/tests/legacy_vault_swap.ts
- state-chain/runtime/src/chainflip/vault_swaps.rs
Closes: PRO-1912, PRO-1854
- Use broker APi for EVM vault swaps
- Add test for legacy vault swaps (undecodable cfParameters) to make sure it doesn't break backwards compatibility. This is to test the logic in #5514 .
- Add BTC Vault swap test to the regular swapping flow. Affiliate fee testing shall be done separately. I've opened a ticket for that: https://linear.app/chainflip/issue/PRO-1927/add-bouncer-affiliate-test-for-vault-swaps
- Fix bug in broker API - it was using the keyManager address.
> chore: bouncer EVM & BTC Vault Swaps to use Broker API

- api/bin/chainflip-broker-api/src/main.rs
Fix for the `broker_get_affiliates` RPC returning "Method not found".
Not sure why the compiler did not pick this up. I guess I only tested the `cf_get_affiliates` directly and not on the broker api. woops.
> fix: broker get affiliates rpc

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__broker_serialization.snap
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1911
Just added the bond to the `RpcAccountInfo` Broker variant. So now the `cf_account_info` RPC will show the bond.
Updated the snapshot for the RPC, but  I'm pretty sure this will not break anything because its just adding a field.
> feat: add bond to broker cf_account_info

- bouncer/tests/btc_vault_swap.ts
- state-chain/runtime/src/chainflip/vault_swaps.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1851
* This PR removes the logic for adding expires_at field to BTC. 
* Also corresponding bouncer test logic is also removed
> fix: revert adding expires_at to vault swap details

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/mocks/mock_eth.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
Closes: PRO-1846
Introduces a check on full deposit that a channel has not been boosted. The reason for this is that we want to catch the edge case where we would ignore the finalization of a boosted channel when the deposit minimum increases between the prewitness and the full witness stage.
> fix: only apply minimum deposit check on deposit process if it hasn't been boosted

- state-chain/pallets/cf-account-roles/src/lib.rs
- state-chain/pallets/cf-account-roles/src/mock.rs
- state-chain/pallets/cf-account-roles/src/tests.rs
- state-chain/pallets/cf-flip/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks.rs
- state-chain/traits/src/mocks/deregistration_check.rs
Closes: PRO-1831
Adds a check to ensure accounts are unbonded before allowing deregistration. We already implicitly required this but it seemed to good to have an explicit check.
> feat: check if node is bonded before deregistering

- api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
- engine/src/witness/btc/vault_swaps.rs
- engine/src/witness/evm/vault.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
We were previously defaulting it to [0u8; 32] which is an invalid address and somewhat misleading as to the intent.
> chore: make broker id explicitly optional for vault swaps

- bouncer/shared/swapping.ts
- bouncer/shared/utils.ts
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/chains/src/ccm_checker.rs
- state-chain/chains/src/sol/sol_tx_core.rs
- state-chain/chains/src/sol/sol_tx_core/program_instructions.rs
- state-chain/chains/src/sol/transaction_builder.rs
Renaming `remaining_accounts` to `additional_accounts`. `remaining_accounts` is Anchor's naming to those extra accounts, which is clear in the context or a Solana program but unclear here.
Solana CCM is not really being used yet by anyone and we are anyway versioning the `ccmAdditionalData` so I'd rather also get this into 1.8 before the overhead of changing it is too large.
> chore: rename Solana CCM remaining accounts

- .github/pull_request_template.md
Removes the non-breaking changes section from the PR template as it's more confusing than useful
> chore: remove non-breaking changes section from PR template

- localnet/docker-compose.yml
Polkadot localnet was advertising on the default port, which is being used by the chainflip node as the bootnode port.
> fix: map node communication port for polkadot localnet outside of chainflip network range

- state-chain/pallets/cf-broadcast/src/lib.rs
Just adds context about intention, otherwise could be confusing.
> chore: add comment for re_sign_aborted_broadcasts

- utilities/src/with_std/redact_endpoint_secret.rs
Closes: PRO-1908
Added a `is_local_url` function that uses the `ipv4.is_private()` to find out if its a local address in the url and skip the redacting. The secret will still get redacted if one is found in the url, regardless of it being local.
> chore: don't redact local endpoints

- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/lib.rs
This PR keeps the old delta based ingress structure, while adding:
- filter votes for nonexistent elections (e.g. if identifier_extra was updated in-flight)
- recreate elections if ingress amount on a channel updated
> fix: solana efficiency with old delta based ingress

- CHANGELOG.md
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
- engine/src/witness/sol/egress_witnessing.rs
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/housekeeping.rs
- Set search transaction history to true. This ensures the engines will witness Solana broadcast success even if the broadcast was a while ago. 
- Catch state discarded error that can occur when the SC has a reorg. This was previously causing some engines that saw the reorg to shutdown. 
- Fix Solana deposit vote filtering by refreshing the election properties with latest channel balances
- Filter out duplicate liveness votes
- Bump version 1.7.7
> fix: various small fixes for 1.7.7 to help with reliability and scalability

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
I noticed that in the case of a partial refund we don't use the CCM parameters for the swapped portion of the funds. (Looks like this was introduced in the recent CCM refactor, so this is currently working correctly on 1.7.) I changed the code to use the parameters and updated the relevant test to catch this.
> fix: use ccm params in a partial refund

- engine/src/elections.rs
- engine/src/elections/voter_api.rs
- engine/src/witness/sol.rs
Closes: PRO-1979
The voter api can now signal that it doesn't have anything to vote for by returning `Ok(None)`. Previously, in such cases we had to return `Err(..)`, which lead to the RetrierClient scheduling an exponential backoff.
> feat: `VoterApi::vote` now returns an Option.

- engine/src/witness/btc/source.rs
- engine/src/witness/common/chain_source/strictly_monotonic.rs
Fixes an extreme BTC witnessing edge case that's only currently possible when a sub 5 second bitcoin block occurs. In most cases this is handled. But can occur under very specific rotation conditions. This will be more simply resolved with the upcoming larger witnessing refactor.
> fix: no gaps in root btc source

- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/liveness.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/lib.rs
This is effectively a rewrite of the delta based ingress logic. Mostly this just makes things (subjectively speaking) more readable. 
Elections are recreated if properties change (ie. if there are any ingresses or channel closures). State (ie. 'pending ingresses') is preserved across elections. 
~~The only behavioural change is in the case where there is (a) a pending deposit in the state and (b) consensus on a higher deposit, with chain tracking lagging behind both:~~
- ~~before, the pending amount was never updated, ie. when chain tracking caught up to the pending amount, the 'first' ingress would always be processed, then the rest.~~
- ~~now, the pending amount is updated with the latest consensus value, even if chain tracking is lagging. This way, once it catches up, everything is …
> fix: solana elections efficiency improvements

- bouncer/full_bouncer.sh
- bouncer/tests/swap_after_temp_disconnecting_chains.ts
- localnet/common.sh
- localnet/docker-compose.yml
- localnet/init/config/Settings.toml
Closes: PRO-2017
The issue stems from now having 2 nodes in the polkadot network, and disconnecting it from the docker network causes it to stop finalising blocks (only sometimes). Here I'm just disabling the test, and we'll enable it for asset hub which has just one node and tests the same code. 
Also included some other small things I found while looking into it.
> fix: swap after disconnect polkadot bouncer issue

- state-chain/chains/src/sol.rs
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs
This prevents Solana channels state from accumulating on-chain. We can revert this change if/when we activate Solana channel recycling.
> fix: delete Solana channel state when closed

- state-chain/pallets/cf-elections/src/lib.rs
We bumped it on release/1.8 - so need to do so here too.
> chore: bump elections version

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
Closes: PRO-2028
Refreshes delta based ingress elections instead of recreating them.
> feat: refresh solana ingress elections instead of recreate

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
Closes: PRO-2037
Adds the broker_id to the WithdrawalRequest event.
> feat: add account id / withdrawal address to affiliate events

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__broker_serialization.snap
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__no_account_serialization.snap
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-2038
- Return affiliate details + usdc balance of affiliates for a broker account
- Deprecated earned_fees field
> feat: returning detailed account information for affiliate in the cf_account_info rpc for brokers

- Cargo.toml
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/helpers.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine.rs
- state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-2043
Re-enables the blockwitnesser ES fuzzy tests. Also uses `u32` for block ages in the block processor.
**NOTE**: Currently, due to some inefficiencies in the way we process rules in the block processor, the prop tests take an "infinitely" long time to run.
> chore: re-enable block witnesser tests

- Cargo.lock
- Cargo.toml
- api/bin/chainflip-elections-tracker/Cargo.toml
- api/bin/chainflip-elections-tracker/src/README.md
- api/bin/chainflip-elections-tracker/src/elections.rs
- api/bin/chainflip-elections-tracker/src/main.rs
- api/bin/chainflip-elections-tracker/src/trace.rs
- state-chain/pallets/cf-elections/src/lib.rs
Closes: PRO-2015
This PR introduces a new binary `chainflip-elections-tracker` which runs alongside a chainflip node and watches the state of elections in each block. It computes which part of the state have changed and pushes this information in form of OTLP traces to a compatible backend, for example to be ingested by Grafana Tempo.
This is a first version with basic tracking of elections. For example, it does not "backfill" blocks if it was shut down for a while. Further functionality is going to be added on a by-need basis.
> feat: generate traces for solana elections

- Cargo.lock
- Cargo.toml
- engine/src/witness/btc_e.rs
- state-chain/pallets/cf-elections/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser_new.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
- state-chain/runtime/src/chainflip/elections.rs
Closes: PRO-2053
This PR cleans up how we use hooks, in particular:
- there is a new trait `HookType` with two associated types `Input` and `Output`.
- the `Hook` trait now takes `T: HookType` as generic type parameter instead of directly input and output. This allows us to omit specifying the concrete hook input and output types when we implement the hook.
- There are new "tag types" for each hook, this is useful for the following:
- When instantiating an electoral system, we now try to implement all traits for a single "associated types carrier type". That is, for example for the BW ES, we implement the traits `ElectoralSystemTypes`, `BlockHeightTrackingTypes`, `StateMachineEs` and a `Hook<...>` all for the same carrier type …
> chore: cleanup state machine ES trait bounds

- engine/src/elections/voter_api.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/deposits.rs
- engine/src/witness/btc_e.rs
- state-chain/chains/src/evm.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/vote_storage/composite.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/primitives/src/lib.rs
- state-chain/runtime/src/chainflip/address_derivation/btc.rs
- state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2029
Vault deposit witnessing ES for Bitcoin.
Use a different instance of the same electoral system to handle different witnesses:
- one for deposit channel
- one for vaults
- one for egress
- etc...
This allow us to keep the election votes small and possibly to only pause/unpause specific function of the witnessing.
> feat: BTC vault deposit electoral system

- CHANGELOG.md
- api/bin/chainflip-broker-api/src/main.rs
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- state-chain/chains/src/sol.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__broker_serialization.snap
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__no_account_serialization.snap
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/delta_based_ingress.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Cherry picks recent fixes from release/1.8
> fix: pick hotfixes from 1.8 branch

- Cargo.lock
- engine/multisig/src/client/ceremony_manager/tests.rs
- engine/multisig/src/client/ceremony_runner/tests.rs
- engine/multisig/src/client/multisig_client_tests.rs
- engine/src/common.rs
- engine/src/state_chain_observer/client/error_decoder.rs
- foreign-chains/solana/sol-prim/src/tests/pda.rs
- state-chain/amm/src/limit_orders/tests.rs
- state-chain/cf-integration-tests/src/authorities.rs
- state-chain/cf-integration-tests/src/new_epoch.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/chains/src/btc.rs
- state-chain/chains/src/eth.rs
- state-chain/chains/src/evm/api/all_batch.rs
- state-chain/pallets/cf-funding/Cargo.toml
- state-chain/pallets/cf-funding/src/tests.rs
- state-chain/pallets/cf-ingress-egress/Cargo.toml
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-threshold-signature/src/benchmarking.rs
- state-chain/pallets/cf-threshold-signature/src/mock.rs
- state-chain/pallets/cf-threshold-signature/src/response_status.rs
- state-chain/pallets/cf-threshold-signature/src/tests.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-vaults/src/tests.rs
- utilities/src/lib.rs
- utilities/src/with_std/dynamic_events.rs
Added a new "assert_matches" utility macro that can be used to replace `assert!(matches!())`
Just adds a little syntactic sugar.
> chore: add assert_matches! utility function for testing

- Cargo.lock
- bouncer/tests/all_concurrent_tests.ts
- bouncer/tests/broker_level_screening.ts
- engine/src/elections/voter_api.rs
- engine/src/witness/btc/deposits.rs
- engine/src/witness/btc_e.rs
- state-chain/chains/src/dot.rs
- state-chain/chains/src/evm.rs
- state-chain/chains/src/lib.rs
- state-chain/chains/src/mocks.rs
- state-chain/pallets/cf-broadcast/Cargo.toml
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/composite.rs
- state-chain/pallets/cf-elections/src/vote_storage/composite.rs
- state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2040
Egress witnessing ES for btc
> feat: BTC egress witnessing ES

- api/bin/chainflip-broker-api/src/main.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Adds the channel action type to the rpc call, such that the deposit monitor can apply custom logic for deposit channel vs swap screening.
> feat: add channel action type to result of `cf_all_open_deposit_channels` rpc.

- api/bin/chainflip-broker-api/src/main.rs
We had an "optimization" in place in 1.7 where we wouldn't push events if they vec was empty, on main we already removed it. This PR also removes it here.
In particular, since we now also have eth events this would have meant that we won't push any events if there aren't any btc events.
> fix: eth broker level screening, push empty events in broker api

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- api/bin/chainflip-ingress-egress-tracker/src/witnessing.rs
- api/bin/chainflip-ingress-egress-tracker/src/witnessing/dot.rs
- engine/Cargo.toml
- engine/src/dot.rs
- engine/src/dot/http_rpc.rs
- engine/src/dot/retry_rpc.rs
- engine/src/dot/rpc.rs
- engine/src/lib.rs
- engine/src/state_chain_observer/client.rs
- engine/src/state_chain_observer/client/base_rpc_api.rs
- engine/src/state_chain_observer/client/subxt_state_chain_config.rs
- engine/src/witness/dot.rs
- engine/src/witness/dot/dot_chain_tracking.rs
- engine/src/witness/dot/dot_deposits.rs
- engine/src/witness/dot/dot_source.rs
- utilities/scale-json-event-logger/Cargo.toml
- utilities/scale-json-event-logger/src/main.rs
Closes: PRO-2026
* Subxt 0.39.0 introduces breaking changes. subxt is now completely decoupled from subtrate and doesn't require it as dependency (`substrate-compat` feature is removed)
* They have introduced basic types instead of substrate types such as: `subxt::utils::H256` instead of `sp_core::H256`. 
* The changes made in this PR mainly address this type conversion issues especially for the `dot` chain. 
* There were a lot of assumptions that the dot chain hash type is `sp_core::H256`, this PR changes the dot hash type to be `pub type PolkadotHash = <subxt::PolkadotConfig as subxt::Config>::Hash;` 
* PR passes full bouncer tests
* ~~To not have polkadot version mismatch issues, this PR uses our fork …
> feat: upgrade subxt to 0.39.0

- bouncer/README.md
- bouncer/commands/run_test.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/vitest.ts
Welcome back the `run_test.ts` command.
Solves the problem of having to know the name of the test to run it. Now you can just give the command a file path and it will run the test using `vitest`.
It works by exploiting the `vitest list` command to execute the `.test` files without running the tests. I use this to save the test names and function names to a file that I can then be cross referenced with the given test file to find the correct test name to run. A bit hacky, but it works great.
Usage: 
```sh copy
./commands/run_test.ts ./tests/boost.ts
```
> feat: bouncer run test command

- state-chain/custom-rpc/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-1639
It has been deprecated for a while, it's time to remove it in 1.9 to reduce the maintenance burden. 
Docs: https://github.com/chainflip-io/chainflip-docs/pull/516
> chore: remove prewitness swaps subscription

- api/bin/chainflip-lp-api/src/main.rs
- api/cf-rpc-types/src/lp.rs
Closes: PRO-1167
Adds hash to get_open_swap_channels, and adds fields for arbitrum and solana.
This should be backwards compatible because:
- Takes an optional new param. Defaults to None -> preserving current behaviour.
- We are only adding fields to the return type, so json parsing should still work
> feat: add option hash to get open swap channels

- state-chain/pallets/cf-lp/src/benchmarking.rs
- state-chain/pallets/cf-lp/src/lib.rs
- state-chain/pallets/cf-lp/src/mock.rs
- state-chain/pallets/cf-lp/src/tests.rs
- state-chain/pallets/cf-lp/src/weights.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/swapping.rs
Closes: PRO-1999
- Renamed `internal swap` to `on-chain swap`
- Added a trait to get the minimum deposit from the ingress egress pallets.
- Added a check to the on-chain swap RPC, to make sure the amount is above the minimum.
- Added a check to cover this in the existing unit test.
- Manually confirmed that the minimum swap works via executing an on-chain swap in the bouncer.
> feat: enforce minimum swap amount for on-chain swaps

- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser_new.rs
- state-chain/runtime/src/chainflip/bitcoin_block_processor.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2054
Remove dedup hook and perform the deduplication (which is common to all the ES) inside the execute hook -> this can now easily be generalized into a function.
> feat: remove dedup hook

- localnet/docker-compose.yml
if variable is not set, use given default value.
This is required for running the broker-level-screening test in the deposit-monitor repo's CI. Cherry pick of PR on main: https://github.com/chainflip-io/chainflip-backend/pull/5706.
> feat: use environment variable to choose deposit-monitor image tag.

- .cargo/config.toml
- .github/workflows/_21_build_m2.yml
- Cargo.lock
* fix: explicitly install rust toolchain on M2 Runners 🐛
* chore: cargo audit
---------
Co-authored-by: Daniel <daniel@chainflip.io>
> fix: explicitly install rust toolchain on M2 Runners 🐛 (#5718)

- engine-runner-bin/build.rs
Sig was `.sig` now it's `.asc`
> fix: sig verification should use .asc sig

- .github/workflows/_21_build_m2.yml
explicitly names the toolchain to install via "rustup install toolchain" to be "nightly" in order to fix the m2 build CI job
> fix rustup install toolchain on m2 build

- .github/workflows/_21_build_m2.yml
explicitly specify darwin arm as the rustup toolchain for m2 build actions
> specify rustup architecture as darwin

- .github/workflows/_21_build_m2.yml
sets the m2 toolchain to nightly-2025-01-10-aarch64-apple-darwin
> fix: m2-toolchain-nightly-2025-01-10-aarch64-apple-darwin

- Cargo.lock
- Cargo.toml
- api/cf-node-client/Cargo.toml
- api/cf-node-client/src/subxt_state_chain_config.rs
- engine/src/state_chain_observer/client.rs
- engine/src/witness/dot.rs
Closes: PRO-2123
* This PR upgrades subxt to rev: [da3ea0b](https://github.com/paritytech/subxt/commit/da3ea0b528c00d2ec6cbc618f46db382dc7bd117) which includes our suggested fix to the wasm-loader in the subxt macro that was causing our CI to fail when the runtime is not built with std feature.
* Also had to make minor changes to fix breaking changes introduced by recent subxt commits such as: renaming signed_extentions to transaction_extensions
> feat: update subxt to >0.41.0 with breaking changes fixes

- api/bin/chainflip-broker-api/src/main.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/snapshots/custom_rpc__test__vault_addresses_custom_rpc.snap
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/address_derivation/btc.rs
- state-chain/runtime/src/chainflip/vault_swaps.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Cherry-picks #5711 to main. 
* feat: Added endpoint to return vault addresses
* refactor: added runtime call
* refactor: Extended the API to return also all deposit addresses
* tests: added snapshop tests for vault_address encoding
* refactor: applied requested changes
- Simplified return of vault addresses
- Handle None case in address derivation
- Removed BTC root vault
* chore: fixed clippy + tests
* chore: using struct instead of tuple
* chore: small refactors:
- rename struct
- encapsulate address conversions
---------
> feat: add RPC to return all current vault addresses (#5711)

- state-chain/custom-rpc/src/backend.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/monitoring.rs
- state-chain/node/src/service.rs
Closes: PRO-2126
* This PR moves common logic (interact with the runtime API, manage subscriptions, and handle block
notifications) to a separate backend module.
* The main goal is that this new `CustomRpcBackend` struct can be instantiated and the logic is shared by different CustomApi providers such as: the custom rpc, lp_api and broker
> refactor: make custom rpc logic shareable

- api/bin/chainflip-cli/src/main.rs
- api/bin/chainflip-lp-api/src/main.rs
- api/cf-rpc-types/src/lp.rs
- api/lib/src/lp.rs
- bouncer/tests/lp_api_test.ts
Closes: PRO-2039
Added a new RPC `lp_request_liquidity_deposit_address`, It returns a struct with the address and expire block.
~~This is a breaking change for this RPC. @acdibble~~
> refactor: include expire block in liquidity deposit details

- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/pallets/cf-trading-strategy/src/lib.rs
- state-chain/pallets/cf-trading-strategy/src/tests.rs
- state-chain/traits/src/liquidity.rs
- state-chain/traits/src/mocks/pool_api.rs
Now instead of having to remember which orders a strategy creates (which given the old code would result in an error if the strategy was closed in the same block as its creation), the strategy simply asks the pool api to cancel all of orders recorded to belong to that strategy. (I think this is a better solution since it will probably be more error prone keeping track of open orders in the strategy pallet especially once we add more complex strategies.) More context: https://github.com/chainflip-io/chainflip-backend/pull/5715#issuecomment-2724769776
> fix: more robust cancellation of strategy orders

- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/order_fills.rs
* Fixes reported issues of seeing "Could not fetch block header"  internal error for lp_order_fills subscription
> fix: order_fills_for_block fix to show error only when result is none

- Cargo.lock
- state-chain/pallets/cf-trading-strategy/Cargo.toml
- state-chain/pallets/cf-trading-strategy/src/lib.rs
- state-chain/pallets/cf-trading-strategy/src/mock.rs
- state-chain/pallets/cf-trading-strategy/src/tests.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/safe_mode.rs
Closes: PRO-2116
Added a single safe mode flag that disables:
- deployment of new strategies
- adding funds to strategies
- closing strategies
- automatic updates of limit orders (in `on_idle`)
Added unit tests to check all 4.
> feat: safe mode for trading strategies

- state-chain/custom-rpc/Cargo.toml
- state-chain/custom-rpc/src/lib.rs
Closes: PRO-2152
* This PR adds a subscription garbage collector where it tracks the all pinned blocks reported by `chainhead_v1_follow` and starts unpinning old blocks once the its queue reaches a certain capacity (default 64)
* Manual tests were carried out on a local node with MAX_PINNED_BLOCKS set to 32 to speed up seeing subscriptions dropping effect.
* A full test with 100 subscriptions was run on a local node with MAX_PINNED_BLOCKS set to the default 512.
> fix: prevent subscriptions dropping by properly unpinning blocks

- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-trading-strategy/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-2155
Simple RPC that gets an asset map of the trading strategy limits. 2 limits `minimum_deployment_amount` and `minimum_added_funds_amount`.
`None`/`null` means no limit is set, so the asset is disabled.
```bash
curl -H "Content-Type: application/json" \
-d '{
"id": 1,
"jsonrpc": "2.0",
"method": "cf_get_trading_strategy_limits",
"params": []
}' http://localhost:9944
```
```json
{
"jsonrpc": "2.0",
"result": {
"minimum_deployment_amount": {
"Ethereum": {
"ETH": null,
"FLIP": null,
"USDC": 20000000000,
"USDT": 20000000000
},
"Polkadot": {
"DOT": null
},
"Bitcoin": {
"BTC": null
},
"Arbitrum": {
"ETH": null,
"USDC": 20000000000
},
"Solana": {
"SOL": null,
"USDC": 20000000000
}
},
"minimum_added_funds_amount": {
"Ethereum": {
"ETH": null,
"FLIP": null,
"USDC": 10000000,
"USDT": …
```
> feat: trading strategy limits rpc

- Cargo.lock
- bouncer/shared/try_runtime_upgrade.ts
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-broadcast/src/migrations.rs
- state-chain/pallets/cf-elections/src/electoral_systems/blockchain/delta_based_ingress.rs
- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-threshold-signature/src/lib.rs
- state-chain/pallets/cf-threshold-signature/src/migrations.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations.rs
- state-chain/runtime/src/migrations/sol_versioned_transactions.rs
This ensures we exit (early) with an error if the runtime upgrade test fails. 
Since we were ignoring this previously, some errors had slipped into main, so this PR fixes those too:
- bumps the upgrade_from version to 1.8.4
- migrate solana txs to VersionedTransaction format. 
- enviroment pallet storage version bumped
> fix: throw error if runtime upgrade test fails

- Cargo.lock
- Cargo.toml
Comes out of cargo audit finding: https://rustsec.org/advisories/RUSTSEC-2025-0023
> chore: bump tokio to latest version

- bouncer/tests/fund_redeem.ts
- state-chain/pallets/cf-funding/src/lib.rs
- state-chain/pallets/cf-funding/src/tests.rs
Closes: PRO-2035
- We check if we try to redeem max and if we try to redeem the total balance of the account. If yes, we don't burn any tax and ignore the tax aside for the rest of the calculations
- Updated all tests where necessary and tried to understand if the change of the test makes sense
> feat: ignore redemption tax when redeem all

- state-chain/amm/Cargo.toml
- state-chain/amm/src/common.rs
- state-chain/amm/src/lib.rs
- state-chain/amm/src/limit_orders.rs
- state-chain/amm/src/limit_orders/tests.rs
- state-chain/amm/src/range_orders.rs
- state-chain/amm/src/tests.rs
- state-chain/pallets/cf-pools/src/benchmarking.rs
- state-chain/pallets/cf-pools/src/lib.rs
- state-chain/pallets/cf-pools/src/migrations.rs
- state-chain/pallets/cf-pools/src/migrations/remove_limit_order_pool_fee.rs
- state-chain/pallets/cf-pools/src/tests.rs
Closes: PRO-2034
- As discussed, when comparing limit and range order prices I chose to "inverse adjust for fee" the limit order price since that led to much cleaner and less error prone code (even though this seems backwards).
- Added a test for fee adjustment math, and also a test to check that we can correctly transition between range and limit orders when executing a swap. Previously I don't think this was sufficiently tested: I almost missed an infinite loop because of this.
- Limit orders no longer charge pool fee; the pool fee field still exists in limit order's PoolState, but (as discussed) I think it would be easier to change the funcitonality first and then clean up later.
- Now setting pool fee only sets it for range orders.
- Added a migration to set limit order pool fee to 0 …
> feat: remove pool fee for limit orders

- state-chain/cf-integration-tests/src/broadcasting.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/chains/src/arb/api.rs
- state-chain/chains/src/eth/api.rs
Fixes an issue with `refresh_replay_protection` on Eth/Arb whereby we would always override the contract address with the key manager address.
> fix: refresh evm replay protection with correct contract address

- state-chain/pallets/cf-ingress-egress/src/boost_pool.rs
- state-chain/pallets/cf-ingress-egress/src/boost_pool/tests.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
Closes: PRO-1958
Simple mapping of the error to a pallet error so we can see the error message though an RPC/extrinsic.
> chore: map boost pool error

- state-chain/chains/src/mocks.rs
- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-broadcast/src/mock.rs
- state-chain/pallets/cf-broadcast/src/tests.rs
Closes: PRO-2214
- Use correct threshold signer types in broadcast mocks
- Refactor broadcast tests to use a more accurate transaction_out_id.
- Don't clean up storage when re-signing. If we clean it up there's an edge case that means we can successfully witness at the point of resigning, but this will be rejected, because the appropriate storage is not there. When we resign we will overwrite the data associated with the broadcast id later down the line anyway.
- Add failing test to demonstrate no clean up bug
- Introduce `BroadcastIdToTransactionOutIds` to properly clean up `TransactionOutIdToBroadastId` (use a Vec for append semantics), fixing the failing test
> fix: correctly clean up TransactionOutIdToBroadcastId storage

- .github/workflows/_24_docker.yml
- .github/workflows/_26_docker_external_networks.yml
- .github/workflows/docker-build-rust-base.yml
Fix github docker cache issue, as github deprecated some older versions we were depending on.
We remove cache-from and cache-to as Namespace provides this already.
> chore: bump docker build-push

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/mocks.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/pallets/cf-pools/src/tests.rs
- state-chain/test-utilities/src/lib.rs
Closes: PRO-2212
- Prewitnessed deposits are now delayed by `BoostDelayBlocks` blocks before being processed. If `BoostDelayBlocks` is 0 (the current default), they are processed immediately as before.
- If a deposit is finalised before it is "prewitness" is processed (e.g. the delay is too long), the deposit is processed as not boosted.
- `BoostDelayBlocks` is configurable by governance
> feat: ability to delay boost

- .github/workflows/_100_run_benchmarks.yml
This appears to have changed (?) since the last release.
Seems to work, based on [this run](https://github.com/chainflip-io/chainflip-backend/actions/runs/14596896538/job/40945101442).
> fix: use ci-benchmarks-release instead of ci-benchmarks

- engine/src/witness/sol.rs
- engine/src/witness/sol/lookup_table_witnessing.rs
- foreign-chains/solana/sol-prim/src/consts.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/chains/src/sol/api.rs
- state-chain/pallets/cf-elections/src/electoral_system.rs
- state-chain/pallets/cf-elections/src/electoral_system_runner.rs
- state-chain/pallets/cf-elections/src/electoral_systems/exact_value.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/egress_success.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/exact_value.rs
- state-chain/pallets/cf-environment/src/lib.rs
- state-chain/pallets/cf-environment/src/mock.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
Closes: PRO-2167, PRO-2169
ALT election results are now stored into the unsynchronised state map with Reference counting
ALT election results are now taken from the state map on ApiCall construction, managed with RC
Removed the expiry system from ALT witnessing elections
Added appropriate integration tests, and fixed a test with a TODO
> refactor: store solana alt election results in unsynchronised state map

- api/cf-rpc-types/src/lib.rs
- state-chain/cf-integration-tests/src/swapping.rs
- state-chain/custom-rpc/src/order_fills.rs
As @niklasnatter correctly pointed out, the amount we are exposing here is the *bought* amount, thus renaming the field.
> chore: rename sold_amounts -> bought_amounts

- .github/workflows/_40_post_check.yml
- .github/workflows/upgrade-test.yml
Closes: PRO-2218
The writing to chain explorer can last the duration of the whole maximum job time just because it can't connect. Better to exit early, shouldn't take more than 10 minutes to write the file.
> chore: add timeout for writing chain explorer to file

- engine/src/witness/eth/chain_tracking.rs
Closes: PRO-2237
We saw a large ETH priority fee spike. We can protect against these single block spikes by taking the last two blocks of fees. Taking the highest base fee, and the lowest priority fee of the two.
> feat: protect against priority fee spikes

- state-chain/pallets/cf-trading-strategy/src/lib.rs
> fix: disable USDC as base asset when creating a strategy

- state-chain/custom-rpc/src/backend.rs
- state-chain/custom-rpc/src/order_fills.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/missed_authorship_slots.rs
Closes: PRO-2018
Getting the timestamp from the header via the existing `extract_slot_from_digest_item` function.
I think this is not a breaking change because its just adding a field to the `BlockUpdate`.
Tested it on a few subscriptions and checked time is correct.
> feat: timestamp in block update

- engine/src/witness/btc.rs
- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/consensus.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/test_utils.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline/chainstate_simulation.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2182
This PR adds a proptest `Strategy` to generate a virtual chain progression with forks, reorgs and "fuzzy timing" which can be used to test the core statemachine logic for the witnessing. It's in `electoral_system/state_machine_chain.rs`. The goal was for the strategy to work nicely with the minimization feature of proptest which tries to find a minimal example when some input is found to break the given properties. It is not yet clear whether this goal succeeded 100%, but the generated inputs already have been highly helpful in finding edge-cases we haven't considered until now.
In `electoral_system/tests/statemachine_witnessing.rs` there's a proptest that uses the new `generate_chain_progression` strategy to …
> test: add full witnessing pipeline proptests

- engine/src/witness/sol.rs
- engine/src/witness/sol/lookup_table_witnessing.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/chains/src/sol/api.rs
- state-chain/pallets/cf-environment/src/mock.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
Closes: PRO-2261
Refactored the Solana ALT auction's key to a BTreeSet.
This orders and dedups the alt addresses
> refactor: solana alt auction uses a BTreeSet instead of Vec as key

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
Closes: PRO-2270
- Removed explicit filter for SwapDepositAddressReady
- Moved filtering of beneficiaries into take_broker_fees fuction
> fix: Don't filter affiliates with 0 BPS in events

- state-chain/chains/src/arb/api.rs
- state-chain/chains/src/btc/api.rs
- state-chain/chains/src/dot/api.rs
- state-chain/chains/src/eth/api.rs
- state-chain/chains/src/evm/api/all_batch.rs
- state-chain/chains/src/hub/api.rs
- state-chain/chains/src/lib.rs
- state-chain/chains/src/sol/api.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-tokenholder-governance/src/mock.rs
- state-chain/pallets/cf-vaults/src/mock.rs
- state-chain/runtime/src/chainflip.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/api_call.rs
Closes: PRO-2238
- Modifies the pattern of building a transaction to introduce a default function that automatically wraps the actual call functionality into a transactional wrapper
- This pattern applies only if the `new_unsigned` returns a Result type, since otherwise the call can not fail
- Added a test to verify the general storage rollback
> feat: Make transaction building transactional

- engine/src/witness/hub/hub_source.rs
We just carried over the timeout from Polkadot, but we should increase it since an AssetHub block is 12 seconds.
> chore: increase stream timeout for hub

- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine_es.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2293
This PR improves the way we handle the `ElectoralSystemTypes` derivation for statemachine based ESs. Instead of requiring the user to provide a full instantation of `ElectoralSystemTypes` and afterwards require some equalities to hold with respect to the given state machine (e.g. OnFinalizeContext should be the statemachine context), we derive a "new" `ElectoralSystemTypes` from the given state machine. This doesn't work completely, since there are some choices to make (which VoteStorage to use, the statechain block number, the onfinalize return value). These still have to be provided.
Anyways, the resulting `bitcoin_elections.rs` is already much conciser.
> chore: derive electoral system types automatically from statemachine

- engine/src/btc/rpc.rs
Closes: PRO-2294
Bitcoin latest release introduced this new `target` field to the response of getblock.
We don't need it so we simply added as optional to support this new release.
> fix: add new `target` field to BTC VerboseBlock

- bouncer/commands/set_minimum_network_fee.ts
Adds another command that can be used for setting the min. network fee (for both internal/regular swaps)
> chore: add a command for setting minimum network fee

- engine/src/elections.rs
- state-chain/cf-integration-tests/src/solana.rs
- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-elections/src/electoral_systems/mocks/access.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/pallets/cf-elections/src/tests.rs
- state-chain/runtime/src/lib.rs
The `call_size()` test is to restrict the enum size, we were hitting this. So introducing a Box to the extrinsics with the biggest types to resolve this.
> chore: box extrinsic types to reduce RuntimeCall enum size

- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
Closes: PRO-2281
- Added an optional `is_internal` param to the `cf_pool_swap_rate_v3`.
- Also now supports the new custom network fee rates for any asset.
> feat: support for internal swaps and asset specific network fees in swap rate RPC

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
> fix: Don't filter affiliates with 0 BPS in events (#5870)

- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_tracking/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/helpers.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2321
This re-enables the (statemachine) (unit-) proptests for the BW. They've been disabled a long time due to refactorings.
This surfaced a few bugs, so in particular this commit includes the following changes:
- fix: expire optimistic blocks.
- fix: forward Governance election block data to BP.
- fix: only mutate ongoing ByHash elections to BySafeHeight, don't do anything with Optimistic.
- test: remove the requirement for safeheight elections to be lower than ongoing. This is because in certain cases (impossible with the current BHW) we can't guarantee it.
- test: add an alternative requirement for safeheight and ongoing elections to be disjoint.
- fix: rewrite the CompactHeightTracker to use a BTreeMap …
> test: reenable BW proptests

- state-chain/pallets/cf-broadcast/src/lib.rs
- state-chain/pallets/cf-chain-tracking/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/pallets/cf-ingress-egress/src/tests/boost.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2311
Added different safe modes for:
- deposit channel creation
- deposit channel witnessing
- vault deposit witnessing
- egress witnessing
+ introduced `inner_update_chain_height` to avoid setting the BTC fees to 0 when updating the chain height
> feat: create different safe modes for different block-witnessers

- state-chain/chains/src/lib.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/consensus.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/consensus.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine_es.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline/chainstate_simulation.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
- state-chain/runtime/src/chainflip/solana_elections.rs
- state-chain/runtime/src/migrations/safe_mode.rs
Closes: PRO-2332
- chore: deduplicate trivial Validate implementations for base types.
- chore: replace `BlockZero` trait by `Default` everywhere.
- chore: introduce dedicated struct for StagedConsensus instead of using tuples.
- chore: rename `input_index` to `query`.
> chore: bitcoin election chores

- Cargo.lock
- state-chain/chains/Cargo.toml
- state-chain/chains/src/deposit_channel.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/core.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_height_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2335
This PR switches most types over to use the new `GenericTypeInfo` derive macro to generate TypeInfo implementations that properly take into account generics. This fixes a few issues with polkadot.js.
In order to generate non-overlapping names for all instantiations, this PR adds:
- a `const NAME: &'static str` constant to the `ChainTypes` trait
- a `const BWNAME: &'static str` constant to the `BWTypes` trait
Also it was necessary to change the TypeInfo name of the cases of the `DepositFailedDetails` enumeration, since they overlapped with the TypeInfo name of the `DepositDetails` struct.
> chore: better typeinfo for bitcoin elections

- state-chain/custom-rpc/src/snapshots/custom_rpc__tests__runtime_safe_mode_serialization.snap
- state-chain/pallets/cf-lending-pools/src/lib.rs
We already have `boost_deposits_enabled` in the ingress-egress pallet and this one was unused. No migration is needed since it is in the new pallet.
> chore: remove duplicate/unused safe mode option

- bouncer/shared/deposit_liquidity.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/substrate.ts
- bouncer/tests/lp_api_test.ts
- Added a timeout feature to the observe event function.
- Added the option for the run with timeout function to use the logger and take a description of the task that its running.
- Used the features to add a 90sec timeout to the deposit liquidity function where it has been timing out on the "flaky" tests.
- Start of PRO-1997
> feat: bouncer deposit liquidity timeout

- engine/src/witness/btc.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_height_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_height_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Closes: PRO-2360
This PR makes the SAFETY_BUFFER configurable by putting it into the settings of both the BHW and the BW.
It *also* sets the default safety_margin for bitcoin to 1 block. This means that we will emit a full witness event when a deposit is of age 1.
> feat: make safety buffer configurable

- Cargo.lock
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
This should make the upgrade test more reliable.
> fix: change old_version to 1.9.7 for more reliable upgrade test

- bouncer/tests/boost.ts
- bouncer/tests/fast_bouncer.test.ts
This adds some additional logging to the boost test in bouncer. 
Also structures the processes a bit differently: the test checks for when boost fails because of missing liquidity. 
It also fixes a potential issue where we were always checking for btc pools although the test takes an arbitrary asset as argument.
> fix: bouncer boost tests improved diagnostics

- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/block_processor.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/block_witnesser/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/block_witnesser.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
Cherry-picks "Fix polkadot.js decoding for various bitcoin election types (#5972)" onto release/1.10
* fix: Fix polkadot.js decoding by attaching the BWName to typeinfo of various BW structs.
* chore: fix clippy / compilation of tests.
> cherry-pick: Fix polkadot.js decoding for various bitcoin election types (#5972)

- bouncer/tests/assethub_xcm.ts
Instead of waiting for the swap promise, and then waiting for the balance to increase, we do both in parallel.
> fix: parallelize waiting for promises in AssethubXcm test

- state-chain/pallets/cf-ingress-egress/src/migrations.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/ccm_add_data_to_decoded.rs
- state-chain/runtime/src/migrations/boost_refactor.rs
The migrations for ccm_add_data_to_decoded and for the boost refactor clashed, because they both tried to migrate some data. I merged the critical part into the ccm_add_data_to_decoded migration.
> fix: merge boost migrations for bitcoin_ingress_egress

- bouncer/shared/setup_elections.ts
Fix the bitcoin elections setup step in the bouncer. Should ignore setting up when the pallet is not found.
> fix: skip elections setup if pallet not found

- engine/src/witness/eth/chain_tracking.rs
Closes: PRO-2386
- use the median instead of 70th percentile
- use the last 5 blocks instead of only 2
> fix: increase the eth fee tracking window to 5 blocks

- engine/src/witness/btc.rs
Closes: PRO-2398
When querying for optimistic blocks the RPC will always fail for non-existing block, since we are querying optimistically this is expected to happen very often. Changed the logic to query only if the block is actually new and return None otherwise.
> fix: avoid logging Error in case of Optimistic Election

- engine/src/state_chain_observer/client.rs
Closes: PRO-1953
When CFE is launched, it will try to check for CFE version - something unique to CF nodes. This ensures Engine is connecting to a valid CF node, not other Substrate-based chains by mistake
If an invalid CFE version is returned, the CFE exits early.
To reproduce the error and test the fix, replace `$SC_RPC_PORT` with `9947` in `localnet/init/scripts/start-engine.sh`
> feat: CFE check for CF chain node connection

- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-elections/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems/tests/unsafe_median.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/pallets/cf-elections/src/lib.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations.rs
- state-chain/runtime/src/migrations/bitcoin_elections.rs
Related: PRO-2443
Since 1.10 we use the `UnsafeMedian` electoral system for witnessing bitcoin fees. This creates new elections on every SC block. Unfortunately, the bitcoin rpc call that we use to get fees (`estimate_smart_fee`) only very rarely updates it's value (every 2 btc blocks or so), so it doesn't make sense to query the rpc and vote on every SC block.
This PR adds a new (unsynchronised) setting to the UnsafeMedian ES that lets us specify the number of SC blocks to wait until the next election is created.
> feat: configurable bitcoin fee polling interval [pick to 1.10]

- bouncer/shared/utils/substrate.ts
* Fixes a race condition in bouncer's `observeEvent` function between checking for the event in historic blocks and in the  new block from a subscription
> fix: remove race condition in bouncer observe event

- bouncer/tests/DCA_test.ts
- state-chain/pallets/cf-swapping/README.md
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/migrations.rs
- state-chain/pallets/cf-swapping/src/migrations/swap_queue_migration.rs
- state-chain/pallets/cf-swapping/src/migrations/swap_request_migration.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fees.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/primitives/src/lib.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-2354
- Refactored the dca state to hold a List of scheduled swap ids instead of just one.
- Refactored the swap queue so we do not need to know the block a swap is in to reschedule/cancel it.
- Refunding a failed swap will also cancel any other swaps that are scheduled for that swap request.
- New event `SwapCanceled`.
- Rescheduling a swap will also reschedule any other swaps that are scheduled for that swap request.
- Refactored the dca state functions to split them up for more control.
- Init swap request now schedules 2 chunks if the interval is 1.
- When a swap completes it schedules the next chunk for the swap request, not necessarily a consecutive chunk.
- Added tests to cover the new 1 block interval.
- Changed the dca test in the bouncer to cover the 1 block interval. …
> feat: Support for DCA 1 block interval

- engine/src/witness/sol/egress_witnessing.rs
Closes: PRO-1615
Some time ago we've made the return value of the vote() function optional ([PRO-1979](https://linear.app/chainflip/issue/PRO-1979/make-return-value-of-voterapi-optional)). If the voter logic gets this value it doesn't vote for this election. It is going to try to vote again on the next SC block because is_vote_desired() returns Ok(true) for the ExactValue ES that's used by SolanaEgressWitnessing.
> refactor: return `Ok(None)` instead of error if sol egress witnessing cannot find a tx

- state-chain/pallets/cf-elections/src/electoral_systems/state_machine/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/statemachine_witnessing_pipeline.rs
We had long runs of the coverage-check in CI (which of course runs all tests to compute the coverage), due to a high number of iterations set for the proptests. This PR lowers the number of proptest iterations. When changing existing proptest-tested statemachine code, **the iteration numbers should be temporarily increased**, to ensure full coverage.
> fix: use fewer proptest iterations to decrease CI times.

- bouncer/tests/assethub_xcm.ts
Closes: PRO-2458
Instead of waiting for the `performSwap()` promise to resolve, we merely log in case of failure. We only wait for balance increases on HubDot (due to the swap) and on Polkadot (due to XCM execution).
**NOTE:** This test has to be redone after we deprecate polkadot, at the latest in 1.12.
> fix: only wait for balance increases, ignore `performSwap()` exceptions.

- state-chain/runtime/src/lib.rs
Closes: PRO-2438
Ensures we don't include ingress/egress fees for internal swaps when estimating the rate.
> fix: respect internal_swap parameter when estimating ingress egress fees in simulate_swap

- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/migrations/swap_request_migration.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/ccm.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/swap_request_api.rs
- state-chain/traits/src/swapping.rs
In liquidation swaps (and I think this might apply to other types of new "system" swaps like the onces swapping collected interest) we want to be able to set an oracle price limit but no expiry time and no refund address (these swaps are never meant to expire and should always execute to completion unless they are explicitly cancelled). However, current types in the swapping pallet don't support this: if you provide any type of price limit, you have to provide other fields too (max duration could have a sensible `u32::MAX`, but there is no sensible default for the refund address), and it seems better to encode the intention of swaps never expiring but having an oracle price limit into the type system.
Here I added `PriceLimitsAndExpiry` replacing the use of …
> refactor: swap expiry enum

- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests.rs
- state-chain/pallets/cf-swapping/src/tests/config.rs
- state-chain/pallets/cf-swapping/src/tests/dca.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/traits/src/mocks/price_feed_api.rs
Closes: PRO-2453
- Changed the new swap canceled event to `SwapAborted`. 
- Emit the `SwapAborted` event both when a swap is canceled and when a swap fails.
- Added a new enum `SwapFailedReason`
- put the new reason enum in swap aborted event and swap rescheduled event.
> feat: swap aborted event

- .github/workflows/upgrade-test.yml
- bouncer/commands/setup_vaults.ts
- bouncer/commands/update_price_feeds.ts
- bouncer/package.json
- bouncer/pnpm-lock.yaml
- bouncer/shared/new_swap.ts
- bouncer/shared/setup_elections.ts
- bouncer/shared/sol_vault_swap.ts
- bouncer/shared/update_price_feed.ts
- bouncer/tests/evm_deposits.ts
- bouncer/tests/fill_or_kill.ts
Closes: PRO-2460
Add Oracle Swaps to FoK bouncer test.
Increase timeout for Oracle price elections as part of the election setup so the oracle prices are up to date for the whole duration of the bouncer run without needing to update it periodically.
> chore: add oracle swaps FoK bouncer test

- bouncer/tests/fast_bouncer.test.ts
This was (I'm pretty sure) preventing boost pool creation - which relies on governance to create the pools.
> fix: make multiple members gov test serial

- bouncer/commands/try_runtime_upgrade.ts
- bouncer/shared/try_runtime_upgrade.ts
- bouncer/shared/upgrade_network.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/exec_with_log.ts
This improves the try-runtime command:
- refactor: use `spawn` instead of `execAsync`. This lets us print the stdout and err while the upgrade test is running. Note, this requires us to pass the CLI-arguments as a `string[]`, instead of as a concatenated `string`, as we did until now.
- fix: add `info` to rust loglevel. This makes `try-runtime` actually print the relevant logs.
> fix: better try-runtime logging in upgrade test

- bouncer/shared/utils/logger.ts
- bouncer/shared/utils/substrate.ts
- bouncer/shared/utils/vitest.ts
Stores all logs of a logger in a custom `logStorage` attribute. If a test fails, we can print out all logs that *this* logger accumulated, giving more context into the reason for failure.
Example output:
```
...
↓ ConcurrentTests > BrokerLevelScreening
↓ ConcurrentTests > VaultSwaps
× ConcurrentTests > SpecialBitcoinSwaps 23322ms
→ Error: something happened!
history:
[2025-08-27T08:13:10.736Z] INFO: 🧪 Starting test SpecialBitcoinSwaps
[2025-08-27T08:13:10.744Z] TRACE: Observing event swapping:SwapDepositAddressReady
[2025-08-27T08:13:11.080Z] TRACE: Found event 1 swapping:SwapDepositAddressReady events in block 28934
[2025-08-27T08:13:13.901Z] DEBUG: $Deposit address: bcrt1p8henkz3pfgks3r0w9g0r7hqcx82vagg2z2ul59heqtnr8am5g5gsm60m2e
[2025-08-27T08:13:13.901Z] DEBUG: Destination address is: …
```
> feat: print logs of failed test when error is thrown in bouncer test.

- state-chain/custom-rpc/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-swapping/src/lib.rs
- state-chain/pallets/cf-swapping/src/tests/fill_or_kill.rs
- state-chain/primitives/src/lib.rs
- state-chain/runtime/src/chainflip/vault_swaps.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/swap_parameter_validation.rs
Closes: PRO-2482
We already had a system for refund params validation, so i added the oracle slippage to that.
If either asset returns None from the price feed, the validation will return an error.
**Breaking change**: added params to the `cf_validate_refund_params` RPC. @dandanlen lmk if that's not ok.
> feat: oracle swap refund params validation

- Cargo.lock
- Cargo.toml
- api/bin/chainflip-elections-tracker/Cargo.toml
Fixes cargo audit:
```
Crate:     tracing-subscriber
Version:   0.3.19
Title:     Logging user input may result in poisoning logs with ANSI escape sequences
Date:      2025-08-29
ID:        RUSTSEC-2025-0055
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0055
Solution:  Upgrade to >=0.3.20
```
> fix: RUSTSEC-2025-0055 - update tracing-subscriber

- bouncer/shared/utils/logger.ts
- bouncer/shared/utils/vitest.ts
Some tests have a list of subfunctions that test a given functionality with different inputs (e.g. the FillOrKill test checking that FoK paramers work for various assets). These tests create child loggers with a `{tag: ...}` binding. The previous implementation of test-local-logs did not collect the logs for tagged children when an error is thrown.
Changes:
- When an error is thrown at the top level of a test, collect logs not only from the logfile of that test, but also try to get a list of all possibly tagged child log files.
> fix: print logs from all childloggers with a `tag` if the test itself has none

- bouncer/shared/send_btc.ts
- bouncer/shared/utils.ts
- bouncer/shared/utils/logger.ts
- bouncer/tests/broker_level_screening.ts
Closes: PRO-2512
Previously, we used our default wallet for the BLS tests, which means that if the DM marks a tx which spends change back into the wallet as tainted, and that UTXO is used later on to constructs txs for other tests, the DM will reject these other transactions, inadvertently.
Fix: we now use a dedicated wallet, so taintedness should be confined to it.
> fix: use dedicated wallet for BLS tests.

- .github/workflows/_01_pre_check.yml
- .github/workflows/_05_force_version_bump.yml
- .github/workflows/_40_post_check.yml
- .github/workflows/upgrade-test.yml
Updates the `actions/setup-node` GitHub Action to the latest version. This ensures that the workflows are using the most up-to-date and secure version of the action that is compatible with the recent GitHub caching backend changes.
> ci: updates nodejs action version ⬆️

- .github/workflows/ci-development.yml
- bouncer/shared/utils/substrate.ts
- bouncer/tests/delegate_flip.ts
- bouncer/tests/fast_bouncer.test.ts
- engine/src/witness/eth/sc_utils.rs
- state-chain/cf-integration-tests/src/delegation.rs
- state-chain/chains/src/evm/api.rs
- state-chain/chains/src/evm/api/sc_utils.rs
- state-chain/chains/src/evm/api/sc_utils/deposit_flip_to_sc_gateway_and_call.rs
- state-chain/chains/src/evm/api/sc_utils/sc_call.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/tests.rs
- state-chain/pallets/cf-funding/src/lib.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-validator/src/weights.rs
- state-chain/runtime/src/chainflip/ethereum_sc_calls.rs
- state-chain/runtime/src/chainflip/vault_swaps.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- state-chain/traits/src/lib.rs
Fixes: PRO-2461
- `set_max_bid` didn't check that the account was delegating.
- added a test
- added `OnKilledAccount` implementation to ensure cleanup
ALSO: 
Changed the API: delegate and undelegate now take increase/decrease to update the max bid. 
Setting the max bid directly is no longer supported.
> fix: API changes (increase/decrease; remove set_max_bid) & delegator account cleanup

- Cargo.lock
- engine/src/witness/eth/sc_utils.rs
- state-chain/cf-integration-tests/src/mock_runtime.rs
- state-chain/node/src/chain_spec.rs
- state-chain/node/src/chain_spec/common.rs
- state-chain/pallets/cf-validator/Cargo.toml
- state-chain/pallets/cf-validator/src/auction_resolver.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations/remove_backups.rs
- state-chain/pallets/cf-validator/src/mock.rs
- state-chain/pallets/cf-validator/src/rotation_state.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-2440
optimizes the operator bids automatically during the auction so that operators can make the set by increasing their average bid by converting one of their validator nodes to a delegator thereby reducing the number of validators and increasing the average bid.
> feat: iteratively run auction to optimize operator bids

- Cargo.lock
- Cargo.toml
- engine/Cargo.toml
- engine/src/btc/cached_rpc.rs
- engine/src/btc/retry_rpc.rs
- engine/src/btc/rpc.rs
- engine/src/witness/btc.rs
- engine/src/witness/btc/fees.rs
- state-chain/pallets/cf-elections/src/electoral_systems/oracle_price/primitives.rs
- state-chain/pallets/cf-elections/src/electoral_systems/unsafe_median.rs
- state-chain/runtime/src/chainflip/bitcoin_elections.rs
- state-chain/runtime/src/migrations/bitcoin_elections.rs
Closes: PRO-2431
This PR:
- Adds a new method for bitcoin fee witnessing to the engine: random transactions from the mempool are sampled and we calculate the median fee of transactions expected to be in the *next* block. This has to parameters configurable via `ElectoralSettings`: "target sample size of txs in the next block" and "fixed fee adjustment value" (added on top of the calculated median). If the target sample size is set to 0, it falls back to the previous witnessing method. It also does this if for any reason the amount of txs sampled is less than half the target sample size.
- Changes the vote storage of `UnsafeMedian` to `Individual<Identity>` since now we don't expect any of the validators to vote with the same …
> feat: precise bitcoin mempool fee estimations

- state-chain/cf-integration-tests/src/delegation.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/src/lib.rs
Closes: PRO-2516
Sets a limit to the number of validators per operator. 
I renamed ManagedValidators to OperatorChoice (this is similar to DelegationChoice for delegators).
This way I can use ManagedValidators for a map of Operator to all current validators.
> feat: limit number of validators per operator to 20

- Cargo.lock
- api/bin/chainflip-lp-api/src/main.rs
- api/cf-rpc-apis/Cargo.toml
- api/cf-rpc-apis/src/lib.rs
- api/cf-rpc-apis/src/lp.rs
- state-chain/custom-rpc/src/backend.rs
- state-chain/custom-rpc/src/broker.rs
- state-chain/custom-rpc/src/lib.rs
- state-chain/custom-rpc/src/lp.rs
Closes: PRO-2444
Added optional parameter to the subscription to allow subscribing to best blocks instead of finalized only
> feat: allow `lp_subscribe_order_fills` to return best blocks

- CHANGELOG.md
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- engine/src/witness/btc.rs
- state-chain/node/Cargo.toml
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
Cherry-pick of PR #5995 that was against `release/1.10` and wasn't picked until now.
> fix: make voting for optimistic elections work independently of best_block_height

- Cargo.lock
- Cargo.toml
- engine/src/witness/btc/deposits.rs
- engine/src/witness/btc/vault_swaps.rs
- state-chain/chains/Cargo.toml
- state-chain/chains/src/refund_parameters.rs
- state-chain/pallets/cf-ingress-egress/Cargo.toml
- state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
- state-chain/pallets/cf-ingress-egress/src/lib.rs
- state-chain/pallets/cf-ingress-egress/src/migrations.rs
- state-chain/pallets/cf-ingress-egress/src/migrations/channel_action_ccm_refund.rs
- state-chain/pallets/cf-ingress-egress/src/mocks.rs
- state-chain/pallets/cf-ingress-egress/src/tests.rs
- state-chain/primitives/Cargo.toml
- state-chain/primitives/src/lib.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/runtime_apis.rs
- utilities/Cargo.toml
- utilities/src/without_std.rs
- utilities/src/without_std/bounded_vec.rs
Motivated as part of PRO-2451.
Closes: PRO-2553.
This extracts the ingress-egress pallet refactors of https://github.com/chainflip-io/chainflip-backend/pull/6038.
While working on the "refund undecodable bitcoin vault swaps"-PR (PRO-2451), I tried to understand the ingress-egress pallet, and in that process, came upon various places where the code could be improved. This PR is the result. It would be useful to merge this before working on PRO-2551.
1. When constructing ChannelAction::Refund, directly include the CcmDepositMetadata with source_chain and source_address. Then in BLS of "full witness" uses that instead of reconstructing it.
2. Make the `ChannelAction` struct parametric over it's CcmMetadata. At channel construction …
> refactor: better channel action handling in ingress-egress pallet

- engine/src/witness/common/epoch_source.rs
- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/v7.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-witnesser/src/benchmarking.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/epoch_info.rs
Previously it was possible for the total managed validator bonds to be set too low if any of the validators had more stake than the current bond. 
I also noticed that validators were able to register at lower than the min stake *if* the number of authorities were low. I removed this, it doesn't make much sense IMO.
> fix: ensure bond for managed validators is distributed correctly

- engine/src/witness/common/epoch_source.rs
- state-chain/pallets/cf-elections/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/benchmarking.rs
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/migrations.rs
- state-chain/pallets/cf-validator/src/migrations/v7.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/pallets/cf-witnesser/src/benchmarking.rs
- state-chain/runtime/src/lib.rs
- state-chain/traits/src/lib.rs
- state-chain/traits/src/mocks/epoch_info.rs
When an operator switches from allow to deny, any existing delegators need to be added to the exceptions list.
> fix: correctly update exceptions list with existing delegators

- CHANGELOG.md
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-validator/src/delegation.rs
- state-chain/pallets/cf-validator/src/lib.rs
- state-chain/pallets/cf-validator/src/tests.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/lib.rs
Contains some runtime-only fixes to delegation.
From these PRs:
- #6148 
- #6142 
One of the commits from the second PR was left out ([this](https://github.com/chainflip-io/chainflip-backend/pull/6142/commits/be71505da50c50faee83c57fca04e86c472882c6) one) - it was a non-functional refactor of the storage items. This would have broken engine compatibility, so I saved it for the next release.
> [RELEASE CANDIDATE] 1.11.6

- CHANGELOG.md
- Cargo.lock
- api/bin/chainflip-broker-api/Cargo.toml
- api/bin/chainflip-cli/Cargo.toml
- api/bin/chainflip-lp-api/Cargo.toml
- api/lib/Cargo.toml
- engine-dylib/Cargo.toml
- engine-proc-macros/Cargo.toml
- engine-runner-bin/Cargo.toml
- engine-runner-bin/src/main.rs
- engine-upgrade-utils/src/lib.rs
- engine/Cargo.toml
- state-chain/node/Cargo.toml
- state-chain/pallets/cf-elections/src/electoral_systems/oracle_price/state_machine.rs
- state-chain/pallets/cf-elections/src/electoral_systems/tests/oracle_price.rs
- state-chain/primitives/src/lib.rs
- state-chain/runtime/Cargo.toml
- state-chain/runtime/src/chainflip/generic_elections.rs
- state-chain/runtime/src/lib.rs
- state-chain/runtime/src/migrations/generic_elections.rs
Closes: PRO-2560
This is a pick of #6153. It additionally includes a runtime upgrade setting the oracle price election settings (increasing timeouts, lowering min price deviation parameter).
The new settings are: for both Eth and Arb the same:
- `up_to_date_timeout: Seconds(60 * 60)` (1h)
- `maybe_stale_timeout: Seconds(30)`
- `minimal_price_deviation: BasisPoints(5)`
> fix: [pick] always create price elections for eth and arb
